# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "0.2.0";
  date = "2023-06-30";
  module = "golang.org/x/vuln";
  subPackages = ["cmd/govulncheck"];
  go = "1.18";
  hash = "sha256-CNxXJMQmZm7SVzv4pjhHGj1TEoZqS3ylUtoH0YR959c=";

  mod = {
    "github.com/google/go-cmdtest" = {
      version = "v0.4.1-0.20220921163831-55ab3332a786";
      hash = "sha256-dH3Gt3hB7Hy+yOw8TOelffZ7xyLag1zLklpH3tbmeoI=";
      go = "1.12";
      packages = ["github.com/google/go-cmdtest"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.5.8";
      hash = "sha256-8zkIo+Sr1NXMnj3PNmvjX2sZKnAKWXOFvmnX7D9bwxQ=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/google/renameio" = {
      version = "v0.1.0";
      hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4=";
      go = "";
      packages = ["github.com/google/renameio"];
    };
    "golang.org/x/mod" = {
      version = "v0.10.0";
      hash = "sha256-g0T2wz+K0nhPWdVQJRGGqEqzlTHMBahv+9C3y090eIM=";
      go = "1.17";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.1.0";
      hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8=";
      go = "";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/sys" = {
      version = "v0.7.0";
      hash = "sha256-GotRHJaas/q3L+tFam0q3oQ1rc8GDStt7wnz9h8MTEU=";
      go = "1.17";
      packages = ["golang.org/x/sys/execabs"];
    };
    "golang.org/x/tools" = {
      version = "v0.8.1-0.20230421161920-b9619ee54b47";
      hash = "sha256-kxTAh6HTBXH0vgCcIMjYivKnK3hst20//xSAmERzCJA=";
      go = "1.18";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/callgraph" "golang.org/x/tools/go/callgraph/cha" "golang.org/x/tools/go/callgraph/vta" "golang.org/x/tools/go/callgraph/vta/internal/trie" "golang.org/x/tools/go/expect" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/internal/packagesdriver" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/packages/packagestest" "golang.org/x/tools/go/ssa" "golang.org/x/tools/go/ssa/ssautil" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/goroot" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/proxydir" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/tokeninternal" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal"];
    };
    "mvdan.cc/unparam" = {
      version = "v0.0.0-20230312165513-e84e2d14e3b8";
      hash = "sha256-kbEdOqX/p/FrNfWQ2WjXX+lERprSV2EI9l+kapHuFi4=";
      go = "1.19";
      packages = ["mvdan.cc/unparam/check"];
    };
  };
}
