# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "1.0.1";
  date = "2023-08-17";
  module = "golang.org/x/vuln";
  subPackages = ["cmd/govulncheck"];
  go = "1.18";
  hash = "sha256-fJnu1IXAowQJDbBH94mP3lfIBnf7swMSOW8UbwfVkek=";

  mod = {
    "github.com/google/go-cmdtest" = {
      version = "v0.4.1-0.20220921163831-55ab3332a786";
      hash = "sha256-dH3Gt3hB7Hy+yOw8TOelffZ7xyLag1zLklpH3tbmeoI=";
      go = "1.12";
      packages = ["github.com/google/go-cmdtest"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.5.8";
      hash = "sha256-8zkIo+Sr1NXMnj3PNmvjX2sZKnAKWXOFvmnX7D9bwxQ=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/google/renameio" = {
      version = "v0.1.0";
      hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4=";
      go = "";
      packages = ["github.com/google/renameio"];
    };
    "golang.org/x/mod" = {
      version = "v0.12.0";
      hash = "sha256-M/oXnzm7odpJdQzEnG6W0pNYtl0uhOM/l7qgfGVpU2M=";
      go = "1.17";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.3.0";
      hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o=";
      go = "1.17";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/sys" = {
      version = "v0.11.0";
      hash = "sha256-g/LjhABK2c/u6v7M2aAIrHvZjmx/ikGHkef86775N38=";
      go = "1.17";
      packages = ["golang.org/x/sys/execabs"];
    };
    "golang.org/x/tools" = {
      version = "v0.12.1-0.20230815132531-74c255bcf846";
      hash = "sha256-j6UwNGtMrqfwNyU4CImmqBYNkKjSDioYc+iJy3GKpw8=";
      go = "1.18";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/callgraph" "golang.org/x/tools/go/callgraph/cha" "golang.org/x/tools/go/callgraph/vta" "golang.org/x/tools/go/callgraph/vta/internal/trie" "golang.org/x/tools/go/expect" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/internal/packagesdriver" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/packages/packagestest" "golang.org/x/tools/go/ssa" "golang.org/x/tools/go/ssa/ssautil" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/event/tag" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/goroot" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/proxydir" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/tokeninternal" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal"];
    };
    "mvdan.cc/unparam" = {
      version = "v0.0.0-20230312165513-e84e2d14e3b8";
      hash = "sha256-kbEdOqX/p/FrNfWQ2WjXX+lERprSV2EI9l+kapHuFi4=";
      go = "1.19";
      packages = ["mvdan.cc/unparam/check"];
    };
  };
}
