# Auto-generated by goscrape - do not edit manually
{
  version = "1.5.0";
  date = "2026-06-25";
  module = "golang.org/x/vuln";
  subPackages = ["cmd/govulncheck"];
  go = "1.25.0";
  license = "BSD-3-Clause";
  hash = "sha256-i0TRsrJs1uMQOWVIvhLDMtfnMeHwz+8c4LSMJqf/6JM=";

  mod = {
    "github.com/google/go-cmdtest" = {
      version = "v0.4.1-0.20220921163831-55ab3332a786";
      hash = "sha256-dH3Gt3hB7Hy+yOw8TOelffZ7xyLag1zLklpH3tbmeoI=";
      go = "1.12";
      packages = ["github.com/google/go-cmdtest"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.6.0";
      hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/google/renameio" = {
      version = "v0.1.0";
      hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4=";
      go = "";
      packages = ["github.com/google/renameio"];
    };
    "golang.org/x/mod" = {
      version = "v0.37.0";
      hash = "sha256-dspScRv3KO4nytvjavhNO2b03P4UtiJQyWVGuEy9OUk=";
      go = "1.25.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.21.0";
      hash = "sha256-2n7PVb1krz7UpnXYGVmCrxV0fZBnjQdVVt6eVudEPYY=";
      go = "1.25.0";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/sys" = {
      version = "v0.46.0";
      hash = "sha256-NzRXMSEk6upeudJvUEPVnw6clJ3d8UdC/vdfANWAc8g=";
      go = "1.25.0";
      packages = [];
    };
    "golang.org/x/telemetry" = {
      version = "v0.0.0-20260625142307-59b4966ccb57";
      hash = "sha256-NymRmhUJZd33Ziexww/0pMgnuioRXcykAQcICdq8Qps=";
      go = "1.25.0";
      packages = ["golang.org/x/telemetry" "golang.org/x/telemetry/counter" "golang.org/x/telemetry/internal/config" "golang.org/x/telemetry/internal/configstore" "golang.org/x/telemetry/internal/counter" "golang.org/x/telemetry/internal/crashmonitor" "golang.org/x/telemetry/internal/mmap" "golang.org/x/telemetry/internal/telemetry" "golang.org/x/telemetry/internal/upload"];
    };
    "golang.org/x/tools" = {
      version = "v0.47.0";
      hash = "sha256-LyCNqEb/Jm94O6gaM01vXSHP9Yw/Cw0qVWXGxhCgwzo=";
      go = "1.25.0";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/ast/edge" "golang.org/x/tools/go/ast/inspector" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/callgraph" "golang.org/x/tools/go/callgraph/cha" "golang.org/x/tools/go/callgraph/internal/chautil" "golang.org/x/tools/go/callgraph/vta" "golang.org/x/tools/go/callgraph/vta/internal/trie" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/ssa" "golang.org/x/tools/go/ssa/ssautil" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/aliases" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/proxydir" "golang.org/x/tools/internal/stdlib" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal" "golang.org/x/tools/internal/versions"];
    };
    "golang.org/x/tools/go/expect" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-7JLwLMSzp9Eovnq7YBTv4Lgx8/FZnfMlx6ZkUdaW4dc=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/expect"];
    };
    "golang.org/x/tools/go/packages/packagestest" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-K3ljJg+gzsY/MAvrVSpWTzKlxOnXMCcsPHLQvH7JRbU=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/packages/packagestest"];
    };
  };
}
