# Auto-generated by goscrape - do not edit manually
{
  version = "1.8.0";
  date = "2026-09-08";
  module = "golang.org/x/vuln";
  subPackages = ["cmd/govulncheck"];
  go = "1.26.0";
  license = "BSD-3-Clause";
  hash = "sha256-c52y9cHE2cw0kXba2qjx/4yuNLIH9U67w6/TXY/iZ/8=";

  mod = {
    "github.com/google/go-cmdtest" = {
      version = "v0.4.1-0.20220921163831-55ab3332a786";
      hash = "sha256-dH3Gt3hB7Hy+yOw8TOelffZ7xyLag1zLklpH3tbmeoI=";
      go = "1.12";
      packages = ["github.com/google/go-cmdtest"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.6.0";
      hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/google/renameio" = {
      version = "v0.1.0";
      hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4=";
      go = "";
      packages = ["github.com/google/renameio"];
    };
    "golang.org/x/mod" = {
      version = "v0.41.0";
      hash = "sha256-euzxa6DC2qmU+LgEwjOM71nc/lRrU9XRC9nESAaDw6Q=";
      go = "1.26.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.23.0";
      hash = "sha256-nF8YZFVC+TitjkderlqgGwJkuMqJCxI+fIElVLjBT2M=";
      go = "1.26.0";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/sys" = {
      version = "v0.48.0";
      hash = "sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls=";
      go = "1.26.0";
      packages = ["golang.org/x/sys/windows"];
    };
    "golang.org/x/telemetry" = {
      version = "v0.0.0-20260908163034-4bcc4b2ee518";
      hash = "sha256-N0nlsmcsCRVsez47/YoY1S3tLukJeUqCB5+/oFNGvPo=";
      go = "1.26.0";
      packages = ["golang.org/x/telemetry" "golang.org/x/telemetry/counter" "golang.org/x/telemetry/internal/config" "golang.org/x/telemetry/internal/configstore" "golang.org/x/telemetry/internal/counter" "golang.org/x/telemetry/internal/crashmonitor" "golang.org/x/telemetry/internal/mmap" "golang.org/x/telemetry/internal/telemetry" "golang.org/x/telemetry/internal/upload"];
    };
    "golang.org/x/tools" = {
      version = "v0.50.0";
      hash = "sha256-BjwWAoexahydRI7Tn98NMRfRPlW8ag5jTENGODYFTaU=";
      go = "1.26.0";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/ast/edge" "golang.org/x/tools/go/ast/inspector" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/callgraph" "golang.org/x/tools/go/callgraph/cha" "golang.org/x/tools/go/callgraph/internal/chautil" "golang.org/x/tools/go/callgraph/vta" "golang.org/x/tools/go/callgraph/vta/internal/trie" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/ssa" "golang.org/x/tools/go/ssa/ssautil" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/aliases" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/moremaps" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/proxydir" "golang.org/x/tools/internal/stdlib" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal" "golang.org/x/tools/internal/versions"];
    };
    "golang.org/x/tools/go/expect" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-7JLwLMSzp9Eovnq7YBTv4Lgx8/FZnfMlx6ZkUdaW4dc=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/expect"];
    };
    "golang.org/x/tools/go/packages/packagestest" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-K3ljJg+gzsY/MAvrVSpWTzKlxOnXMCcsPHLQvH7JRbU=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/packages/packagestest"];
    };
  };
}
