# Auto-generated by goscrape - do not edit manually
{
  "1.3.0" = {go = "1.25.0"; license = "BSD-3-Clause";};
  "1.2.0" = {go = "1.25.0"; license = "BSD-3-Clause";};
  "1.1.4" = {go = "1.22.0"; license = "BSD-3-Clause";};
  "1.1.3" = {go = "1.21"; license = "BSD-3-Clause";};
  "1.1.2" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.1.1" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.1.0" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.0.4" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.0.3" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.0.2" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.0.1" = {go = "1.18"; license = "BSD-3-Clause";};
  "1.0.0" = {go = "1.18"; license = "BSD-3-Clause";};
  "0.2.0" = {go = "1.18"; license = "BSD-3-Clause";};
  "0.1.0" = {go = "1.18"; license = "BSD-3-Clause";};
}
