# Auto-generated by go-scrape - do not edit manually
{
  version = "1.22.3";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "610e48c1df4d2f852de8bc2e7fd2dc1521aac216f0c0026625db12f67f192024";
    url = "https://go.dev/dl/go1.22.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "02abeab3f4b8981232237ebd88f0a9bad933bc9621791cd7720a9ca29eacbe9d";
    url = "https://go.dev/dl/go1.22.3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b9989ca87695ae93bacde6f3aa7b13cde5f3825515eb9ed9bbef014273739889";
    url = "https://go.dev/dl/go1.22.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "7483961fae29d7d768afd5c9c0f229354ca3263ab7119c20bc182761f87cbc74";
    url = "https://go.dev/dl/go1.22.3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "572eb70e5e835fbff7d53ebf473f611d7eb458c428f8dbd98a49196883c3309e";
    url = "https://go.dev/dl/go1.22.3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "fefba30bb0d3dd1909823ee38c9f1930c3dc5337a2ac4701c2277a329a386b57";
    url = "https://go.dev/dl/go1.22.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36";
    url = "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "6c33e52a5b26e7aa021b94475587fce80043a727a54ceb0eee2f9fc160646434";
    url = "https://go.dev/dl/go1.22.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "f2bacad20cd2b96f23a86d4826525d42b229fd431cc6d0dec61ff3bc448ef46e";
    url = "https://go.dev/dl/go1.22.3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "41e9328340544893482b2928ae18a9a88ba18b2fdd29ac77f4d33cf1815bbdc2";
    url = "https://go.dev/dl/go1.22.3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "04b7b05283de30dd2da20bf3114b2e22cc727938aed3148babaf35cc951051ac";
    url = "https://go.dev/dl/go1.22.3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "d4992d4a85696e3f1de06cefbfc2fd840c9c6695d77a0f35cfdc4e28b2121c20";
    url = "https://go.dev/dl/go1.22.3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "2aba796417a69be5f3ed489076bac79c1c02b36e29422712f9f3bf51da9cf2d4";
    url = "https://go.dev/dl/go1.22.3.linux-s390x.tar.gz";
  };
}
