# Auto-generated by goscrape - do not edit manually
{
  version = "0.12.0";
  date = "2026-09-07";
  module = "mvdan.cc/gofumpt";
  subPackages = ["."];
  go = "1.26.0";
  license = "BSD-3-Clause";
  hash = "sha256-SA40ufLitByv7W/kCTBjvJURg8f4Sgzq24k7KJicqRQ=";

  mod = {
    "github.com/go-quicktest/qt" = {
      version = "v1.102.0";
      hash = "sha256-Ys/kyQzyoaUHYoo1BlrZ80Ev1DeyDCgSHQdiCMYzF1E=";
      go = "1.18";
      packages = ["github.com/go-quicktest/qt"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.7.0";
      hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM=";
      go = "1.21";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/kr/pretty" = {
      version = "v0.3.1";
      hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU=";
      go = "1.12";
      packages = ["github.com/kr/pretty"];
    };
    "github.com/kr/text" = {
      version = "v0.2.0";
      hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE=";
      go = "";
      packages = ["github.com/kr/text"];
    };
    "github.com/rogpeppe/go-internal" = {
      version = "v1.16.0";
      hash = "sha256-taz3iAUJayomgTV637S27ZkI4VD7ulkOVdMj68woTxE=";
      go = "1.25";
      packages = ["github.com/rogpeppe/go-internal/diff" "github.com/rogpeppe/go-internal/fmtsort" "github.com/rogpeppe/go-internal/gotooltest" "github.com/rogpeppe/go-internal/imports" "github.com/rogpeppe/go-internal/internal/goenv" "github.com/rogpeppe/go-internal/internal/misspell" "github.com/rogpeppe/go-internal/internal/os/execpath" "github.com/rogpeppe/go-internal/par" "github.com/rogpeppe/go-internal/testenv" "github.com/rogpeppe/go-internal/testscript" "github.com/rogpeppe/go-internal/testscript/internal/pty" "github.com/rogpeppe/go-internal/txtar"];
    };
    "golang.org/x/mod" = {
      version = "v0.40.0";
      hash = "sha256-gmuKtxidzYWVlQYNB/8BREmajyfockaQ5/6Xk4IR32A=";
      go = "1.25.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.22.0";
      hash = "sha256-VZjl0fAM0p/nI81zh+pdBjzxFupx0UcKYXBBpL2ZS7k=";
      go = "1.25.0";
      packages = ["golang.org/x/sync/semaphore"];
    };
    "golang.org/x/sys" = {
      version = "v0.47.0";
      hash = "sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98=";
      go = "1.25.0";
      packages = ["golang.org/x/sys/unix"];
    };
    "golang.org/x/tools" = {
      version = "v0.49.0";
      hash = "sha256-3oaXp2PlfuIn6/UTarnYD279YqJKTyaCWT/KD7ABjD4=";
      go = "1.25.0";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/txtar"];
    };
  };
}
