# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "0.6.0";
  date = "2024-01-28";
  module = "mvdan.cc/gofumpt";
  subPackages = ["."];
  go = "1.20";
  hash = "sha256-2M9yKlAN0Oe88vBfMED0SJE0XMJfzOMd8Bd2ot/ZMko=";

  mod = {
    "github.com/frankban/quicktest" = {
      version = "v1.14.6";
      hash = "sha256-4DRq4JlaahwdLSQlx8gVuMoC4U9JmDI84jeNx8hO0D4=";
      go = "1.13";
      packages = ["github.com/frankban/quicktest"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.6.0";
      hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/kr/pretty" = {
      version = "v0.3.1";
      hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU=";
      go = "1.12";
      packages = ["github.com/kr/pretty"];
    };
    "github.com/kr/text" = {
      version = "v0.2.0";
      hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE=";
      go = "";
      packages = ["github.com/kr/text"];
    };
    "github.com/rogpeppe/go-internal" = {
      version = "v1.12.0";
      hash = "sha256-qvDNCe3l84/LgrA8X4O15e1FeDcazyX91m9LmXGXX6M=";
      go = "1.20";
      packages = ["github.com/rogpeppe/go-internal/diff" "github.com/rogpeppe/go-internal/fmtsort" "github.com/rogpeppe/go-internal/gotooltest" "github.com/rogpeppe/go-internal/imports" "github.com/rogpeppe/go-internal/internal/misspell" "github.com/rogpeppe/go-internal/internal/os/execpath" "github.com/rogpeppe/go-internal/par" "github.com/rogpeppe/go-internal/testenv" "github.com/rogpeppe/go-internal/testscript" "github.com/rogpeppe/go-internal/testscript/internal/pty" "github.com/rogpeppe/go-internal/txtar"];
    };
    "golang.org/x/mod" = {
      version = "v0.14.0";
      hash = "sha256-sx3hWp5l99DBfIrn821ohfoBwvaITSHMWbzPvX0btLM=";
      go = "1.18";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.6.0";
      hash = "sha256-LLims/wjDZtIqlYCVHREewcUOX4hwRwplEuZKPOJ/HI=";
      go = "1.18";
      packages = ["golang.org/x/sync/semaphore"];
    };
    "golang.org/x/sys" = {
      version = "v0.16.0";
      hash = "sha256-ZkGclbp2S7NQYhbuGji6XokCn2Qi1BJy8dwyAOTV8sY=";
      go = "1.18";
      packages = ["golang.org/x/sys/unix"];
    };
    "golang.org/x/tools" = {
      version = "v0.17.0";
      hash = "sha256-CxuHfKKtUkn3VjA7D9WQjzvV1EUbyI/xMNhb5CxO6IQ=";
      go = "1.18";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/txtar"];
    };
  };
}
