# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "0.8.0";
  date = "2025-04-13";
  module = "mvdan.cc/gofumpt";
  subPackages = ["."];
  go = "1.23.0";
  hash = "sha256-alW9ArCNJwsrsRsY4LQEj9PPvAmiPutuuxoQ+hn/2fs=";

  mod = {
    "github.com/go-quicktest/qt" = {
      version = "v1.101.0";
      hash = "sha256-/dGNGhn9Jvdb6D95qbN1DLfS6H7ZS4G4AubU9zUDgdU=";
      go = "1.18";
      packages = ["github.com/go-quicktest/qt"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.6.0";
      hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg=";
      go = "1.13";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/cmpopts" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "github.com/kr/pretty" = {
      version = "v0.3.1";
      hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU=";
      go = "1.12";
      packages = ["github.com/kr/pretty"];
    };
    "github.com/kr/text" = {
      version = "v0.2.0";
      hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE=";
      go = "";
      packages = ["github.com/kr/text"];
    };
    "github.com/rogpeppe/go-internal" = {
      version = "v1.14.1";
      hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E=";
      go = "1.23";
      packages = ["github.com/rogpeppe/go-internal/diff" "github.com/rogpeppe/go-internal/fmtsort" "github.com/rogpeppe/go-internal/gotooltest" "github.com/rogpeppe/go-internal/imports" "github.com/rogpeppe/go-internal/internal/misspell" "github.com/rogpeppe/go-internal/internal/os/execpath" "github.com/rogpeppe/go-internal/par" "github.com/rogpeppe/go-internal/testenv" "github.com/rogpeppe/go-internal/testscript" "github.com/rogpeppe/go-internal/testscript/internal/pty" "github.com/rogpeppe/go-internal/txtar"];
    };
    "golang.org/x/mod" = {
      version = "v0.24.0";
      hash = "sha256-Lrl4RzOO0J/S5E+AQ7Y6yh8B9yygvZ2W0fsKEtBSYNU=";
      go = "1.23.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.13.0";
      hash = "sha256-CElRNe74Or/ysUkb/m3Wcz/juO/tB5fhQbAaxA5AizY=";
      go = "1.23.0";
      packages = ["golang.org/x/sync/semaphore"];
    };
    "golang.org/x/sys" = {
      version = "v0.32.0";
      hash = "sha256-c9RRnyKQy9Kl8hpbtcgkm1O5H7gOdk9Rv925F8fZS6E=";
      go = "1.23.0";
      packages = ["golang.org/x/sys/unix"];
    };
    "golang.org/x/tools" = {
      version = "v0.32.0";
      hash = "sha256-nCcgtl0trmuGKWvMkJ2Rn4Q8CnNATdVrBfA1sgLGPUk=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/txtar"];
    };
  };
}
