# Auto-generated by goscrape - do not edit manually
{
  "0.10.0" = {go = "1.25.0"; license = "BSD-3-Clause";};
  "0.9.2" = {go = "1.24.0"; license = "BSD-3-Clause";};
  "0.9.1" = {go = "1.24.0"; license = "BSD-3-Clause";};
  "0.9.0" = {go = "1.24.0"; license = "BSD-3-Clause";};
  "0.8.0" = {go = "1.23.0"; license = "BSD-3-Clause";};
  "0.7.0" = {go = "1.22"; license = "BSD-3-Clause";};
  "0.6.0" = {go = "1.20"; license = "BSD-3-Clause";};
  "0.5.0" = {go = "1.19"; license = "BSD-3-Clause";};
  "0.4.0" = {go = "1.18"; license = "BSD-3-Clause";};
  "0.3.1" = {go = "1.17"; license = "BSD-3-Clause";};
}
