# Auto-generated by go-scrape - do not edit manually
{
  version = "1.18.8";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "683ac9bf32731d6a1b31489d733f91fb4cb1203430c046d89362916b4325815d";
    url = "https://go.dev/dl/go1.18.8.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "19f66ce3205c3511fed4bf1ec75c63f79953538a660bc83a095eca72425ce7d1";
    url = "https://go.dev/dl/go1.18.8.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "1732f4977f7c3cdc26810d949313ed0ebfe5f63c31c9c4d15c957f2138ac81ae";
    url = "https://go.dev/dl/go1.18.8.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "b0000cde0ec57483725f1258bf8ea14a50b1b0ba858be123d84cb8ccac75f9ec";
    url = "https://go.dev/dl/go1.18.8.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "2dafc6558753e3f39826823731d33acdddefef0a5e8aa37e44da621c66e899f1";
    url = "https://go.dev/dl/go1.18.8.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4d854c7bad52d53470cf32f1b287a5c0c441dc6b98306dea27358e099698142a";
    url = "https://go.dev/dl/go1.18.8.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "df71bc84d84f7f62dad06aca5e1b8234045dce94a94dcefe71af0cb8f6e93a87";
    url = "https://go.dev/dl/go1.18.8.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "71bc2263f91d5f11e189db543ea0cf1288ef3720ae9f6b8a31805275d0b1f428";
    url = "https://go.dev/dl/go1.18.8.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "e254ec42ec2673bf77b4ec8ad0ca62768dc0675c0cd4567658e2aa585c877fd6";
    url = "https://go.dev/dl/go1.18.8.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "54f7970bb6cf6658a42ba40383476a3803cef187c2970dddeb3c3c6ef5758110";
    url = "https://go.dev/dl/go1.18.8.linux-s390x.tar.gz";
  };
}
