# Auto-generated by go-scrape - do not edit manually
{
  version = "1.18.3";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "d9dcf8fc35da54c6f259be41954783a9f4984945a855d03a003a7fd6ea4c5ca1";
    url = "https://go.dev/dl/go1.18.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "40ecd383c941cc9f0682e6a6f2a333539d58c7dea15c842434d03afafe2f7242";
    url = "https://go.dev/dl/go1.18.3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "dbf06c8b76f7e9bd2f2b8d47d8c748e9867c2bbbdb2e90240d54df3e5766ad18";
    url = "https://go.dev/dl/go1.18.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "b1c60641aa175aa92edf494e942e37db28086b9d534f072ad9609d081b614d39";
    url = "https://go.dev/dl/go1.18.3.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "72b73da021397a3a1ce182c19d2a890a5346bfe80885d9dd7d1ff04ce6597938";
    url = "https://go.dev/dl/go1.18.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245";
    url = "https://go.dev/dl/go1.18.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "beacbe1441bee4d7978b900136d1d6a71d150f0a9bb77e9d50c822065623a35a";
    url = "https://go.dev/dl/go1.18.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "b8f0b5db24114388d5dcba7ca0698510ea05228b0402fcbeb0881f74ae9cb83b";
    url = "https://go.dev/dl/go1.18.3.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "5d42bd252e7af9f854df92e46bb2e88be7b2fb310cc937c0fe091afd8c4f2016";
    url = "https://go.dev/dl/go1.18.3.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "ebb4efddec5bbd22bdd9c87137cb3dd59e874b5dfcf93d00bef351c60d2c7401";
    url = "https://go.dev/dl/go1.18.3.linux-s390x.tar.gz";
  };
}
