# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17.1";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "3c452046b1dfa27b70d3217c9fe6de266f9fd74d83aad81382fead70efcdffca";
    url = "https://go.dev/dl/go1.17.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "48f48a3cfe49b7bb448510ec9bf1682439e4e95fa6888580914a3115fe853d8c";
    url = "https://go.dev/dl/go1.17.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "e945a5cfb2d4acd434d606175c69202a7d28660630839ade9907facec702870f";
    url = "https://go.dev/dl/go1.17.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "cfa16e98602a88fc80aca045a271e45b76fc30a6bd472c67329ebd362dd984d0";
    url = "https://go.dev/dl/go1.17.1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "e60bb44046f424ba2cc47db7b183079b5add2f8cfa6887daf45bf2f317cc2f53";
    url = "https://go.dev/dl/go1.17.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "dab7d9c34361dc21ec237d584590d72500652e7c909bf082758fb63064fca0ef";
    url = "https://go.dev/dl/go1.17.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "53b29236fa03ed862670a5e5e2ab2439a2dc288fe61544aa392062104ac0128c";
    url = "https://go.dev/dl/go1.17.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ed3e4dbc9b80353f6482c441d65b51808290e94ff1d15d56da5f4a7be7353758";
    url = "https://go.dev/dl/go1.17.1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "df4fa945512c3b472cf3d2dcb2e4ae5b34819607bc63f3223f5bc0c17b637dd0";
    url = "https://go.dev/dl/go1.17.1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "f770b72e1e1281239b12b64825f87a928a1788943c7f09cac7f28985ef2cf692";
    url = "https://go.dev/dl/go1.17.1.linux-s390x.tar.gz";
  };
}
