# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "355bd544ce08d7d484d9d7de05a71b5c6f5bc10aa4b316688c2192aeb3dacfd1";
    url = "https://go.dev/dl/go1.17.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "da4e3e3c194bf9eed081de8842a157120ef44a7a8d7c820201adae7b0e28b20b";
    url = "https://go.dev/dl/go1.17.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "6819a7a11b8351d5d5768f2fff666abde97577602394f132cb7f85b3a7151f05";
    url = "https://go.dev/dl/go1.17.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "15c184c83d99441d719da201b26256455eee85a808747c404b4183e9aa6c64b4";
    url = "https://go.dev/dl/go1.17.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "c19e3227a6ac6329db91d1af77bbf239ccd760a259c16e6b9c932d527ff14848";
    url = "https://go.dev/dl/go1.17.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d";
    url = "https://go.dev/dl/go1.17.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "01a9af009ada22122d3fcb9816049c1d21842524b38ef5d5a0e2ee4b26d7c3e7";
    url = "https://go.dev/dl/go1.17.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ae89d33f4e4acc222bdb04331933d5ece4ae71039812f6ccd7493cb3e8ddfb4e";
    url = "https://go.dev/dl/go1.17.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "ee84350114d532bf15f096198c675aafae9ff091dc4cc69eb49e1817ff94dbd7";
    url = "https://go.dev/dl/go1.17.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "a50aaecf054f393575f969a9105d5c6864dd91afc5287d772449033fbafcf7e3";
    url = "https://go.dev/dl/go1.17.linux-s390x.tar.gz";
  };
}
