# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17.10";
  date = "2025-12-08";

  "x86_64-darwin" = {
    sha256 = "84979d5985c70cee6f303050a7e811440aad7f304efdf28665b200f096b01945";
    url = "https://go.dev/dl/go1.17.10.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "32098bea40117ea1ec23e7124cd188db6bdddd0ea41e2ec9bea3ba35a487e39c";
    url = "https://go.dev/dl/go1.17.10.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "37f005846d70f477e89fcf7279f8869c28ba1d266cebf794d2f7a79a1e2127ec";
    url = "https://go.dev/dl/go1.17.10.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "33794d96f58608fdc023c5114ae9baeeb4111a74720c8830ff25029debe508f0";
    url = "https://go.dev/dl/go1.17.10.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "5c45aad27c3091b07517ed57df5650dad5b3b71111cebdf83153878f140ad981";
    url = "https://go.dev/dl/go1.17.10.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "87fc728c9c731e2f74e4a999ef53cf07302d7ed3504b0839027bd9c10edaa3fd";
    url = "https://go.dev/dl/go1.17.10.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "649141201efa7195403eb1301b95dc79c5b3e65968986a391da1370521701b0c";
    url = "https://go.dev/dl/go1.17.10.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ad2d9053011c24be07c39f337f4a31987381d905874acbf2570511e050418dd3";
    url = "https://go.dev/dl/go1.17.10.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "4e2310864fa9d5a4e2d589dbc5fcd98ce8c4cd25320b335efed04dc67765e66c";
    url = "https://go.dev/dl/go1.17.10.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "e1df61f29fb0962b89d7bfe18b7db45eee003d5f8a1a7ff4d9e54616689076bf";
    url = "https://go.dev/dl/go1.17.10.linux-s390x.tar.gz";
  };
}
