# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21.2";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "31db09a0ebaf89a3efa15a84cc67d4a8b60ae4aace9e6818e453d72be64f76bd";
    url = "https://go.dev/dl/go1.21.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "7534d79f1955b57971092a91d2ce683fc49352c6130e2c9411357031c05437a4";
    url = "https://go.dev/dl/go1.21.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "3ac3c5e1ec1f42e8394ae0803c2ca5570ddc4026d82ddf9010a8bdd24e419a54";
    url = "https://go.dev/dl/go1.21.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "63a0c772ba671b11a1da2df69424be051cfb3ea61017b28a32d41492e4114826";
    url = "https://go.dev/dl/go1.21.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "5289bdba92c3127b613050b0516d7ca8e7d0506a58e0ccc1f14d84b65ec32f73";
    url = "https://go.dev/dl/go1.21.2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "e2ccb4121a328c3fa297c6d653cc0a625a06935313c2367f8e026c3af56869c5";
    url = "https://go.dev/dl/go1.21.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "f5414a770e5e11c6e9674d4cd4dd1f4f630e176d1828d3427ea8ca4211eee90d";
    url = "https://go.dev/dl/go1.21.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "23e208ca44a3cb46cd4308e48a27c714ddde9c8c34f2e4211dbca95b6d456554";
    url = "https://go.dev/dl/go1.21.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "8727d842176a2bfd9edf307ed5411c39a69e2c6a748098987be361e8e0c36b46";
    url = "https://go.dev/dl/go1.21.2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "9e9e5eed5777147d7811ed090f1e7dda44e18b89ba17ff416f97f1d365b8f15b";
    url = "https://go.dev/dl/go1.21.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "429ae21664ee12fdddc9a04fd0646879da34d81fe3fd316d57250e7fd50e7c6b";
    url = "https://go.dev/dl/go1.21.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "040a6c0978bb4022b36a4c3c6077585ce98295d5eac4195ff15a5a3966904a3b";
    url = "https://go.dev/dl/go1.21.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "544c867180bf3384396b0906a7f14f4dc26bb7e78d4b05a8b45557b1b0ce0376";
    url = "https://go.dev/dl/go1.21.2.linux-s390x.tar.gz";
  };
}
