# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21.3";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "27014fc69e301d7588a169ca239b3cc609f0aa1abf38528bf0d20d3b259211eb";
    url = "https://go.dev/dl/go1.21.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "65302a7a9f7a4834932b3a7a14cb8be51beddda757b567a2f9e0cbd0d7b5a6ab";
    url = "https://go.dev/dl/go1.21.3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "8e0cd2f66cf1bde9d07b4aee01e3d7c3cfdd14e20650488e1683da4b8492594a";
    url = "https://go.dev/dl/go1.21.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6e74f65f586e93d1f3947894766f69e9b2ebda488592a09df61f36f06bfe58a8";
    url = "https://go.dev/dl/go1.21.3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "8e85103b559ae2a3b95530995645ce86fb0a89ca8e56f41339297133fb215dec";
    url = "https://go.dev/dl/go1.21.3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "fb209fd070db500a84291c5a95251cceeb1723e8f6142de9baca5af70a927c0e";
    url = "https://go.dev/dl/go1.21.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "1241381b2843fae5a9707eec1f8fb2ef94d827990582c7c7c32f5bdfbfd420c8";
    url = "https://go.dev/dl/go1.21.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "fc90fa48ae97ba6368eecb914343590bbb61b388089510d0c56c2dde52987ef3";
    url = "https://go.dev/dl/go1.21.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "a1ddcaaf0821a12a800884c14cb4268ce1c1f5a0301e9060646f1e15e611c6c7";
    url = "https://go.dev/dl/go1.21.3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "215b71c99fb5aee9ed42f585de4eb4b0f99ae43b621c4692d1fd0b4643c2cbff";
    url = "https://go.dev/dl/go1.21.3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "3b0e10a3704f164a6e85e0377728ec5fd21524fabe4c925610e34076586d5826";
    url = "https://go.dev/dl/go1.21.3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "67d14d3e513e505d1ec3ea34b55641c6c29556603c7899af94045c170c1c0f94";
    url = "https://go.dev/dl/go1.21.3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "4c78e2e6f4c684a3d5a9bdc97202729053f44eb7be188206f0627ef3e18716b6";
    url = "https://go.dev/dl/go1.21.3.linux-s390x.tar.gz";
  };
}
