# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21.11";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "a3efff72f7aba31c85b53ebfd3985d0e3157a87b0e69e178161ba7097c197885";
    url = "https://go.dev/dl/go1.21.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "0142f5ac9f9a1bf19b826ee08a8c7955a745f7a2e62d36e0566d29fcac4d88e0";
    url = "https://go.dev/dl/go1.21.11.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "718351eacf1f75e5114033e0c2fdb48b92b447a62244676b054e11073dda1203";
    url = "https://go.dev/dl/go1.21.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "b1737199d1e96e785ec732ec4fc3ffa84b7ceab512ad7bfb18022d65acf55458";
    url = "https://go.dev/dl/go1.21.11.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "24f9d073a6ade5b7b8445a345dd40f9d4276ffe8fbed8b0efe0bc49544e34335";
    url = "https://go.dev/dl/go1.21.11.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "8b00cbc2519c2d052177bf2c8472bf06578d3b0182eeb3406a1d7d4e5d4c59ef";
    url = "https://go.dev/dl/go1.21.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "54a87a9325155b98c85bc04dc50298ddd682489eb47f486f2e6cb0707554abf0";
    url = "https://go.dev/dl/go1.21.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "715d9a7ff72e4e0e3378c48318c52c6e4dd32a47c4136f3c08846f89b2ee2241";
    url = "https://go.dev/dl/go1.21.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "a62bff8297816a387a36bbda2889dd0dbcf0f8ce03bc62162ecd6918d6acecb5";
    url = "https://go.dev/dl/go1.21.11.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "19c738e3670efb6581a91d7d93e719080ccf710684938d015ab3e7ca044715be";
    url = "https://go.dev/dl/go1.21.11.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "6f5e18187abc4ff1c3173afbe38ef29f84b6d1ee7173f40075a4134863b209a5";
    url = "https://go.dev/dl/go1.21.11.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "3ee5f9aac2f252838d88bb4cf93560c567814889c74d87ad8a04be16aa5e1b21";
    url = "https://go.dev/dl/go1.21.11.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "489c363d5da2d3d5709419bda61856582c5ebdc7874ca7ecdebf67d736d329e6";
    url = "https://go.dev/dl/go1.21.11.linux-s390x.tar.gz";
  };
}
