# Auto-generated by goscrape - do not edit manually
{
  version = "1.17.4";
  date = "2021-12-02";

  "x86_64-darwin" = {
    sha256 = "52c8328fbfb879fcca607f84663977138bfdaa17c7202897f9b63bed55665328";
    url = "https://go.dev/dl/go1.17.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "0f419ccc3b6bc26e1be05a328e3099a62340212d4f1c5cd3b0a0a4f2f435b592";
    url = "https://go.dev/dl/go1.17.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "3d069055f58dcfbfcecacfc59c77166c2b0fa5b5ab1d630756fa38495f543fb6";
    url = "https://go.dev/dl/go1.17.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "80099cb7ba1810e20a6b2fa3cb3eccbb69e3105d07ab1c9496c9abeda2837bf6";
    url = "https://go.dev/dl/go1.17.4.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "276bda8e8efa59482b0be87394566e02ff7a860b65e8b6ccc90c026dbcab1f74";
    url = "https://go.dev/dl/go1.17.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "adab2483f644e2f8a10ae93122f0018cef525ca48d0b8764dae87cb5f4fd4206";
    url = "https://go.dev/dl/go1.17.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "617a46bd083e59877bb5680998571b3ddd4f6dcdaf9f8bf65ad4edc8f3eafb13";
    url = "https://go.dev/dl/go1.17.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "f34d25f818007345b716b316908115ba462f3f0dbd4343073020b544b4ae2320";
    url = "https://go.dev/dl/go1.17.4.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "d185567480d9e335d4d9274804ef9fa796b01e53c7290a744871d0c0fac2f248";
    url = "https://go.dev/dl/go1.17.4.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "63e4e2065aa3139b4d9a203fa7e39a810f67e9f4753492726d485c17c37cd817";
    url = "https://go.dev/dl/go1.17.4.linux-s390x.tar.gz";
  };
}
