# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17.9";
  date = "2022-04-12";

  "x86_64-darwin" = {
    sha256 = "af9f9deabd6e8a9d219b695b81c19276e2cd5bbc1215741e3bb1b18e88147990";
    url = "https://go.dev/dl/go1.17.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "1f8a0312bdf991d63734c2fd5693b06b053dfb0cce8f204c7c790a50b22cab03";
    url = "https://go.dev/dl/go1.17.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "d74a535afdb2be11403495fc204e47d345d4341c1a093d12e9b84ae0f4bdc843";
    url = "https://go.dev/dl/go1.17.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "c4850c10ee7bfcfe211666f08b1ef3a04c3361808793b6bff4bebb965565056b";
    url = "https://go.dev/dl/go1.17.9.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "382d4207a8a3edb531fcb19dc10b71e51a6d939aedbc15efef92b93b9c1f4e2c";
    url = "https://go.dev/dl/go1.17.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "9dacf782028fdfc79120576c872dee488b81257b1c48e9032d122cfdb379cca6";
    url = "https://go.dev/dl/go1.17.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "44dcdcd4f0fa6f83c15ef70b31580f1e3f95895c2f11a00e36c440c3554b6ad5";
    url = "https://go.dev/dl/go1.17.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "548543479c8d9b3eb9713ed21a7e0b5f2c90f971977db0bfadfa6eff7933282c";
    url = "https://go.dev/dl/go1.17.9.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "5624fb69571b80c00bb1e7b977c9c1b6c1258d791ed904a285fdfd1b247a75ce";
    url = "https://go.dev/dl/go1.17.9.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "51180a0c7c0f31524db5a0322a49f3024075b46064101cc95e8b983148c939f1";
    url = "https://go.dev/dl/go1.17.9.linux-s390x.tar.gz";
  };
}
