# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17.12";
  date = "2022-07-12";

  "x86_64-darwin" = {
    sha256 = "8c5812f678c437a79797270da44b33f2c53fd02b8843894063fa830a03a0a366";
    url = "https://go.dev/dl/go1.17.12.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a1a7324c3117565d78703d91e9288b7a7ca44eabb4d03fbd327e43c270b80464";
    url = "https://go.dev/dl/go1.17.12.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9fbb09a0941a92ae42ccbb7f6e7a5ec8c6e40e1f48ab5b0194789cf07178bf0f";
    url = "https://go.dev/dl/go1.17.12.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "88088e6465b7d1d3147aff053654594286e35f48af32cbc4387904bd648221f7";
    url = "https://go.dev/dl/go1.17.12.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "fbc850c5caa86c1cf422ced6875c25b2a9e93b49ea80273894bdb2617c958d76";
    url = "https://go.dev/dl/go1.17.12.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "6e5203fbdcade4aa4331e441fd2e1db8444681a6a6c72886a37ddd11caa415d4";
    url = "https://go.dev/dl/go1.17.12.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "74a4832d0f150a2d768a6781553494ba84152e854ebef743c4092cd9d1f66a9f";
    url = "https://go.dev/dl/go1.17.12.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "8bab372c85336574f620fc69618a102102196c01ce71911c521570adb5803fdf";
    url = "https://go.dev/dl/go1.17.12.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "da1585fa7c17b54419303b58341739bc30c212f17137f93c80ccaff4003e7c7f";
    url = "https://go.dev/dl/go1.17.12.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "5f2a6b4a792058ad3ef4cb1444a7800ed327e271d6dd04e01b8244273b67a945";
    url = "https://go.dev/dl/go1.17.12.linux-s390x.tar.gz";
  };
}
