# Auto-generated by go-scrape - do not edit manually
{
  version = "1.17.11";
  date = "2025-12-08";

  "x86_64-darwin" = {
    sha256 = "4f924c534230de8f0e1c7369f611c0310efd21fc2d9438b13bc2703af9dda25a";
    url = "https://go.dev/dl/go1.17.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "b8e1ab009c2ff8dea462c7a1263d1f3f38e90ab5262e74c76d70e41a4db320be";
    url = "https://go.dev/dl/go1.17.11.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "c2f583384177423186139dab94c718ee43f36a48681873794f23f7f40a0d758c";
    url = "https://go.dev/dl/go1.17.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "da78bcd5efa24cfa8ca3ccf0d222f7d66b755c4200d404869984ebdcfc7b6aa7";
    url = "https://go.dev/dl/go1.17.11.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "8e43b4c63dda0612df0e1ed3cf8bed566fe8ae88082a46343c40be76a61371e4";
    url = "https://go.dev/dl/go1.17.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "d69a4fe2694f795d8e525c72b497ededc209cb7185f4c3b62d7a98dd6227b3fe";
    url = "https://go.dev/dl/go1.17.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "adefa7412c6798f9cad02d1e8336fc2242f5bade30c5b32781759181e01961b7";
    url = "https://go.dev/dl/go1.17.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "56fb4a344bfe01427398083b3e82018fcde1f168a94e9df9820010b29e558f27";
    url = "https://go.dev/dl/go1.17.11.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "013624fc1964d576f314117f2f3b6a6a8f3d32f0ec8f55fa5962664537a34180";
    url = "https://go.dev/dl/go1.17.11.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "0202a0b2ffaa9bdf1f2480789c2009ba6fde597e1f1c6d4cfb9559bb1964a39c";
    url = "https://go.dev/dl/go1.17.11.linux-s390x.tar.gz";
  };
}
