# Auto-generated by go-scrape - do not edit manually
{
  version = "1.18.9";
  date = "2022-12-06";

  "x86_64-darwin" = {
    sha256 = "82df887243a753b1eac1dfabf9eaf488edb03dc9f8d2b426bc1831d66c19189f";
    url = "https://go.dev/dl/go1.18.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "4b9f0a2a145c5b60934133708c6c54ad1cf91c6451a99461d5382d0f6fbde08d";
    url = "https://go.dev/dl/go1.18.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "109dc93a7af27941ba7fd4938a8d01eb7e19200ec261dcebd90efc0e24ab2d56";
    url = "https://go.dev/dl/go1.18.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "0e224e021e48890a0a75c21da8bac07456af2fbccefc610c56881140aaab18ec";
    url = "https://go.dev/dl/go1.18.9.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "2d78087a1e9627e69bbd8ed517a8fa37a8a505572dce3b16048458894492ef11";
    url = "https://go.dev/dl/go1.18.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "015692d2a48e3496f1da3328cf33337c727c595011883f6fc74f9b5a9c86ffa8";
    url = "https://go.dev/dl/go1.18.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "ae21430756c69c48201c51c3a17ac785613d9616105959a0fb7592e407be8588";
    url = "https://go.dev/dl/go1.18.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e01ef720700e1b198391e88dfca3d3b0e744c88348d0cc5ff560edf42555cb89";
    url = "https://go.dev/dl/go1.18.9.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "17453073e6c3976ff9b0a58cafa82efa424e4190334c7c0a769758369294a3f0";
    url = "https://go.dev/dl/go1.18.9.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "1246e1db3ecdfa9a8699cfa0c0282d1e8c6d2bf8020db2012d3931c034d97750";
    url = "https://go.dev/dl/go1.18.9.linux-s390x.tar.gz";
  };
}
