# Auto-generated by goscrape - do not edit manually
{
  version = "1.18.4";
  date = "2022-07-12";

  "x86_64-darwin" = {
    sha256 = "315e1a2b21a827c68da1b7f492b5dcbe81d8df8a79ebe50922df9588893f87f0";
    url = "https://go.dev/dl/go1.18.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "04eed623d5143ffa44965b618b509e0beccccfd3a4a1bfebc0cdbcf906046769";
    url = "https://go.dev/dl/go1.18.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "e5244fdcd6b6eaf785dbd8c6e02b4804a4d00409e7edecc63cd59fc8f37c34c5";
    url = "https://go.dev/dl/go1.18.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "fb00f8aaffcc80e0a2bd39db1d8e8e21ef0a691c564f7b7601383dd6adad4042";
    url = "https://go.dev/dl/go1.18.4.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "418232d905e18ece6cb13c4884bb1c68963d7d3b4d889671b3e5be8bd4059862";
    url = "https://go.dev/dl/go1.18.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "c9b099b68d93f5c5c8a8844a89f8db07eaa58270e3a1e01804f17f4cf8df02f5";
    url = "https://go.dev/dl/go1.18.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "35014d92b50d97da41dade965df7ebeb9a715da600206aa59ce1b2d05527421f";
    url = "https://go.dev/dl/go1.18.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7dfeab572e49638b0f3d9901457f0622c27b73301c2b99db9f5e9568ff40460c";
    url = "https://go.dev/dl/go1.18.4.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "f80acc4dc054ddc89ccc4869664e331bf16e0ac6e07830e94554162e66f66961";
    url = "https://go.dev/dl/go1.18.4.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "7e932f36e8f347feea2e706dcd32c1a464b1e5767ab2928ae460a37a975fe4a3";
    url = "https://go.dev/dl/go1.18.4.linux-s390x.tar.gz";
  };
}
