# Auto-generated by goscrape - do not edit manually
{
  version = "1.18.1";
  date = "2022-04-12";

  "x86_64-darwin" = {
    sha256 = "3703e9a0db1000f18c0c7b524f3d378aac71219b4715a6a4c5683eb639f41a4d";
    url = "https://go.dev/dl/go1.18.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "6d5641a06edba8cd6d425fb0adad06bad80e2afe0fa91b4aa0e5aed1bc78f58e";
    url = "https://go.dev/dl/go1.18.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b9a9063d4265d8ccc046c9b314194d6eadc47e56d0d637db81e98e68aad45035";
    url = "https://go.dev/dl/go1.18.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "2bc1c138d645e37dbbc63517dd1cf1bf33fc4cb95f442a6384df0418b5134e9f";
    url = "https://go.dev/dl/go1.18.1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "9a8df5dde9058f08ac01ecfaae42534610db398e487138788c01da26a0d41ff9";
    url = "https://go.dev/dl/go1.18.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "b3b815f47ababac13810fc6021eb73d65478e0b2db4b09d348eefad9581a2334";
    url = "https://go.dev/dl/go1.18.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "56a91851c97fb4697077abbca38860f735c32b38993ff79b088dac46e4735633";
    url = "https://go.dev/dl/go1.18.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "9edc01c8e7db64e9ceeffc8258359e027812886ceca3444e83c4eb96ddb068ee";
    url = "https://go.dev/dl/go1.18.1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "33db623d1eecf362fe365107c12efc90eff0b9609e0b3345e258388019cb552a";
    url = "https://go.dev/dl/go1.18.1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "5d9301324148ed4dbfaa0800da43a843ffd65c834ee73fcf087255697c925f74";
    url = "https://go.dev/dl/go1.18.1.linux-s390x.tar.gz";
  };
}
