# Auto-generated by goscrape - do not edit manually
{
  version = "1.18.7";
  date = "2022-10-04";

  "x86_64-darwin" = {
    sha256 = "048cd3dab42d9923ec1d81752859ada96c6f69ac4c644ef00a590a6de0473bca";
    url = "https://go.dev/dl/go1.18.7.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "0b00b5f658ef066941d9b996ab0aa4d2d1072617886e99fb6334e68c54f243db";
    url = "https://go.dev/dl/go1.18.7.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "4e0c5eda1bae50a4257b524f7d28499747cfab0f844c61ec173e935fb7f5269a";
    url = "https://go.dev/dl/go1.18.7.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "8fe9f8861f25c92ee586f1db1d694b4f34de4ca3f9533cdbd3b6431ce5a4db0c";
    url = "https://go.dev/dl/go1.18.7.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "34d14312a599fc8f8956ad93a6f0545e28e31ba4e67845961b818228677d3e9a";
    url = "https://go.dev/dl/go1.18.7.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "6c967efc22152ce3124fc35cdf50fc686870120c5fd2107234d05d450a6105d8";
    url = "https://go.dev/dl/go1.18.7.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "dceea023a9f87dc7c3bf638874e34ff1b42b76e3f1e489510a0c5ffde0cad438";
    url = "https://go.dev/dl/go1.18.7.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "2238c2a4fef887f14ecf37d4c4cd5e1da7c392f4faca3c029a972acf1343bd5e";
    url = "https://go.dev/dl/go1.18.7.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "57aa7293bf085fbf5eb50e162fa1d9314a53f025961992744051f14289d65870";
    url = "https://go.dev/dl/go1.18.7.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "e03938284758d59cd32251760631a4ecfecc24a91a97cdc4e682c804770739fe";
    url = "https://go.dev/dl/go1.18.7.linux-s390x.tar.gz";
  };
}
