# Auto-generated by goscrape - do not edit manually
{
  version = "1.19.4";
  date = "2022-12-06";

  "x86_64-darwin" = {
    sha256 = "44894862d996eec96ef2a39878e4e1fce4d05423fc18bdc1cbba745ebfa41253";
    url = "https://go.dev/dl/go1.19.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "bb3bc5d7655b9637cfe2b5e90055dee93b0ead50e2ffd091df320d1af1ca853f";
    url = "https://go.dev/dl/go1.19.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "dd6c401cc6d0692995ed9b0f37482a724b5b9d9c1119d620862766c60708630f";
    url = "https://go.dev/dl/go1.19.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "84489ebb63f1757b79574d7345c647bd40bc6414cecb868c93e24476c2d2b9b6";
    url = "https://go.dev/dl/go1.19.4.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "e5f0b0551e120bf3d1246cb960ec58032d7ca69e1adcf0fdb91c07da620e0c61";
    url = "https://go.dev/dl/go1.19.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "c9c08f783325c4cf840a94333159cc937f05f75d36a8b307951d5bd959cf2ab8";
    url = "https://go.dev/dl/go1.19.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9df122d6baf6f2275270306b92af3b09d7973fb1259257e284dba33c0db14f1b";
    url = "https://go.dev/dl/go1.19.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7a51dae4f3a52d2dfeaf59367cc0b8a296deddc87e95aa619bf87d24661d2370";
    url = "https://go.dev/dl/go1.19.4.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "fbc6c7d1d169bbdc82223d861d2fadc6add01c126533d3efbba3fdca9b362035";
    url = "https://go.dev/dl/go1.19.4.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "4b8d25acbdca8010c31ea8c5fd4aba93471ff6ada7a8b4fb04b935baee873dc8";
    url = "https://go.dev/dl/go1.19.4.linux-s390x.tar.gz";
  };
}
