# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.12";
  date = "2023-08-01";

  "x86_64-darwin" = {
    sha256 = "f5b10aa4fe63a004df6b6fb9a65a6ac10ff1513a8bc1107d4b5ac74fb568e6cd";
    url = "https://go.dev/dl/go1.19.12.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "dbfd4c6ee0aa362f1fd215073b5af3b9408f6afdba79be433be2822ba12441c8";
    url = "https://go.dev/dl/go1.19.12.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "0097766e0b06718a5ca8cdb0f3cd94a2996a7acd00140a526d2d11c5c3f336a4";
    url = "https://go.dev/dl/go1.19.12.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "7012d1069a20a61a15bf1148f729af972639693f9da862002e6924a5d56ba7f2";
    url = "https://go.dev/dl/go1.19.12.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "06b26c25c09e8d29c230ef59923ed26dcedb3db0c3048c27e84e30606325cf2f";
    url = "https://go.dev/dl/go1.19.12.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "48e4fcfb6abfdaa01aaf1429e43bdd49cea5e4687bd5f5b96df1e193fcfd3e7e";
    url = "https://go.dev/dl/go1.19.12.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "18da7cf1ae5341e6ee120948221aff96df9145ce70f429276514ca7c67c929b1";
    url = "https://go.dev/dl/go1.19.12.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "459ab9af459cf3e5b640365e090d665752a58236e2e7ae53e8ed72f6e90ef40b";
    url = "https://go.dev/dl/go1.19.12.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "bb4fa49ef69c7336fc2ee7500bd580e9a0015016fc6ef7bce700dfad11e6216e";
    url = "https://go.dev/dl/go1.19.12.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "f8da845db8130326fdb454bf85ed1a08458a2f3058e3c3fa068f83db6a047585";
    url = "https://go.dev/dl/go1.19.12.linux-s390x.tar.gz";
  };
}
