# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19";
  date = "2022-08-02";

  "x86_64-darwin" = {
    sha256 = "df6509885f65f0d7a4eaf3dfbe7dda327569787e8a0a31cbf99ae3a6e23e9ea8";
    url = "https://go.dev/dl/go1.19.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "859e0a54b7fcea89d9dd1ec52aab415ac8f169999e5fdfb0f0c15b577c4ead5e";
    url = "https://go.dev/dl/go1.19.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "3989e2336dbb3dcf9197b8c0ef9227cdd1a134789d83095d20ebdc1d88edb9f0";
    url = "https://go.dev/dl/go1.19.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "eca1a8f7b6ff6146efc285eed581096b12b59c1f0488bfe98ed053ab205267ca";
    url = "https://go.dev/dl/go1.19.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "6f721fa3e8f823827b875b73579d8ceadd9053ad1db8eaa2393c084865fb4873";
    url = "https://go.dev/dl/go1.19.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6";
    url = "https://go.dev/dl/go1.19.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "efa97fac9574fc6ef6c9ff3e3758fb85f1439b046573bf434cccb5e012bd00c8";
    url = "https://go.dev/dl/go1.19.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "25197c7d70c6bf2b34d7d7c29a2ff92ba1c393f0fb395218f1147aac2948fb93";
    url = "https://go.dev/dl/go1.19.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "92bf5aa598a01b279d03847c32788a3a7e0a247a029dedb7c759811c2a4241fc";
    url = "https://go.dev/dl/go1.19.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "58723eb8e3c7b9e8f5e97b2d38ace8fd62d9e5423eaa6cdb7ffe5f881cb11875";
    url = "https://go.dev/dl/go1.19.linux-s390x.tar.gz";
  };
}
