# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.1";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "b2828a2b05f0d2169afc74c11ed010775bf7cf0061822b275697b2f470495fb7";
    url = "https://go.dev/dl/go1.19.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "e46aecce83a9289be16ce4ba9b8478a5b89b8aa0230171d5c6adbc0c66640548";
    url = "https://go.dev/dl/go1.19.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "cfaca8c1d5784d2bc21e12d8893cfd2dc885a60db4c1a9a95e4ffc694d0925ce";
    url = "https://go.dev/dl/go1.19.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "db5b8f232e12c655cc6cde6af1adf4d27d842541807802d747c86161e89efa0a";
    url = "https://go.dev/dl/go1.19.1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "9acc57342400c5b0c2da07b5b01b50da239dd4a7fad41a1fb56af8363ef4133f";
    url = "https://go.dev/dl/go1.19.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde";
    url = "https://go.dev/dl/go1.19.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "49960821948b9c6b14041430890eccee58c76b52e2dbaafce971c3c38d43df9f";
    url = "https://go.dev/dl/go1.19.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "efe93f5671621ee84ce5e262e1e21acbc72acefbaba360f21778abd083d4ad16";
    url = "https://go.dev/dl/go1.19.1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "4137984aa353de9c5ec1bd8fb3cd00a0624b75eafa3d4ec13d2f3f48261dba2e";
    url = "https://go.dev/dl/go1.19.1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "ca1005cc80a3dd726536b4c6ea5fef0318939351ff273eff420bd66a377c74eb";
    url = "https://go.dev/dl/go1.19.1.linux-s390x.tar.gz";
  };
}
