# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.2";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "16f8047d7b627699b3773680098fbaf7cc962b7db02b3e02726f78c4db26dfde";
    url = "https://go.dev/dl/go1.19.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "35d819df25197c0be45f36ce849b994bba3b0559b76d4538b910d28f6395c00d";
    url = "https://go.dev/dl/go1.19.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "7831a406447a14d964212d07f68e77cf7fe7fb7286bade6eeb9fbea39b192984";
    url = "https://go.dev/dl/go1.19.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "d74c88430484d14826ec21161e3b9336bd021f502b6594c4dd00e9ec730ee51d";
    url = "https://go.dev/dl/go1.19.2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "ba8c97965e0856c69c9ca2c86f96bec5bb21de43e6533e25494bb211d85cda1b";
    url = "https://go.dev/dl/go1.19.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "5e8c5a74fe6470dd7e055a461acda8bb4050ead8c2df70f227e3ff7d8eb7eeb6";
    url = "https://go.dev/dl/go1.19.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "b62a8d9654436c67c14a0c91e931d50440541f09eb991a987536cb982903126d";
    url = "https://go.dev/dl/go1.19.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "f3ccec7816ecd704ebafd130b08b8ad97c55402a8193a107b63e9de12ab90118";
    url = "https://go.dev/dl/go1.19.2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "37e1d4342f7103aeb9babeabe8c71ef3dba23db28db525071119e94b2aa21d7d";
    url = "https://go.dev/dl/go1.19.2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "51b45dec41295215df17f78e67d1a373b9dda97a5e539bed440974da5ffc97de";
    url = "https://go.dev/dl/go1.19.2.linux-s390x.tar.gz";
  };
}
