# Auto-generated by go-scrape - do not edit manually
{
  version = "1.20rc2";
  date = "2023-01-04";

  "x86_64-darwin" = {
    sha256 = "905db6f9b4e14defa7ce0c7884f53a6d2a511b48a1fdbfa826552170dfe9bbb5";
    url = "https://go.dev/dl/go1.20rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "6da549308070dd9c8a522ae7b80af4cbed32da0e42dc8ed3f02cf2a51af8b276";
    url = "https://go.dev/dl/go1.20rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "0f0830bc59c692cebec5e89d8c94b791919bf3a96a73df24037b97fcd6c7cd97";
    url = "https://go.dev/dl/go1.20rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "1a7aa34dec0e74fcf44473001efd12a99475b0915c635ed487ac5f97ead27ec1";
    url = "https://go.dev/dl/go1.20rc2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "5fdd75afa0ec62127b6f8b00340be63059c05092ddf992bec08c7c19eedd6c55";
    url = "https://go.dev/dl/go1.20rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "9ba01a3be1a682b89f5bfc62f9fba0e7d6990a5b7018f6c7aaa56ad65ed96a0e";
    url = "https://go.dev/dl/go1.20rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "d14c1eeb9f48e8def6f886f4cdec57c0a90ba47bdee1b79a00543aa30386e3a6";
    url = "https://go.dev/dl/go1.20rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "8f356c90d5bbaf8bf4ec00a7168c353dd56ae98d521d3d0726151ca307ba64dd";
    url = "https://go.dev/dl/go1.20rc2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "d19e144952779084dd1e6619f8bdde822708082c7611af398b0d378775372ec4";
    url = "https://go.dev/dl/go1.20rc2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "adcc4bb0d7237b270dd3291844e12cf8d710cd7d8c98f06ad0740376aa5a2de2";
    url = "https://go.dev/dl/go1.20rc2.linux-s390x.tar.gz";
  };
}
