# Auto-generated by go-scrape - do not edit manually
{
  version = "1.20.1";
  date = "2023-02-14";

  "x86_64-darwin" = {
    sha256 = "a300a45e801ab459f3008aae5bb9efbe9a6de9bcd12388f5ca9bbd14f70236de";
    url = "https://go.dev/dl/go1.20.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "f1a8e06c7f1ba1c008313577f3f58132eb166a41ceb95ce6e9af30bc5a3efca4";
    url = "https://go.dev/dl/go1.20.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "57d80349dc4fbf692f8cd85a5971f97841aedafcf211e367e59d3ae812292660";
    url = "https://go.dev/dl/go1.20.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6e124d54d5850a15fdb15754f782986f06af23c5ddb6690849417b9c74f05f98";
    url = "https://go.dev/dl/go1.20.1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "3a7345036ebd92455b653e4b4f6aaf4f7e1f91f4ced33b23d7059159cec5f4d7";
    url = "https://go.dev/dl/go1.20.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02";
    url = "https://go.dev/dl/go1.20.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "5e5e2926733595e6f3c5b5ad1089afac11c1490351855e87849d0e7702b1ec2e";
    url = "https://go.dev/dl/go1.20.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e4edc05558ab3657ba3dddb909209463cee38df9c1996893dd08cde274915003";
    url = "https://go.dev/dl/go1.20.1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "85cfd4b89b48c94030783b6e9e619e35557862358b846064636361421d0b0c52";
    url = "https://go.dev/dl/go1.20.1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "ba3a14381ed4538216dec3ea72b35731750597edd851cece1eb120edf7d60149";
    url = "https://go.dev/dl/go1.20.1.linux-s390x.tar.gz";
  };
}
