# Auto-generated by go-scrape - do not edit manually
{
  version = "1.20.2";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "c93b8ced9517d07e1cd4c362c6e2d5242cb139e29b417a328fbf19aded08764c";
    url = "https://go.dev/dl/go1.20.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "7343c87f19e79c0063532e82e1c4d6f42175a32d99f7a4d15e658e88bf97f885";
    url = "https://go.dev/dl/go1.20.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "14f9be2004e042b3a64d0facb0c020756a9084a5c7333e33b0752b393b6016ea";
    url = "https://go.dev/dl/go1.20.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "b41b67b4f1b56797a7cecf6ee7f47fcf4f93960b2788a3683c07dd009d30b2a4";
    url = "https://go.dev/dl/go1.20.2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "ee240ed33ae57504c41f04c12236aeaa17fbeb6ea9fcd096cd9dc7a89d10d4db";
    url = "https://go.dev/dl/go1.20.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4eaea32f59cde4dc635fbc42161031d13e1c780b87097f4b4234cfce671f1768";
    url = "https://go.dev/dl/go1.20.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "78d632915bb75e9a6356a47a42625fd1a785c83a64a643fedd8f61e31b1b3bef";
    url = "https://go.dev/dl/go1.20.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d79d56bafd6b52b8d8cbe3f8e967caaac5383a23d7a4fa9ac0e89778cd16a076";
    url = "https://go.dev/dl/go1.20.2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "850564ddb760cb703db63bf20182dc4407abd2ff090a95fa66d6634d172fd095";
    url = "https://go.dev/dl/go1.20.2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "8da24c5c4205fe8115f594237e5db7bcb1d23df67bc1fa9a999954b1976896e8";
    url = "https://go.dev/dl/go1.20.2.linux-s390x.tar.gz";
  };
}
