# Auto-generated by go-scrape - do not edit manually
{
  version = "1.20.11";
  date = "2023-11-07";

  "x86_64-darwin" = {
    sha256 = "ced1b5cfd4e8aa7aff5e6a399ed111e5ed2903ee17aaa79ac0c93565fb229776";
    url = "https://go.dev/dl/go1.20.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "9c29373ae278dc02c1d8a08465eea8490bb09bea4ba88fce79b01fe75f84961c";
    url = "https://go.dev/dl/go1.20.11.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "24fd8b234f64e11d49a37f15be346d733a73e0cd082055faf8dad4352754d4a8";
    url = "https://go.dev/dl/go1.20.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "af07dd2b8d8e69c88cad8994e2a82570d64409c447b6e32fa0a7132aca8a8f12";
    url = "https://go.dev/dl/go1.20.11.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "168b11bbc30f5a18671412fb9535ede76b3d98389be01ba37319635eea76de24";
    url = "https://go.dev/dl/go1.20.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "ef79a11aa095a08772d2a69e4f152f897c4e96ee297b0dc20264b7dec2961abe";
    url = "https://go.dev/dl/go1.20.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "7908a49c6ce9d48af9b5ba76ccaa0769da45d8b635259a01065b3739acef4ada";
    url = "https://go.dev/dl/go1.20.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "636a1b4d75c739f4d6373b36d7d278e25523141d4d69eb1bde5526ed56a49635";
    url = "https://go.dev/dl/go1.20.11.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "e04676e1aeafe7c415176f330322d43a4be5ea6deb14aca49905bd1449dc7072";
    url = "https://go.dev/dl/go1.20.11.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "6112113758b7994249db5d33c34723cd2b2f96d0d80ece07c0e59a91e45912db";
    url = "https://go.dev/dl/go1.20.11.linux-s390x.tar.gz";
  };
}
