# Auto-generated by go-scrape - do not edit manually
{
  version = "1.20.13";
  date = "2024-01-09";

  "x86_64-darwin" = {
    sha256 = "713051aa0da66839f5a31a8ec677a7c61717b6fba62bf47eadb25542df3e9ee7";
    url = "https://go.dev/dl/go1.20.13.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "4b7e8d0260b7376c77a0caea7b19dad6e1426c316671a15bc31036f92af2eb12";
    url = "https://go.dev/dl/go1.20.13.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "c10dc00a2693bfce1d9f0622da36bd91380a80f9006b6cbfd7717a071b8366aa";
    url = "https://go.dev/dl/go1.20.13.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "d704e4e44e50c3b54b435bb67a9474880a79f1a7c7af602aecc86cd8154ba4be";
    url = "https://go.dev/dl/go1.20.13.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "4da6f08510a21b829a065d3f99914bfbe1d8b212664cea230485a64e7e6d00d8";
    url = "https://go.dev/dl/go1.20.13.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "9a9d3dcae2b6a638b1f2e9bd4db08ffb39c10e55d9696914002742d90f0047b5";
    url = "https://go.dev/dl/go1.20.13.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "a2d811cef3c4fc77c01195622e637af0c2cf8b3814a95a0920cf2f83b6061d38";
    url = "https://go.dev/dl/go1.20.13.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d4c6c671423ce6eef3f240bf014115b2673ad6a89e12429b5a331b95952c7279";
    url = "https://go.dev/dl/go1.20.13.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "5f632b83323e16f8c6ceb676cd570b3f13f1826e06a81d92985d1301b643a7d3";
    url = "https://go.dev/dl/go1.20.13.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "ae6c8f75df9b15c92374cfeae86e97d2744d4d4cdafcb999fea5b63e20c22651";
    url = "https://go.dev/dl/go1.20.13.linux-s390x.tar.gz";
  };
}
