# Auto-generated by goscrape - do not edit manually
{
  version = "1.20.9";
  date = "2023-10-05";

  "x86_64-darwin" = {
    sha256 = "265b40cc1ff99e24774525af66c65cc60e1576b03e3de21e1ea536ee318ef4fb";
    url = "https://go.dev/dl/go1.20.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "cdbc628807f04d1aadf5f40ba097b1ae1019638258533265ebdd7af205ccd7c5";
    url = "https://go.dev/dl/go1.20.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9eb7af9fb2f12bf186d60fd74167cac791c2b81669af102ea364450b64af7f94";
    url = "https://go.dev/dl/go1.20.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "274100096ac0ad6351ac03bf828b2f02e25c79fa359a4b516f1d4488297eaee9";
    url = "https://go.dev/dl/go1.20.9.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "4cacfaf4a67c27d571c6e94e15e2a3abbcc540f8dfd0ca025f7ea049f8c1ef1b";
    url = "https://go.dev/dl/go1.20.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "8921369701afa749b07232d2c34d514510c32dbfd79c65adb379451b5f0d7216";
    url = "https://go.dev/dl/go1.20.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "da7fca78f85b90b495382cd74b2d0a1c0b6aaa200e7feb27ae7198352b2317fa";
    url = "https://go.dev/dl/go1.20.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "285c10d21172e6a249cef69bff69385b7ddf01ce674b584af73ad2dfa1d467c4";
    url = "https://go.dev/dl/go1.20.9.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "2db0628914522d9d2dbc7070877131dd9d1f8f74387f2f32314b5cfb5e45ff82";
    url = "https://go.dev/dl/go1.20.9.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "8816ff4872c7af6bd975d1c05ea572de49613ddc49f62093a1811535ee715e58";
    url = "https://go.dev/dl/go1.20.9.linux-s390x.tar.gz";
  };
}
