# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21rc2";
  date = "2023-06-21";

  "x86_64-darwin" = {
    sha256 = "bac129d19f83e1267714e1c2e1182cd9f93505e47da3acc9872ca0e69588dd4f";
    url = "https://go.dev/dl/go1.21rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a196b6acfc20fb6836a2e8eb5376c056ac79bcb3c1c6447d580efda20c40dca7";
    url = "https://go.dev/dl/go1.21rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9a93b09dea8e8f66e3edf5a3dca26d4ae5c93671672fafc670ff50f1478957f4";
    url = "https://go.dev/dl/go1.21rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "f1666a4f718e3fae4a50c5117ad8e23a1c330849ddc2bbdaeb9da4dceb92457f";
    url = "https://go.dev/dl/go1.21rc2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "c151931bcd409a3728636f54a97c80d37f004e889cb885b2fe00dfa50a93ccd9";
    url = "https://go.dev/dl/go1.21rc2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "cf330c82e41cf766af5629772600d5ecd3d24faeacdba8ac1f5f33acc6590175";
    url = "https://go.dev/dl/go1.21rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "8fe90332727c606019e80a7368e23f5e65ad59520e45ee4010692f15572e45c6";
    url = "https://go.dev/dl/go1.21rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "30a6518ca5f816c0fef5b2cc16b960e999b98b16f7d69f995f74236cc00aa292";
    url = "https://go.dev/dl/go1.21rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "0f82199e49978db858a8ed2c6b8d842b9674fd577c4ab91cc4b6b11672375993";
    url = "https://go.dev/dl/go1.21rc2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "6fadbd46312b60f9c1651838c5722a71fe85c379e8a78fcb08b00767485c09fe";
    url = "https://go.dev/dl/go1.21rc2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "8c3a2674cf57c304ed1a8f4e0a6184ad85fd5760a04dea608fdcaca7ad863027";
    url = "https://go.dev/dl/go1.21rc2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "33ea0c09d1f10f034d9e4fbef4eaceb785f3433ba631eaacb01a0af40773b673";
    url = "https://go.dev/dl/go1.21rc2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "3fd1640c1f4c50dff412643cd61577d53c8241f1f2789605b1ff1048d2b36f95";
    url = "https://go.dev/dl/go1.21rc2.linux-s390x.tar.gz";
  };
}
