# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21.1";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "809f5b0ef4f7dcdd5f51e9630a5b2e5a1006f22a047126d61560cdc365678a19";
    url = "https://go.dev/dl/go1.21.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "ffd40391a1e995855488b008ad9326ff8c2e81803a6e80894401003bae47fcf1";
    url = "https://go.dev/dl/go1.21.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9919a9a4dc82371aba3da5b7c830bcb6249fc1502cd26d959eb340a60e41ee01";
    url = "https://go.dev/dl/go1.21.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "2571f10f6047e04d87c1f5986a05e5e8f7b511faf98803ef12b66d563845d2a1";
    url = "https://go.dev/dl/go1.21.1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "4946118e72deccf194a9bfcfedbafe52e45b5fe9441fd3acfced760b27a20f9a";
    url = "https://go.dev/dl/go1.21.1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "b93850666cdadbd696a986cf7b03111fe99db8c34a9aaa113d7c96d0081e1901";
    url = "https://go.dev/dl/go1.21.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "b3075ae1ce5dab85f89bc7905d1632de23ca196bd8336afd93fa97434cfa55ae";
    url = "https://go.dev/dl/go1.21.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "7da1a3936a928fd0b2602ed4f3ef535b8cd1990f1503b8d3e1acc0fa0759c967";
    url = "https://go.dev/dl/go1.21.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "f3716a43f59ae69999841d6007b42c9e286e8d8ce470656fb3e70d7be2d7ca85";
    url = "https://go.dev/dl/go1.21.1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "2273cc4ed398d8b341aee01fd62f3845045b2f439b84b28720a7f3d3552f5d41";
    url = "https://go.dev/dl/go1.21.1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "eddf018206f8a5589bda75252b72716d26611efebabdca5d0083ec15e9e41ab7";
    url = "https://go.dev/dl/go1.21.1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "fac64ed26e003f49f1d77f6d2c4cf951422aecbce12232d9ec1bf4585fc44ee1";
    url = "https://go.dev/dl/go1.21.1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "a83b3e8eb4dbf76294e773055eb51397510ff4d612a247bad9903560267bba6d";
    url = "https://go.dev/dl/go1.21.1.linux-s390x.tar.gz";
  };
}
