# Auto-generated by goscrape - do not edit manually
{
  version = "1.21.13";
  date = "2024-08-06";

  "x86_64-darwin" = {
    sha256 = "796fd05e8741f6776c505eb201922864f2e32991679b639d9fcb524dbe300c0d";
    url = "https://go.dev/dl/go1.21.13.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "c04ee7bdc0e65cf17133994c40ee9bdfa1b1dc9587b3baedaea39affdb8e5b49";
    url = "https://go.dev/dl/go1.21.13.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "7d9b46dc3b6aeac3b624c2b17f27e1f6307b8b6535fe1b8c05e7366db5bdcc9b";
    url = "https://go.dev/dl/go1.21.13.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "56137d4a487b8fdd013c57b025079a4ec20bd19dd809035cc648887188523c64";
    url = "https://go.dev/dl/go1.21.13.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "c90933011c21b06547be42f32d4f9bad2e04cf8726d0f013fde6dd512c21ae49";
    url = "https://go.dev/dl/go1.21.13.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "21652cea6ef24f6a87f2911af338dbc6ecac5b05fc2f8235137cf486244fcb42";
    url = "https://go.dev/dl/go1.21.13.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "502fc16d5910562461e6a6631fb6377de2322aad7304bf2bcd23500ba9dab4a7";
    url = "https://go.dev/dl/go1.21.13.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "2ca2d70dc9c84feef959eb31f2a5aac33eefd8c97fe48f1548886d737bffabd4";
    url = "https://go.dev/dl/go1.21.13.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7f360ac69fc7f53cbe849680a7cb508524b9f225c532d9d888a0583c7903750b";
    url = "https://go.dev/dl/go1.21.13.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "4139f812876a681215bbd0be5fe4f425bc857ae6914b49dd8ae96c52735a9a43";
    url = "https://go.dev/dl/go1.21.13.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "d204271ad29f74184ac04fa62407d70de4003070441bc6146d217035320c47ed";
    url = "https://go.dev/dl/go1.21.13.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "3aa7e83ab4aeba6d6ef98d3df965f176ccb148fcefc6eacfd80831ada842fa9a";
    url = "https://go.dev/dl/go1.21.13.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "f0a40e4596f919422cb8c6695565c67161835343e09d6b0ddc9ba54f9ce1916b";
    url = "https://go.dev/dl/go1.21.13.linux-s390x.tar.gz";
  };
}
