# Auto-generated by go-scrape - do not edit manually
{
  version = "1.21.7";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "4b9f4e02e465ba0f3a4c138ecb1c148135cf77c0efb5474461746b7c123b3484";
    url = "https://go.dev/dl/go1.21.7.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "26e23304810f8e14ba443664326f53d7eafd83faa8097a5c2c4d55b61f431280";
    url = "https://go.dev/dl/go1.21.7.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "2a0586f6bf97d51b25a2fef673cd3463b7b280261b0d30a85fb854398cfbe25a";
    url = "https://go.dev/dl/go1.21.7.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "65cedc79920786bda0db4dde5a468cd18ca49c84dd450d765aef8942874d1c9f";
    url = "https://go.dev/dl/go1.21.7.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "90a127bd420454b3cd94ddcda6a2c3f68e3275006b3b911da1f9c01570d033a3";
    url = "https://go.dev/dl/go1.21.7.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "ecd838b01c28b62d23e0fc806f980de676a6754be53e6bf2f1fe966c12dede15";
    url = "https://go.dev/dl/go1.21.7.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "13b76a9b2a26823e53062fa841b07087d48ae2ef2936445dc34c4ae03293702c";
    url = "https://go.dev/dl/go1.21.7.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "a9bc1ccedbfde059f25b3a2ad81ae4cdf21192ae207dfd3ccbbfe99c3749e233";
    url = "https://go.dev/dl/go1.21.7.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d86d2da4cad1c0ff5fc13677b0b77f26ca8adca48170c140f06b882e83b6e8df";
    url = "https://go.dev/dl/go1.21.7.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "bbb50af652c860b4177b8f1b31500954e5c8ffb3038ecf4a3e1ae22a0d70b9b1";
    url = "https://go.dev/dl/go1.21.7.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "48a99ecce9b1e632870c29420088f61cf17a6f0c5bdb3cc821ff5c00e14b1a8a";
    url = "https://go.dev/dl/go1.21.7.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "dc1c3cb6eadc57130136b3c1dec5ca8af7783c36e0392ebf59073c61e60b24f2";
    url = "https://go.dev/dl/go1.21.7.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "d655022bd82927fbfeb36eb49a3e2af0f3cc18d18882c0f671923da0ec257948";
    url = "https://go.dev/dl/go1.21.7.linux-s390x.tar.gz";
  };
}
