# Auto-generated by go-scrape - do not edit manually
{
  version = "1.22.11";
  date = "2025-01-16";

  "x86_64-darwin" = {
    sha256 = "c6d130066d509ccca1164d84514905b1e8dc5f5f4c25c24113f1b65ad87cd020";
    url = "https://go.dev/dl/go1.22.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "3980b1d2be042a164989f2fd24f0bb306a2397d581a29c7426885578b369db5d";
    url = "https://go.dev/dl/go1.22.11.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "ab10063b2620de387b74bc2eeadc2642a960b1c97c3fc8193447977954262241";
    url = "https://go.dev/dl/go1.22.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "7910de647cab36eea010da64c07c31484a2c94e0447a0d81f339415de0def2a4";
    url = "https://go.dev/dl/go1.22.11.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "9b5043744bd56d36d66ed193776952dd5ebdef31302d6b209e9e87f3b3936e85";
    url = "https://go.dev/dl/go1.22.11.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "b40ee463437e8c8f2d6c9685a0e166eaecb36615afa362eaa58459d3369f3baf";
    url = "https://go.dev/dl/go1.22.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "0fc88d966d33896384fbde56e9a8d80a305dc17a9f48f1832e061724b1719991";
    url = "https://go.dev/dl/go1.22.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9ebfcab26801fa4cf0627c6439db7a4da4d3c6766142a3dd83508240e4f21031";
    url = "https://go.dev/dl/go1.22.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ac3ba3e0433d96b041f683e9bbb791ca39e159b3d4bb948de4ab3a2c1af1b257";
    url = "https://go.dev/dl/go1.22.11.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "83ced97550e9afc82a48d98534a2457c9662a9071a35439558a70167c8cd513b";
    url = "https://go.dev/dl/go1.22.11.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "963a0ec973640b23ee8bb7a462cc415276fd8436111a03df8c34eb3b1ae29f12";
    url = "https://go.dev/dl/go1.22.11.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "150fd528397622764285f807d3343c36d052ed8cfc390a95e6336738c53f68f4";
    url = "https://go.dev/dl/go1.22.11.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "1a235afe650dee989fb37fef6aa520f35e4cd557c31453f3e82b553da3a90669";
    url = "https://go.dev/dl/go1.22.11.linux-s390x.tar.gz";
  };
}
