# Auto-generated by goscrape - do not edit manually
{
  version = "1.22.12";
  date = "2025-02-04";

  "x86_64-darwin" = {
    sha256 = "e7bbe07e96f0bd3df04225090fe1e7852ed33af37c43a23e16edbbb3b90a5b7c";
    url = "https://go.dev/dl/go1.22.12.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "416c35218edb9d20990b5d8fc87be655d8b39926f15524ea35c66ee70273050d";
    url = "https://go.dev/dl/go1.22.12.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "85b00f8646e84be6ce51c753d22b68a5f4d5bbfc6a82c8ca9e7489c0c5a619d8";
    url = "https://go.dev/dl/go1.22.12.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "a8c77e76859db3e6f3322cbe11deea5faf779e374f45df7554d2cb484ffa492a";
    url = "https://go.dev/dl/go1.22.12.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "f56d3b2d26acd9e720f8be503d92bb7bb5d921462ff7c92463d0fa550507ed93";
    url = "https://go.dev/dl/go1.22.12.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "40d4c297bc2e964e9c96fe79bb323dce79b77b8b103fc7cc52e0a87c7849890f";
    url = "https://go.dev/dl/go1.22.12.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4fa4f869b0f7fc6bb1eb2660e74657fbf04cdd290b5aef905585c86051b34d43";
    url = "https://go.dev/dl/go1.22.12.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "fd017e647ec28525e86ae8203236e0653242722a7436929b1f775744e26278e7";
    url = "https://go.dev/dl/go1.22.12.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "bcd678461bb74cda217fb5aa3cc914b2021be6d828f0c6fb4e3a36c3d7312acb";
    url = "https://go.dev/dl/go1.22.12.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "ef1644676782354369210ed6cd839ff872de886c38f287d29ac69377928edec1";
    url = "https://go.dev/dl/go1.22.12.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "9573d30003b0796717a99d9e2e96c48fddd4fc0f29d840f212c503b03d7de112";
    url = "https://go.dev/dl/go1.22.12.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "f03a084aabc812fdc15b29acd5e1ee18e13b3c80be22aec43990119afcaf4947";
    url = "https://go.dev/dl/go1.22.12.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "e1b20935cc790fdc4c48c0e3e6dd11be57ac09e4eb302ba2cdf146276468b346";
    url = "https://go.dev/dl/go1.22.12.linux-s390x.tar.gz";
  };
}
