# Auto-generated by go-scrape - do not edit manually
{
  version = "1.22.0";
  date = "2024-02-06";

  "x86_64-darwin" = {
    sha256 = "ebca81df938d2d1047cc992be6c6c759543cf309d401b86af38a6aed3d4090f4";
    url = "https://go.dev/dl/go1.22.0.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "bf8e388b09134164717cd52d3285a4ab3b68691b80515212da0e9f56f518fb1e";
    url = "https://go.dev/dl/go1.22.0.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b8065da37783e8b9e7086365a54d74537e832c92311b61101a66989ab2458d8e";
    url = "https://go.dev/dl/go1.22.0.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "50f421c7f217083ac94aab1e09400cb9c2fea7d337679ec11f1638a11460da30";
    url = "https://go.dev/dl/go1.22.0.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "e23385e5c640787fa02cd58f2301ea09e162c4d99f8ca9fa6d52766f428a933d";
    url = "https://go.dev/dl/go1.22.0.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "1e209c4abde069067ac9afb341c8003db6a210f8173c77777f02d3a524313da3";
    url = "https://go.dev/dl/go1.22.0.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "f6c8a87aa03b92c4b0bf3d558e28ea03006eb29db78917daec5cfb6ec1046265";
    url = "https://go.dev/dl/go1.22.0.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "6a63fef0e050146f275bf02a0896badfe77c11b6f05499bb647e7bd613a45a10";
    url = "https://go.dev/dl/go1.22.0.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "0525f92f79df7ed5877147bce7b955f159f3962711b69faac66bc7121d36dcc4";
    url = "https://go.dev/dl/go1.22.0.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "b4b1d425cc113608452a32768469b6e34e538fd072bde9f508a75c8dbbdb843f";
    url = "https://go.dev/dl/go1.22.0.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "0e57f421df9449066f00155ce98a5be93744b3d81b00ee4c2c9b511be2a31d93";
    url = "https://go.dev/dl/go1.22.0.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "afe9cedcdbd6fdff27c57efd30aa5ce0f666f471fed5fa96cd4fb38d6b577086";
    url = "https://go.dev/dl/go1.22.0.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "2e546a3583ba7bd3988f8f476245698f6a93dfa9fe206a8ca8f85c1ceecb2446";
    url = "https://go.dev/dl/go1.22.0.linux-s390x.tar.gz";
  };
}
