# Auto-generated by goscrape - do not edit manually
{
  version = "1.22.4";
  date = "2024-06-04";

  "x86_64-darwin" = {
    sha256 = "c95967f50aa4ace34af0c236cbdb49a9a3e80ee2ad09d85775cb4462a5c19ed3";
    url = "https://go.dev/dl/go1.22.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "242b78dc4c8f3d5435d28a0d2cec9b4c1aa999b601fb8aa59fb4e5a1364bf827";
    url = "https://go.dev/dl/go1.22.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "7c54884bb9f274884651d41e61d1bc12738863ad1497e97ea19ad0e9aa6bf7b5";
    url = "https://go.dev/dl/go1.22.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "88d44500e1701dd35797619774d6dd51bf60f45a8338b0a82ddc018e4e63fb78";
    url = "https://go.dev/dl/go1.22.4.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "726dc093cf020277be45debf03c3b02b43c2efb3e2a5d4fba8f52579d65327dc";
    url = "https://go.dev/dl/go1.22.4.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "47a2a8d249a91eb8605c33bceec63aedda0441a43eac47b4721e3975ff916cec";
    url = "https://go.dev/dl/go1.22.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "ba79d4526102575196273416239cca418a651e049c2b099f3159db85e7bade7d";
    url = "https://go.dev/dl/go1.22.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "a8e177c354d2e4a1b61020aca3562e27ea3e8f8247eca3170e3fa1e0c2f9e771";
    url = "https://go.dev/dl/go1.22.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e2b143fbacbc9cbd448e9ef41ac3981f0488ce849af1cf37e2341d09670661de";
    url = "https://go.dev/dl/go1.22.4.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "e2ff9436e4b34bf6926b06d97916e26d67a909a2effec17967245900f0816f1d";
    url = "https://go.dev/dl/go1.22.4.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "a3e5834657ef92523f570f798fed42f1f87bc18222a16815ec76b84169649ec4";
    url = "https://go.dev/dl/go1.22.4.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "56a827ff7dc6245bcd7a1e9288dffaa1d8b0fd7468562264c1523daf3b4f1b4a";
    url = "https://go.dev/dl/go1.22.4.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "7590c3e278e2dc6040aae0a39da3ca1eb2e3921673a7304cc34d588c45889eec";
    url = "https://go.dev/dl/go1.22.4.linux-s390x.tar.gz";
  };
}
