# Auto-generated by goscrape - do not edit manually
{
  version = "1.22.2";
  date = "2024-04-03";

  "x86_64-darwin" = {
    sha256 = "33e7f63077b1c5bce4f1ecadd4d990cf229667c40bfb00686990c950911b7ab7";
    url = "https://go.dev/dl/go1.22.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "660298be38648723e783ba0398e90431de1cb288c637880cdb124f39bd977f0d";
    url = "https://go.dev/dl/go1.22.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "efc7162b0cad2f918ac566a923d4701feb29dc9c0ab625157d49b1cbcbba39da";
    url = "https://go.dev/dl/go1.22.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "d753428296e6709527e291fd204700a587ffef2c0a472b21aebea11618245929";
    url = "https://go.dev/dl/go1.22.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "c4d7c44d522188d7fbe0f09bd502c009d0eeba3f76d8001c5a3ea21f1834e921";
    url = "https://go.dev/dl/go1.22.2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "586d9eb7fe0489ab297ad80dd06414997df487c5cf536c490ffeaa8d8f1807a7";
    url = "https://go.dev/dl/go1.22.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17";
    url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "36e720b2d564980c162a48c7e97da2e407dfcc4239e1e58d98082dfa2486a0c1";
    url = "https://go.dev/dl/go1.22.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "9243dfafde06e1efe24d59df6701818e6786b4adfdf1191098050d6d023c5369";
    url = "https://go.dev/dl/go1.22.2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "682fa3a47b8bb07eff7300602199c8732aa4c81c4dcab2e7b52c6d61bdc6d631";
    url = "https://go.dev/dl/go1.22.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "251a8886c5113be6490bdbb955ddee98763b49c9b1bf4c8364c02d3b482dab00";
    url = "https://go.dev/dl/go1.22.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "2e0447ed3294729232e012898a43145defaf2ffbfece2e934edda8bd2775c400";
    url = "https://go.dev/dl/go1.22.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "2b39019481c28c560d65e9811a478ae10e3ef765e0f59af362031d386a71bfef";
    url = "https://go.dev/dl/go1.22.2.linux-s390x.tar.gz";
  };
}
