# Auto-generated by go-scrape - do not edit manually
{
  version = "1.22rc1";
  date = "2025-12-12";

  "x86_64-darwin" = {
    sha256 = "e826132e72eb1f3f6a523309bfabf7cb4b2d72e26e369abed4b30bda2ed61246";
    url = "https://go.dev/dl/go1.22rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "799699272100d451f46ce271b65421c3472e6ce99375a8885e24223dcddc0235";
    url = "https://go.dev/dl/go1.22rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "1f163bdd8ad40eba68f90da048bd3962a19b63d660ec557ce3aa70e22216bef0";
    url = "https://go.dev/dl/go1.22rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "f884e50062bcffdb8b0a09c91be5e18bd3f6219bae24e88cea5b5737d005fc73";
    url = "https://go.dev/dl/go1.22rc1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "61fceff9fd9d7e04a14770570ade80ba905068918cc07bd3c324c48ff31b53c1";
    url = "https://go.dev/dl/go1.22rc1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "85ea68ef2fbd0d28179a8852401f498cb02dd7a2d688e71e54ee6180a790d105";
    url = "https://go.dev/dl/go1.22rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "fbe9d0585b9322d44008f6baf78b391b22f64294338c6ce2b9eb6040d6373c52";
    url = "https://go.dev/dl/go1.22rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "d777d6bc3241bcd470603c3af896d1c60ed1d8cc718cf92d0a5d9035b149a827";
    url = "https://go.dev/dl/go1.22rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "78e86eb1f449d88692829f1d794cd9f696b66c4f5e25f4ceb4ddd3ad7bee3683";
    url = "https://go.dev/dl/go1.22rc1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "36041011ce28451c8d6fa303abba678c8d145d42973294306dc183edcdcab9d2";
    url = "https://go.dev/dl/go1.22rc1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "051d68e1fb9c804db0c5ecf856493ccf7611f6b05424bfe6d6a03ce03e5dbb24";
    url = "https://go.dev/dl/go1.22rc1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "f7c9d98683f52004bc9942a6ac4ae628f89070446f24ad5451404ad7ee27682a";
    url = "https://go.dev/dl/go1.22rc1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "29e6b990a47cb3942e72208e91e370b3620119d0a7dcb2a58de57bde7716fc2b";
    url = "https://go.dev/dl/go1.22rc1.linux-s390x.tar.gz";
  };
}
