# Auto-generated by go-scrape - do not edit manually
{
  version = "1.23.9";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "50200cba5173100a6e880098cf3b2db4063394beaf7374e9766b6c19bb18012d";
    url = "https://go.dev/dl/go1.23.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "2bf624b6399e41248255858b2d61abae2703eecafad39808449951f3f1ab3766";
    url = "https://go.dev/dl/go1.23.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "2ec88ecebd609768d0b2a19f5ae6df333f60e7ae1b06dab3562d21ac41d2f837";
    url = "https://go.dev/dl/go1.23.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "d939dd297a4ced4999147be03c22e3b667cee5479078373ed7bf7ccd1a777c83";
    url = "https://go.dev/dl/go1.23.9.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "a2d01870891f9bd531e3ac4b9a1a0768fb9c3aeab69986f79d965ddb618b5c1a";
    url = "https://go.dev/dl/go1.23.9.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "9145095dead1209fd4ce554cd5a18ac42861b168efcd849faf85b8639782f0f9";
    url = "https://go.dev/dl/go1.23.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "de03e45d7a076c06baaa9618d42b3b6a0561125b87f6041c6397680a71e5bb26";
    url = "https://go.dev/dl/go1.23.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "3dc4dd64bdb0275e3ec65a55ecfc2597009c7c46a1b256eefab2f2172a53a602";
    url = "https://go.dev/dl/go1.23.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ade33880caacb8919b48767e0957e9880f2cdf634e137402a6f22552504136dd";
    url = "https://go.dev/dl/go1.23.9.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "50b08d8b3a7fb027608db01ff63152001b33710b2ec9acad995adbb63bd8a02a";
    url = "https://go.dev/dl/go1.23.9.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "4e23059029552ece0f37e626208caacfe088b7178409797be75280f6e850e98b";
    url = "https://go.dev/dl/go1.23.9.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "e9027dfeb00a482271c2d068d2d0fd5d75aa5b49fa86542d8409cac3cd0c977f";
    url = "https://go.dev/dl/go1.23.9.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "25e7cb524f97f52369b6162e2440c87be128ed8e9ad9bd076e0706bba4f73817";
    url = "https://go.dev/dl/go1.23.9.linux-s390x.tar.gz";
  };
}
