# Auto-generated by go-scrape - do not edit manually
{
  version = "1.23.4";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "6700067389a53a1607d30aa8d6e01d198230397029faa0b109e89bc871ab5a0e";
    url = "https://go.dev/dl/go1.23.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "87d2bb0ad4fe24d2a0685a55df321e0efe4296419a9b3de03369dbe60b8acd3a";
    url = "https://go.dev/dl/go1.23.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "8df26b1e71234756c1f0e82cfffba3f427c5a91a251844ada2c7694a6986c546";
    url = "https://go.dev/dl/go1.23.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "7de078d94d2af50ee9506ef7df85e4d12d4018b23e0b2cbcbc61d686f549b41a";
    url = "https://go.dev/dl/go1.23.4.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "986a20e7c94431f03b44b3c415abc698c7b4edc2ae8431f7ecae1c2429d4cfa2";
    url = "https://go.dev/dl/go1.23.4.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "4a4a0e7587ef8c8a326439b957027f2791795e2d29d4ae3885b4091a48f843bc";
    url = "https://go.dev/dl/go1.23.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "6924efde5de86fe277676e929dc9917d466efa02fb934197bc2eba35d5680971";
    url = "https://go.dev/dl/go1.23.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "16e5017863a7f6071363782b1b8042eb12c6ca4f4cd71528b2123f0a1275b13e";
    url = "https://go.dev/dl/go1.23.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "1f1dda0dc7ce0b2295f57258ec5ef0803fd31b9ed0aa20e2e9222334e5755de1";
    url = "https://go.dev/dl/go1.23.4.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "4f469179a335a1a7bb9f991ad0c567f3d3eeb9b412ecd192206ab5c3e1a52b5a";
    url = "https://go.dev/dl/go1.23.4.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "65a303ef51e48ff77e004a6a5b4db6ce59495cd59c6af51b54bf4f786c01a1b9";
    url = "https://go.dev/dl/go1.23.4.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "7c40e9e0d722cef14ede765159ba297f4c6e3093bb106f10fbccf8564780049a";
    url = "https://go.dev/dl/go1.23.4.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "74aab82bf4eca7c26c830a5b0e2a31d193a4d5ba47045526b92473cc7188d7d7";
    url = "https://go.dev/dl/go1.23.4.linux-s390x.tar.gz";
  };
}
