# Auto-generated by goscrape - do not edit manually
{
  version = "1.23.2";
  date = "2024-10-01";

  "x86_64-darwin" = {
    sha256 = "445c0ef19d8692283f4c3a92052cc0568f5a048f4e546105f58e991d4aea54f5";
    url = "https://go.dev/dl/go1.23.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "d87031194fe3e01abdcaf3c7302148ade97a7add6eac3fec26765bcb3207b80f";
    url = "https://go.dev/dl/go1.23.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "e4d9a1319dfdaa827407855e406c43e85c878a1f93f4f3984c85dce969c8bf70";
    url = "https://go.dev/dl/go1.23.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "025d77f1780906142023a364c31a572afd7d56d3a3be1e4e562e367ca88d3267";
    url = "https://go.dev/dl/go1.23.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "f45af3e1434175ff85620a74c07fb41d6844655f1f2cd2389c5fca6de000f58c";
    url = "https://go.dev/dl/go1.23.2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "cb1ed4410f68d8be1156cee0a74fcfbdcd9bca377c83db3a9e1b07eebc6d71ef";
    url = "https://go.dev/dl/go1.23.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "542d3c1705f1c6a1c5a80d5dc62e2e45171af291e755d591c5e6531ef63b454e";
    url = "https://go.dev/dl/go1.23.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "f626cdd92fc21a88b31c1251f419c17782933a42903db87a174ce74eeecc66a9";
    url = "https://go.dev/dl/go1.23.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e3286bdde186077e65e961cbe18874d42a461e5b9c472c26572b8d4a98d15c40";
    url = "https://go.dev/dl/go1.23.2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "2293c5c3ffc595418308b4059ce214b99f0383cba83232e47a1a8c3b710c24e8";
    url = "https://go.dev/dl/go1.23.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "c164ce7d894b10fd861d7d7b96f1dbea3f993663d9f0c30bc4f8ae3915db8b0c";
    url = "https://go.dev/dl/go1.23.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "ea8ab49c5c04c9f94a3f4894d1b030fbce8d10413905fa399f6c39c0a44d5556";
    url = "https://go.dev/dl/go1.23.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "de1f94d7dd3548ba3036de1ea97eb8243881c22a88fcc04cc08c704ded769e02";
    url = "https://go.dev/dl/go1.23.2.linux-s390x.tar.gz";
  };
}
