# Auto-generated by go-scrape - do not edit manually
{
  version = "1.23.7";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "3a3d6745286297cd011d2ab071998a85fe82714bf178dc3cd6ecd3d043a59270";
    url = "https://go.dev/dl/go1.23.7.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a08a77374a4a8ab25568cddd9dad5ba7bb6d21e04c650dc2af3def6c9115ebba";
    url = "https://go.dev/dl/go1.23.7.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "4bc9c3583236b13a9f1ec22c133fe4436714d56ebc0ee96733d4f6f0eb3c7ae1";
    url = "https://go.dev/dl/go1.23.7.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "c0e7a5ff1875eb79d7c2acfa1616718ad892c0b2637d56594fdc3332e313efd4";
    url = "https://go.dev/dl/go1.23.7.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "2b51c940898fad6708609495b9a27b5869cf5195381fc4a31a013006aa4eb156";
    url = "https://go.dev/dl/go1.23.7.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "9115f7d751efe5b17b63a7630d24cd0a2479976465eecb277b5deec8aa0f4143";
    url = "https://go.dev/dl/go1.23.7.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4741525e69841f2e22f9992af25df0c1112b07501f61f741c12c6389fcb119f3";
    url = "https://go.dev/dl/go1.23.7.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "597acbd0505250d4d98c4c83adf201562a8c812cbcd7b341689a07087a87a541";
    url = "https://go.dev/dl/go1.23.7.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "c9e9ecd6a8cf1429f1c65d81115c450258258ac65833d95a82d5f4e5ad7d2d7a";
    url = "https://go.dev/dl/go1.23.7.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "b9fb0ae7116cee77e88e1e2f54cca44343a71168b944768c48188cd1957fb3f8";
    url = "https://go.dev/dl/go1.23.7.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "3ffc310bfd11fd0bcc713a764a0f7252c4d52d03f12abebfaebaaae77e027028";
    url = "https://go.dev/dl/go1.23.7.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "6474c707a09633ebd3117eb9127de467fbc482932164f1d1b1084e3be40c36f7";
    url = "https://go.dev/dl/go1.23.7.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "af1d4c5d01e32c2cf6e3cc00e44cb240e1a6cef539b28a64389b2b9ca284ac6c";
    url = "https://go.dev/dl/go1.23.7.linux-s390x.tar.gz";
  };
}
