# Auto-generated by go-scrape - do not edit manually
{
  version = "1.23rc1";
  date = "2024-06-21";

  "x86_64-darwin" = {
    sha256 = "4006228f4a28ac70a6ddaa4ac083dccb1d0e510d642a7c599a21ba4f00499ba5";
    url = "https://go.dev/dl/go1.23rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "afd500bd5a1cc41f424aadfe9f09fb7db2a7eaa9065de3875a9b9a75f5611042";
    url = "https://go.dev/dl/go1.23rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "932460e728b50429a825fca9d983351007afaca459eed4a9ab0bbaa3b07aaf2e";
    url = "https://go.dev/dl/go1.23rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "0ddf396214e97a4417be143929c2cb419076f9d7641f03df8f89c8af51698621";
    url = "https://go.dev/dl/go1.23rc1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "92b63e4f62826677a3877a425625dd3a4ae1806bc33c0bd5064d0da96dd7a616";
    url = "https://go.dev/dl/go1.23rc1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "770f682ad2b7b2305915fbf2918acf67ef5a06654cdcac1f859d195b2e7d9861";
    url = "https://go.dev/dl/go1.23rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "0d8543abb8f4d566b3c8ef25b38e578ae2cb357bba2db8f0c0481531d8e1c939";
    url = "https://go.dev/dl/go1.23rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "1208d96e6535ccf32ceee2f876dbbec588bf0921861d2224b809cbfe797f2319";
    url = "https://go.dev/dl/go1.23rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "6aaf0968817cadb372aff885cfd2c5b6c3a121f1cb890c0ad54106cbc5317c8a";
    url = "https://go.dev/dl/go1.23rc1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "abc4603171988f95f1872385946b334e92191ce79e3831f9447f350ca6216928";
    url = "https://go.dev/dl/go1.23rc1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "bbb5f0f6895f25173e436ef2549342db050b6c2d3e094a0db306a4fa27c231bf";
    url = "https://go.dev/dl/go1.23rc1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "8cb299c73325de4bf59a9788e9851afdead7ab45d8da1eec8bb5f774c4014f8e";
    url = "https://go.dev/dl/go1.23rc1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "7d35beef23925061b0a219a8338a1525f74647fc22aeecab97b983a9d6114054";
    url = "https://go.dev/dl/go1.23rc1.linux-s390x.tar.gz";
  };
}
