# Auto-generated by go-scrape - do not edit manually
{
  version = "1.23.3";
  date = "2024-11-06";

  "x86_64-darwin" = {
    sha256 = "c7e024d5c0bc81845070f23598caf02f05b8ae88fd4ad2cd3e236ddbea833ad2";
    url = "https://go.dev/dl/go1.23.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "31e119fe9bde6e105407a32558d5b5fa6ca11e2bd17f8b7b2f8a06aba16a0632";
    url = "https://go.dev/dl/go1.23.3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "69479fa016ec5b4605885643ce0c2dd5c583e02353978feb6de38c961863b9cc";
    url = "https://go.dev/dl/go1.23.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "bf1de22a900646ef4f79480ed88337856d47089cc610f87e6fef46f6b8db0e1f";
    url = "https://go.dev/dl/go1.23.3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "24154b4018a45540aefeb6b5b9ffdcc8d9a8cdb78cd7fec262787b89fed19997";
    url = "https://go.dev/dl/go1.23.3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "3d7b00191a43c50d28e0903a0c576104bc7e171a8670de419d41111c08dfa299";
    url = "https://go.dev/dl/go1.23.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "a0afb9744c00648bafb1b90b4aba5bdb86f424f02f9275399ce0c20b93a2c3a8";
    url = "https://go.dev/dl/go1.23.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "1f7cbd7f668ea32a107ecd41b6488aaee1f5d77a66efd885b175494439d4e1ce";
    url = "https://go.dev/dl/go1.23.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "5f0332754beffc65af65a7b2da76e9dd997567d0d81b6f4f71d3588dc7b4cb00";
    url = "https://go.dev/dl/go1.23.3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "1d0161a8946c7d99f717bad23631738408511f9f87e78d852224a023d8882ad8";
    url = "https://go.dev/dl/go1.23.3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "e3b926c81e8099d3cee6e6e270b85b39c3bd44263f8d3df29aacb4d7e00507c8";
    url = "https://go.dev/dl/go1.23.3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "324e03b6f59be841dfbaeabc466224b0f0905f5ad3a225b7c0703090e6c4b1a5";
    url = "https://go.dev/dl/go1.23.3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "6bd72fcef72b046b6282c2d1f2c38f31600e4fe9361fcd8341500c754fb09c38";
    url = "https://go.dev/dl/go1.23.3.linux-s390x.tar.gz";
  };
}
