# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.4";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "69bef555e114b4a2252452b6e7049afc31fbdf2d39790b669165e89525cd3f5c";
    url = "https://go.dev/dl/go1.24.4.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "27973684b515eaf461065054e6b572d9390c05e69ba4a423076c160165336470";
    url = "https://go.dev/dl/go1.24.4.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "8d529839db29ee171505b89dc9c3de76003a4ab56202d84bddbbecacbfb6d7c9";
    url = "https://go.dev/dl/go1.24.4.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6cbc3ad6cc21bdcc7283824d3ac0e85512c02022f6a35eb2e844882ea6e8448c";
    url = "https://go.dev/dl/go1.24.4.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "e31924abef2a28456b7103c0a5d333dcc11ecf19e76d5de1a383ad5fe0b42457";
    url = "https://go.dev/dl/go1.24.4.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "130c9b061082eca15513e595e9952a2ded32e737e609dd0e49f7dfa74eba026d";
    url = "https://go.dev/dl/go1.24.4.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "77e5da33bb72aeaef1ba4418b6fe511bc4d041873cbf82e5aa6318740df98717";
    url = "https://go.dev/dl/go1.24.4.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "d5501ee5aca0f258d5fe9bfaed401958445014495dc115f202d43d5210b45241";
    url = "https://go.dev/dl/go1.24.4.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "6a554e32301cecae3162677e66d4264b81b3b1a89592dd1b7b5c552c7a49fe37";
    url = "https://go.dev/dl/go1.24.4.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "b208eb25fe244408cbe269ed426454bc46e59d0e0a749b6240d39e884e969875";
    url = "https://go.dev/dl/go1.24.4.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "9ca4afef813a2578c23843b640ae0290aa54b2e3c950a6cc4c99e16a57dec2ec";
    url = "https://go.dev/dl/go1.24.4.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "1d7034f98662d8f2c8abd7c700ada4093acb4f9c00e0e51a30344821d0785c77";
    url = "https://go.dev/dl/go1.24.4.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "0449f3203c39703ab27684be763e9bb78ca9a051e0e4176727aead9461b6deb5";
    url = "https://go.dev/dl/go1.24.4.linux-s390x.tar.gz";
  };
}
