# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24rc1";
  date = "2025-12-12";

  "x86_64-darwin" = {
    sha256 = "0f0895cbaf4e0c0ea0c4c2ffa2f428b0af0dfc39b64ad9f34c7c4de1be39ee55";
    url = "https://go.dev/dl/go1.24rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "457a34b8228db747404b71e9a9789623c808256a862ee5acb5dd9d002d819938";
    url = "https://go.dev/dl/go1.24rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "66b9c553cbc3ea76417c95dee81950f16d10811ea371f4b8c473bef44ba4eb01";
    url = "https://go.dev/dl/go1.24rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "74c162d66208a98a485d3c078280875c687119d3b5e4e1a75222c1c67018cf26";
    url = "https://go.dev/dl/go1.24rc1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "1aa6e36d30a735b077737eb2648b60fc9bf2ef2bbf1f799206a2728c23b94d0f";
    url = "https://go.dev/dl/go1.24rc1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "f8332a537d99504cca6d1a706a34aad74051dadcb098dc5b87de1733e24db3b7";
    url = "https://go.dev/dl/go1.24rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "706c3810c0826dd43bb6d5274c5fa4f644488274533a9bb1f9b13a0e302afcc6";
    url = "https://go.dev/dl/go1.24rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "febc01e97564c3851f96a778bd31f9b7631517f71e7bdf15baeb47c84d735a18";
    url = "https://go.dev/dl/go1.24rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "8b1bd52e292626a2dae8a5d684590380bd3c6af923a7504c0fe9f9e51abbfe1e";
    url = "https://go.dev/dl/go1.24rc1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "54631f57f99e7807324cbe9e3a4133e41edbcf404f885993e5375a7049f4bb5e";
    url = "https://go.dev/dl/go1.24rc1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "492eca7616fe51194886d5ae3a782d97559d7e8ba7e51ccb23fa1b32c79d96e9";
    url = "https://go.dev/dl/go1.24rc1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "5cd2bc49913b0661a2f30d88fb80cd600477f66fa44b2d3d7002ce7fa7bffb91";
    url = "https://go.dev/dl/go1.24rc1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "13331e1c63c944b86602944945a2b87c88c002deaeea971b9930fd1d3b3e7a2c";
    url = "https://go.dev/dl/go1.24rc1.linux-s390x.tar.gz";
  };
}
