# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.0";
  date = "2025-02-11";

  "x86_64-darwin" = {
    sha256 = "7af054e5088b68c24b3d6e135e5ca8d91bbd5a05cb7f7f0187367b3e6e9e05ee";
    url = "https://go.dev/dl/go1.24.0.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "fd9cfb5dd6c75a347cfc641a253f0db1cebaca16b0dd37965351c6184ba595e4";
    url = "https://go.dev/dl/go1.24.0.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "4ee02b1f3812aff4da79c79464ee4038ca61ad74b3a9619850f30435f81c2536";
    url = "https://go.dev/dl/go1.24.0.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "838191001f9324da904dece35a586a3156d548687db87ac9461aa3d38fc88b09";
    url = "https://go.dev/dl/go1.24.0.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "511f7b0cac4c4ed1066d324072ce223b906ad6b2a85f2e1c5d260eb7d08b5901";
    url = "https://go.dev/dl/go1.24.0.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "90521453a59c6ce20364d2dc7c38532949b033b602ba12d782caeb90af1b0624";
    url = "https://go.dev/dl/go1.24.0.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "dea9ca38a0b852a74e81c26134671af7c0fbe65d81b0dc1c5bfe22cf7d4c8858";
    url = "https://go.dev/dl/go1.24.0.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "c3fa6d16ffa261091a5617145553c71d21435ce547e44cc6dfb7470865527cc7";
    url = "https://go.dev/dl/go1.24.0.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "695dc54fa14cd3124fa6900d7b5ae39eeac23f7a4ecea81656070160fac2c54a";
    url = "https://go.dev/dl/go1.24.0.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "a201e4c9b7e6d29ed64c43296ed88e81a66f82f2093ce45b766d2c526941396f";
    url = "https://go.dev/dl/go1.24.0.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "a871a43de7d26c91dd90cb6e0adacb214c9e35ee2188c617c91c08c017efe81a";
    url = "https://go.dev/dl/go1.24.0.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "620dcf48c6297519aad6c81f8e344926dc0ab09a2a79f1e306964aece95a553d";
    url = "https://go.dev/dl/go1.24.0.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "544d78b077c6b54bf78958c4a8285abec2d21f668fb007261c77418cd2edbb46";
    url = "https://go.dev/dl/go1.24.0.linux-s390x.tar.gz";
  };
}
