# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.3";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "13e6fe3fcf65689d77d40e633de1e31c6febbdbcb846eb05fc2434ed2213e92b";
    url = "https://go.dev/dl/go1.24.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "64a3fa22142f627e78fac3018ce3d4aeace68b743eff0afda8aae0411df5e4fb";
    url = "https://go.dev/dl/go1.24.3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9fe6101b3797919bd7337ee5ce591954f85d59db7ae88983904db29fd64c3dd1";
    url = "https://go.dev/dl/go1.24.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6ccf4cca287e90cc28cd7954b6172f5d177a17e20b072b65f7f39636c325e2fb";
    url = "https://go.dev/dl/go1.24.3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "8f6494a12a874d0ea57c67987829359e016960ce3ba0673273609d6ac2af589a";
    url = "https://go.dev/dl/go1.24.3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "41b1051063e68cbd2b919bf12326764fe33937cf1d32b5c529dd1a4f43dce578";
    url = "https://go.dev/dl/go1.24.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "3333f6ea53afa971e9078895eaa4ac7204a8c6b5c68c10e6bc9a33e8e391bdd8";
    url = "https://go.dev/dl/go1.24.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "a463cb59382bd7ae7d8f4c68846e73c4d589f223c589ac76871b66811ded7836";
    url = "https://go.dev/dl/go1.24.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "17a392d7e826625dd12a32099df0b00b85c32d8132ed86fe917183ee5c3f88ed";
    url = "https://go.dev/dl/go1.24.3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "e4b003c04c902edc140153d279b42167f1ad7c229f48f1f729bbef5e65e88d1f";
    url = "https://go.dev/dl/go1.24.3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "341a749d168f47b1d4dad25e32cae70849b7ceed7c290823b853c9e6b0df0856";
    url = "https://go.dev/dl/go1.24.3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "fa482f53ccb4ba280316b8c5751ea67291507280d9166f2a38fe4d9b5d5fb64b";
    url = "https://go.dev/dl/go1.24.3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "a87b0c2a079a0bece1620fb29a00e02b4dba17507850f837e754af7d57cda282";
    url = "https://go.dev/dl/go1.24.3.linux-s390x.tar.gz";
  };
}
