# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.2";
  date = "2025-04-01";

  "x86_64-darwin" = {
    sha256 = "238d9c065d09ff6af229d2e3b8b5e85e688318d69f4006fb85a96e41c216ea83";
    url = "https://go.dev/dl/go1.24.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "b70f8b3c5b4ccb0ad4ffa5ee91cd38075df20fdbd953a1daedd47f50fbcff47a";
    url = "https://go.dev/dl/go1.24.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "026f1dd906189acff714c7625686bbc4ed91042618ba010d45b671461acc9e63";
    url = "https://go.dev/dl/go1.24.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "49399ba759b570a8f87d12179133403da6c2dd296d63a8830dee309161b9c40c";
    url = "https://go.dev/dl/go1.24.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "ef856428b60a8c0bd9a2cba596e83024be6f1c2d5574e89cb1ff2262b08df8b9";
    url = "https://go.dev/dl/go1.24.2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "4c382776d52313266f3026236297a224a6688751256a2dffa3f524d8d6f6c0ba";
    url = "https://go.dev/dl/go1.24.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "68097bd680839cbc9d464a0edce4f7c333975e27a90246890e9f1078c7e702ad";
    url = "https://go.dev/dl/go1.24.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "756274ea4b68fa5535eb9fe2559889287d725a8da63c6aae4d5f23778c229f4b";
    url = "https://go.dev/dl/go1.24.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "438d5d3d7dcb239b58d893a715672eabe670b9730b1fd1c8fc858a46722a598a";
    url = "https://go.dev/dl/go1.24.2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "6aefd3bf59c3c5592eda4fb287322207f119c2210f3795afa9be48d3ccb73e1b";
    url = "https://go.dev/dl/go1.24.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "5fff857791d541c71d8ea0171c73f6f99770d15ff7e2ad979104856d01f36563";
    url = "https://go.dev/dl/go1.24.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "91bda1558fcbd1c92769ad86c8f5cf796f8c67b0d9d9c19f76eecfc75ce71527";
    url = "https://go.dev/dl/go1.24.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "1cb3448166d6abb515a85a3ee5afbdf932081fb58ad7143a8fb666fbc06146d9";
    url = "https://go.dev/dl/go1.24.2.linux-s390x.tar.gz";
  };
}
