# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.9";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "961aa2ae2b97e428d6d8991367e7c98cb403bac54276b8259aead42a0081591c";
    url = "https://go.dev/dl/go1.24.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "af451b40651d7fb36db1bbbd9c66ddbed28b96d7da48abea50a19f82c6e9d1d6";
    url = "https://go.dev/dl/go1.24.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "729b05acac1d9e3d98350e650bb9fb925ef8ee84c7a3f8838b1041368cc21cb5";
    url = "https://go.dev/dl/go1.24.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6d127c1b0533a61afbe42d1722da9fab9b2c0accca0a43dd9553abe2159a0e24";
    url = "https://go.dev/dl/go1.24.9.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "46da5f0d6aefa9c838fc9191c09e839c90e85c79ed14b24d26227fa7ac1321e0";
    url = "https://go.dev/dl/go1.24.9.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "61f9033947f789a3ce117fe61c4ba37d376522337e8bb8bfff77aaae211218e1";
    url = "https://go.dev/dl/go1.24.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "5b7899591c2dd6e9da1809fde4a2fad842c45d3f6b9deb235ba82216e31e34a6";
    url = "https://go.dev/dl/go1.24.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9aa1243d51d41e2f93e895c89c0a2daf7166768c4a4c3ac79db81029d295a540";
    url = "https://go.dev/dl/go1.24.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "39dafc8e7e5e455995f87e1ffc6b0892302ea519c1f0e59c9e2e0fda41b8aa56";
    url = "https://go.dev/dl/go1.24.9.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "2c6bb497029864d10a65a9a97f47f1d300385b36821c8be2cbc8b5988196a157";
    url = "https://go.dev/dl/go1.24.9.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "8e52374ce7500234cf9e43dae2ecd57cc6062d4ab40b42da9d1eecef5fa92df6";
    url = "https://go.dev/dl/go1.24.9.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "26a399d862247dc8b10e0a6f03c4b043ef7f94a63b788e502be62d380b167f51";
    url = "https://go.dev/dl/go1.24.9.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "8fc2a8a4d4c1bf26cf6481e3f1b8f8e68569861b32547907b24da8fb49419f82";
    url = "https://go.dev/dl/go1.24.9.linux-s390x.tar.gz";
  };
}
