# Auto-generated by goscrape - do not edit manually
{
  version = "1.25.6";
  date = "2026-01-15";

  "x86_64-darwin" = {
    sha256 = "e2b5b237f5c262931b8e280ac4b8363f156e19bfad5270c099998932819670b7";
    url = "https://go.dev/dl/go1.25.6.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "984521ae978a5377c7d782fd2dd953291840d7d3d0bd95781a1f32f16d94a006";
    url = "https://go.dev/dl/go1.25.6.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "59fe62eee3cca65332acef3ebe9b6ff3272467e0a08bf7f68f96334902bf23b9";
    url = "https://go.dev/dl/go1.25.6.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "f022b6aad78e362bcba9b0b94d09ad58c5a70c6ba3b7582905fababf5fe0181a";
    url = "https://go.dev/dl/go1.25.6.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "738ef87d79c34272424ccdf83302b7b0300b8b096ed443896089306117943dd5";
    url = "https://go.dev/dl/go1.25.6.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "679f0e70b27c637116791e3c98afbf8c954deb2cd336364944d014f8e440e2ae";
    url = "https://go.dev/dl/go1.25.6.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "be22b65ded1d4015d7d9d328284c985932771d120a371c7df41b2d4d1a91e943";
    url = "https://go.dev/dl/go1.25.6.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "61e1d50e332359474ff6dcf4bc0bd34ba2d2cf4ef649593a5faa527f0ab84e2b";
    url = "https://go.dev/dl/go1.25.6.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "648484146702dd58db0e2c3d15bda3560340d149ed574936e63285a823116b77";
    url = "https://go.dev/dl/go1.25.6.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "433fe54d8797700b44fc4f1d085f9cd50ab3511b9b484fdfbb7b6c32a2be2486";
    url = "https://go.dev/dl/go1.25.6.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "bee02dbe034b12b839ae7807a85a61c13bee09ee38f2eeba2074bd26c0c0ab73";
    url = "https://go.dev/dl/go1.25.6.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "82a6b989afda1681ecb1f4fa96f1006484f42643eb5e76bed58f7f97316bf84b";
    url = "https://go.dev/dl/go1.25.6.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "3d97cc5670a0da9cb177037782129f0bf499ecb47abc40488248548abd2c2c35";
    url = "https://go.dev/dl/go1.25.6.linux-s390x.tar.gz";
  };
}
