# Auto-generated by go-scrape - do not edit manually
{
  version = "1.25.2";
  date = "2025-10-07";

  "x86_64-darwin" = {
    sha256 = "95493abb01da81638ab5083ff3f97e8f923cb42a64c2e16728e3cf5b0cd3fc5a";
    url = "https://go.dev/dl/go1.25.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "d1ade1b480e51b6269b6e65856c602aed047e1f0d32fffef7eebbd7faa8d7687";
    url = "https://go.dev/dl/go1.25.2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "5b58265121876ae0c204701103800acd08a2070445bc111ff4e18232769bd360";
    url = "https://go.dev/dl/go1.25.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "283b88c46edd5c1df1f146f121950e50bd92c4ebf9591372f79a9e2b1766eaef";
    url = "https://go.dev/dl/go1.25.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "524c030f87c64ac9a03587dd805d510d9e545874c0691d83a96246ee1d40c3fc";
    url = "https://go.dev/dl/go1.25.2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "abc7b51a27fbdee522f3e8f6a84d2a1620ef42fd03559775ddf91165023bf7fc";
    url = "https://go.dev/dl/go1.25.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "d7fa7f8fbd16263aa2501d681b11f972a5fd8e811f7b10cb9b26d031a3d7454b";
    url = "https://go.dev/dl/go1.25.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9aaeb044bf8dbf50ca2fbf0edc5ebc98b90d5bda8c6b2911526df76f61232919";
    url = "https://go.dev/dl/go1.25.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "63572d476f02c1f1049e11c42cb2017eb7b241187e219a004e83202a4a17d21e";
    url = "https://go.dev/dl/go1.25.2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "8b8fb873238d7fe496816862f989dd8d08e45b3cb61b517bdcf64496ce3d7ec6";
    url = "https://go.dev/dl/go1.25.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "91dd35ac3f33baa642d9bac22b626bdb5ee0372cf80e7d782994337f81f34417";
    url = "https://go.dev/dl/go1.25.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "77ec1adfbc80e43a8822db9072aae841cac632881dd11d2a27e5986c3ea7dfcd";
    url = "https://go.dev/dl/go1.25.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "3a9b8f2675c1d15fb668c01f02ae705999fb404119c2a20238a3fddcf18c7602";
    url = "https://go.dev/dl/go1.25.2.linux-s390x.tar.gz";
  };
}
