# Auto-generated by go-scrape - do not edit manually
{
  version = "1.25rc2";
  date = "2025-12-12";

  "x86_64-darwin" = {
    sha256 = "a09e19acff22863dfad464aee1b8b83689b75b233d65406b1d9e63d1dea21296";
    url = "https://go.dev/dl/go1.25rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "995979864ed7a80a81fc5c20381da9973f8528f3776ddcebf542d888e72991d2";
    url = "https://go.dev/dl/go1.25rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "42fde484c7dd07883d1b4a6783523db84c01491e733e7d824da19343fa6d1f6c";
    url = "https://go.dev/dl/go1.25rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "5423d4c578f1a642513171d827f33a4bc66694244e1039a5cac372cf4da93f1f";
    url = "https://go.dev/dl/go1.25rc2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "03aab5a14dccb30621728840d6e2400f6aabb43190405a88daed376065ad5ae0";
    url = "https://go.dev/dl/go1.25rc2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "918ed022a37e1f8e6cf11d2285084b45c6f83818592b2c7cd925449d756e873a";
    url = "https://go.dev/dl/go1.25rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "efcd3a151b174ffebde86b9d391ad59084300a4c5e9ea8c1d5dff90bbac38820";
    url = "https://go.dev/dl/go1.25rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "e9a077cef12d5c4a82df6d85a76f5bb7a4abd69c7d0fbab89d072591ef219ed3";
    url = "https://go.dev/dl/go1.25rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "21d2d8eb318b3a4acccd6ac334fb1a27b84dd6e72f59483c612e69bdde79fffa";
    url = "https://go.dev/dl/go1.25rc2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "36a407279177b93cc04b57ec5909a2aa847b35d8771cef734551e4cd77cb32eb";
    url = "https://go.dev/dl/go1.25rc2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "4025e48dc929940f89bbbacb37bc39291c2ee4dd5725b7f565e0efd501e27350";
    url = "https://go.dev/dl/go1.25rc2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "1dc59f6bf60ad5240ccd3b47c0f82b6e4bbb3e569aab892731b6072aa83be078";
    url = "https://go.dev/dl/go1.25rc2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "49ff951fe67c0d8b2945118bd219dcaa9b5a0a7682a0d5e54f7e43d60fd06564";
    url = "https://go.dev/dl/go1.25rc2.linux-s390x.tar.gz";
  };
}
