# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.5";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "23d22bb6571bbd60197bee8aaa10e702f9802786c2e2ddce5c84527e86b66aa0";
    url = "https://go.dev/dl/go1.19.5.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "4a67f2bf0601afe2177eb58f825adf83509511d77ab79174db0712dc9efa16c8";
    url = "https://go.dev/dl/go1.19.5.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b18a5e1e60130003896e1d1c8a9e142c7cccf6f5063d52c55dd42006434419c1";
    url = "https://go.dev/dl/go1.19.5.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "317996f7427691ff3a7ffd1b6aa089b9c66cd76f32e9107443f2f6aad1bb568a";
    url = "https://go.dev/dl/go1.19.5.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "f68331aa7458a3598060595f5601d5731fd452bb2c62ff23095ddad68854e510";
    url = "https://go.dev/dl/go1.19.5.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "36519702ae2fd573c9869461990ae550c8c0d955cd28d2827a6b159fda81ff95";
    url = "https://go.dev/dl/go1.19.5.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "fc0aa29c933cec8d76f5435d859aaf42249aa08c74eb2d154689ae44c08d23b3";
    url = "https://go.dev/dl/go1.19.5.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "ec14f04bdaf4a62bdcf8b55b9b6434cc27c2df7d214d0bb7076a7597283b026a";
    url = "https://go.dev/dl/go1.19.5.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "e4032e7c52ebc48bad5c58ba8de0759b6091d9b1e59581a8a521c8c9d88dbe93";
    url = "https://go.dev/dl/go1.19.5.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "764871cbca841a99a24e239b63c68a4aaff4104658e3165e9ca450cac1fcbea3";
    url = "https://go.dev/dl/go1.19.5.linux-s390x.tar.gz";
  };
}
