# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.6";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "108a3cd27b7dff5a8b3540d3bab0aa04d16814babc85625b183f2a1217af88d0";
    url = "https://go.dev/dl/go1.19.6.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "dfbf3e4686dd7fee7a9c0223c52b124c1af5f02508baf07e1e59489cd9df2a90";
    url = "https://go.dev/dl/go1.19.6.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "6b20260968ed6ccd3d48b39aaee7816e44c8c5ccc341c20e6a46327d051667c2";
    url = "https://go.dev/dl/go1.19.6.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "f4b432ebe462a6edd6131e94360b9f0fb3b8136bba39caeacb4aa22a89ba1dd8";
    url = "https://go.dev/dl/go1.19.6.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "da4546cc516ae88698e8643d6d22fe1465b44dd49fc36abb34d53a93c19581ad";
    url = "https://go.dev/dl/go1.19.6.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "e3410c676ced327aec928303fef11385702a5562fd19d9a1750d5a2979763c3d";
    url = "https://go.dev/dl/go1.19.6.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "e4d63c933a68e5fad07cab9d12c5c1610ce4810832d47c44314c3246f511ac4f";
    url = "https://go.dev/dl/go1.19.6.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "1f5900567595366fbb3b9ea02cee8ea67ac4b87234fb246549b902cde1013821";
    url = "https://go.dev/dl/go1.19.6.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "4ce62f9bad666e7aa73171c3056fe89b23548d1a78de8be5f30b64ccd10990de";
    url = "https://go.dev/dl/go1.19.6.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "1673f748e25acbb2504536f41239231ac658c99e06d04ba68d51123ee62108a5";
    url = "https://go.dev/dl/go1.19.6.linux-s390x.tar.gz";
  };
}
