# Auto-generated by go-scrape - do not edit manually
{
  version = "1.19.13";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "1b4329dc9e73def7f894ca71fce78bb9f3f5c4c8671b6c7e4f363a3f47e88325";
    url = "https://go.dev/dl/go1.19.13.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "022b35fa9c79b9457fa4a14fd9c4cf5f8ea315a8f2e3b3cd949fea55e11a7d7b";
    url = "https://go.dev/dl/go1.19.13.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "a0ad2dc1479310774ceba502c10097963637e398b235e48bbf26d8ed971b3fac";
    url = "https://go.dev/dl/go1.19.13.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "97fd4990c5349ab922b9bf3e4c655e899135559ea6ad666d4b3c7a27b1e147a2";
    url = "https://go.dev/dl/go1.19.13.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "8368a9fdb3ab78da1ce75b80dc765c2814ca42afc2cf7e7dc45a1a61eaea22be";
    url = "https://go.dev/dl/go1.19.13.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4643d4c29c55f53fa0349367d7f1bb5ca554ea6ef528c146825b0f8464e2e668";
    url = "https://go.dev/dl/go1.19.13.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "1142ada7bba786d299812b23edd446761a54efbbcde346c2f0bc69ca6a007b58";
    url = "https://go.dev/dl/go1.19.13.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "9dfd42b41057514454134552854cd1a5a47d501b760c87e9b0d3b0665374d8d9";
    url = "https://go.dev/dl/go1.19.13.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "fe02b81fd18913a19de420929f1fc2698eea15e90ad1d13471168fcdabe3aaff";
    url = "https://go.dev/dl/go1.19.13.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "af324cb46b268722e8ed3c7ecac87af4ee288ccb50be30ce2184fa7210495fb9";
    url = "https://go.dev/dl/go1.19.13.linux-s390x.tar.gz";
  };
}
