package modproxy

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
	"gotest.tools/v3/golden"
)

const fakeManifest = `# Auto-generated by goscrape - do not edit manually
{
  version = "%s";
  date = "2024-01-01";
  module = "example.com/tool";
  subPackages = ["cmd/tool"];
  go = "%s";
  hash = "sha256-fake=";

  mod = {
    "example.com/dep" = {
      version = "v1.0.0";
      hash = "sha256-fake=";
      go = "1.10";
      packages = ["example.com/dep"];
    };
  };
}
`

func TestWriteIndex(t *testing.T) {
	dir := t.TempDir()

	versions := map[string]string{
		"0.3.1":  "1.17",
		"0.10.0": "1.25.0",
		"0.9.0":  "1.24.0",
	}
	for version, goVersion := range versions {
		content := fmt.Sprintf(fakeManifest, version, goVersion)
		require.NoError(t, os.WriteFile(filepath.Join(dir, version+".nix"), []byte(content), 0o644))
	}

	require.NoError(t, writeIndex(dir))

	got, err := os.ReadFile(filepath.Join(dir, "index.nix"))
	require.NoError(t, err)

	golden.Assert(t, string(got), "index.nix.golden")
}
