# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.6";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "4a8d7a32052f223e71faab424a69430455b27b3fff5f4e651f9d97c3e51a8746";
    url = "https://go.dev/dl/go1.24.6.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "4e29202c49573b953be7cc3500e1f8d9e66ddd12faa8cf0939a4951411e09a2a";
    url = "https://go.dev/dl/go1.24.6.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9cd74ad74f3ad833e92529f2fd9b0d7d9ffaab46307eccadb0afcf9a1ba09553";
    url = "https://go.dev/dl/go1.24.6.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "4983e2b10ae1f754e4eb07e1e589691c7e1d0dc428a92c16bd0e2ba03cc23ed9";
    url = "https://go.dev/dl/go1.24.6.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "76a75ad5125217c268029c0ad9c7295cc7f6042fe9cba4bebf9a89f7f42ad8af";
    url = "https://go.dev/dl/go1.24.6.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "bb5bf69d75e7edbc93339824753a1a4655a928451a2c5e13ff90959ad69e065b";
    url = "https://go.dev/dl/go1.24.6.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "bbca37cc395c974ffa4893ee35819ad23ebb27426df87af92e93a9ec66ef8712";
    url = "https://go.dev/dl/go1.24.6.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "124ea6033a8bf98aa9fbab53e58d134905262d45a022af3a90b73320f3c3afd5";
    url = "https://go.dev/dl/go1.24.6.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7feb4d25f5e72f94fda81c99d4adb6630dfa2c35211e0819417d53af6e71809e";
    url = "https://go.dev/dl/go1.24.6.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "8424d9c52b254255d2720769366af73802747e4eaf339c6e86bb52e5a1809fcb";
    url = "https://go.dev/dl/go1.24.6.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "63fc9559a3d6dfd63aa902f714375b879bbc848466181c035c122489b9646e27";
    url = "https://go.dev/dl/go1.24.6.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "e92c19ff15a9004fe43e1f62d433555250ef9fe3fabee3dc29ebd4802c2b8021";
    url = "https://go.dev/dl/go1.24.6.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "4cde28d9ffb6eef86bf8dac6852a45db335009f67e60bee3e477dd0ba0ff9704";
    url = "https://go.dev/dl/go1.24.6.linux-s390x.tar.gz";
  };
}
