# Auto-generated by go-scrape - do not edit manually
{
  version = "1.24.11";
  date = "2025-12-09";

  "x86_64-darwin" = {
    sha256 = "c45566cf265e2083cd0324e88648a9c28d0edede7b5fd12f8dc6932155a344c5";
    url = "https://go.dev/dl/go1.24.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a9c90c786e75d5d1da0547de2d1199034df6a4b163af2fa91b9168c65f229c12";
    url = "https://go.dev/dl/go1.24.11.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "bb702d0b67759724dccee1825828e8bae0b5199e3295cac5a98a81f3098fa64a";
    url = "https://go.dev/dl/go1.24.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "bceca00afaac856bc48b4cc33db7cd9eb383c81811379faed3bdbc80edb0af65";
    url = "https://go.dev/dl/go1.24.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "beaf0f51cbe0bd71b8289b2b6fa96c0b11cd86aa58672691ef2f1de88eb621de";
    url = "https://go.dev/dl/go1.24.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "24d712a7e8ea2f429c05bc67287249e0291f2fe0ea6d6ff268f11b7343ad0f47";
    url = "https://go.dev/dl/go1.24.11.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "99229da13fd74d5cdcb81fae844bf48574c64eae0d2821137f45c848f1453771";
    url = "https://go.dev/dl/go1.24.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "de6fdd4eefa06dbb2531ed601ef5f2b88e73f49f89c10bc1078f51a96a7ae88f";
    url = "https://go.dev/dl/go1.24.11.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "eead4408b88557228fe4b30ee90aa33062d338fa5647c046a5aaca4237839f5a";
    url = "https://go.dev/dl/go1.24.11.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "45c3cbec9e30071ea1f3323fc30fb1b8497007c992f00ba48fcdcb729f06467c";
    url = "https://go.dev/dl/go1.24.11.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "f770d0c5d7e7e2edb030133ac7854d9204f4e954e79a176e81362ffedf6ea34c";
    url = "https://go.dev/dl/go1.24.11.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "9db9ba8e6b60f3662f55ed78b128175edbe8b9480e657126a5b8f5043ee1e38c";
    url = "https://go.dev/dl/go1.24.11.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "5955ddda3445b2cbfd81b8772044084911f55d0baeb32414da0411f6a377a2d4";
    url = "https://go.dev/dl/go1.24.11.linux-s390x.tar.gz";
  };
}
