# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "0.4.5";
  date = "2023-08-17";
  module = "honnef.co/go/tools";
  subPackages = ["cmd/staticcheck"];
  go = "1.19";
  hash = "sha256-l1KrTOuH0AC+i0DW3ApypYH6PtWmHNn0uiPyaw6bfvo=";

  mod = {
    "github.com/BurntSushi/toml" = {
      version = "v1.2.1";
      hash = "sha256-Z1dlsUTjF8SJZCknYKt7ufJz8NPGg9P9+W17DQn+LO0=";
      go = "1.16";
      packages = ["github.com/BurntSushi/toml" "github.com/BurntSushi/toml/internal"];
    };
    "golang.org/x/exp/typeparams" = {
      version = "v0.0.0-20221208152030-732eee02a75a";
      hash = "sha256-IdVdYrszhwtJ63OmlyzuqJ261dGyYulHd/MW9RKkIZg=";
      go = "1.18";
      packages = ["golang.org/x/exp/typeparams"];
    };
    "golang.org/x/mod" = {
      version = "v0.10.0";
      hash = "sha256-g0T2wz+K0nhPWdVQJRGGqEqzlTHMBahv+9C3y090eIM=";
      go = "1.17";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sys" = {
      version = "v0.8.0";
      hash = "sha256-wLPPnoFkHM1HPUaFIfRyQZOJjrqXVZimB0nMySly7Xg=";
      go = "1.17";
      packages = ["golang.org/x/sys/execabs"];
    };
    "golang.org/x/tools" = {
      version = "v0.9.4-0.20230601214343-86c93e8732cc";
      hash = "sha256-KD1ooN7+DBHnP8jUK6tdtVKYdwtjvDSyRt6kxmjSWio=";
      go = "1.18";
      packages = ["golang.org/x/tools/go/analysis" "golang.org/x/tools/go/analysis/analysistest" "golang.org/x/tools/go/analysis/internal/analysisflags" "golang.org/x/tools/go/analysis/internal/checker" "golang.org/x/tools/go/analysis/passes/inspect" "golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/ast/inspector" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/expect" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/internal/packagesdriver" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/diff" "golang.org/x/tools/internal/diff/lcs" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/event/tag" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/goroot" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/robustio" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/tokeninternal" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal" "golang.org/x/tools/txtar"];
    };
  };
}
