# Auto-generated by goscrapeproxy - do not edit manually
{
  version = "0.7.0";
  date = "2026-02-13";
  module = "honnef.co/go/tools";
  subPackages = ["cmd/staticcheck"];
  go = "1.25.0";
  hash = "sha256-K3Yt3O/obBerNwnW0HKY9/pf+t9lZp8u5MzKDvyjv1o=";

  mod = {
    "github.com/BurntSushi/toml" = {
      version = "v1.4.1-0.20240526193622-a339e1f7089c";
      hash = "sha256-ixpMR6uwjREWWfY9rStfd5AB7UGkE3EqlR7JocUK+JE=";
      go = "1.18";
      packages = ["github.com/BurntSushi/toml" "github.com/BurntSushi/toml/internal"];
    };
    "golang.org/x/exp" = {
      version = "v0.0.0-20231110203233-9a3e6036ecaa";
      hash = "sha256-m1T4KePBRCJpAjnuq4BnDYXebOHiVI6h2489XD5R9BA=";
      go = "1.20";
      packages = ["golang.org/x/exp/constraints"];
    };
    "golang.org/x/exp/typeparams" = {
      version = "v0.0.0-20231108232855-2478ac86f678";
      hash = "sha256-0uQMDDiRS2ZMGdS4k7/+JgP7SHC0p+sA9bnywR+sTuU=";
      go = "1.18";
      packages = ["golang.org/x/exp/typeparams"];
    };
    "golang.org/x/mod" = {
      version = "v0.31.0";
      hash = "sha256-ZVNmaZADgM3+30q9rW8q4gP6ySkT7r1eb4vrHIlpCjM=";
      go = "1.24.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.19.0";
      hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno=";
      go = "1.24.0";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/sys" = {
      version = "v0.39.0";
      hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U=";
      go = "1.24.0";
      packages = ["golang.org/x/sys/execabs"];
    };
    "golang.org/x/tools" = {
      version = "v0.40.1-0.20260108161641-ca281cf95054";
      hash = "sha256-odtYPHSujOgB3dZ57DCiAl7Lo/6Lnkcd+futTEQA6/g=";
      go = "1.24.0";
      packages = ["golang.org/x/tools/go/analysis" "golang.org/x/tools/go/analysis/analysistest" "golang.org/x/tools/go/analysis/checker" "golang.org/x/tools/go/analysis/internal" "golang.org/x/tools/go/analysis/internal/analysisflags" "golang.org/x/tools/go/analysis/internal/checker" "golang.org/x/tools/go/analysis/passes/ctrlflow" "golang.org/x/tools/go/analysis/passes/inspect" "golang.org/x/tools/go/analysis/singlechecker" "golang.org/x/tools/go/analysis/unitchecker" "golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/ast/edge" "golang.org/x/tools/go/ast/inspector" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/cfg" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/aliases" "golang.org/x/tools/internal/analysis/driverutil" "golang.org/x/tools/internal/astutil/free" "golang.org/x/tools/internal/diff" "golang.org/x/tools/internal/diff/lcs" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/facts" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/stdlib" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal" "golang.org/x/tools/internal/versions" "golang.org/x/tools/txtar"];
    };
    "golang.org/x/tools/go/expect" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-7JLwLMSzp9Eovnq7YBTv4Lgx8/FZnfMlx6ZkUdaW4dc=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/expect"];
    };
  };
}
