# Auto-generated by goscrape - do not edit manually
{
  version = "0.8.0-rc.1";
  date = "2026-06-25";
  module = "honnef.co/go/tools";
  subPackages = ["cmd/staticcheck"];
  go = "1.26.0";
  license = "MIT";
  hash = "sha256-4vjbfha2vgj7wcQD91cuICn6M3IofrbO/1g7SpPFNbY=";

  mod = {
    "github.com/BurntSushi/toml" = {
      version = "v1.4.1-0.20240526193622-a339e1f7089c";
      hash = "sha256-ixpMR6uwjREWWfY9rStfd5AB7UGkE3EqlR7JocUK+JE=";
      go = "1.18";
      packages = ["github.com/BurntSushi/toml" "github.com/BurntSushi/toml/internal"];
    };
    "github.com/google/go-cmp" = {
      version = "v0.7.0";
      hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM=";
      go = "1.21";
      packages = ["github.com/google/go-cmp/cmp" "github.com/google/go-cmp/cmp/internal/diff" "github.com/google/go-cmp/cmp/internal/flags" "github.com/google/go-cmp/cmp/internal/function" "github.com/google/go-cmp/cmp/internal/value"];
    };
    "golang.org/x/exp" = {
      version = "v0.0.0-20231110203233-9a3e6036ecaa";
      hash = "sha256-m1T4KePBRCJpAjnuq4BnDYXebOHiVI6h2489XD5R9BA=";
      go = "1.20";
      packages = ["golang.org/x/exp/constraints"];
    };
    "golang.org/x/exp/typeparams" = {
      version = "v0.0.0-20231108232855-2478ac86f678";
      hash = "sha256-0uQMDDiRS2ZMGdS4k7/+JgP7SHC0p+sA9bnywR+sTuU=";
      go = "1.18";
      packages = ["golang.org/x/exp/typeparams"];
    };
    "golang.org/x/mod" = {
      version = "v0.35.0";
      hash = "sha256-ICEQxokHywOFInDPqoP+go9l1tZSz3roknF5SXPtNV4=";
      go = "1.25.0";
      packages = ["golang.org/x/mod/internal/lazyregexp" "golang.org/x/mod/modfile" "golang.org/x/mod/module" "golang.org/x/mod/semver"];
    };
    "golang.org/x/sync" = {
      version = "v0.20.0";
      hash = "sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y=";
      go = "1.25.0";
      packages = ["golang.org/x/sync/errgroup"];
    };
    "golang.org/x/tools" = {
      version = "v0.44.1-0.20260420230617-19499e7caabc";
      hash = "sha256-Fe4VIKmduDtJa/ZHju23UQQicEF6n3pHVqMyZM/+K/A=";
      go = "1.25.0";
      packages = ["golang.org/x/tools/go/analysis" "golang.org/x/tools/go/analysis/analysistest" "golang.org/x/tools/go/analysis/checker" "golang.org/x/tools/go/analysis/internal" "golang.org/x/tools/go/analysis/passes/ctrlflow" "golang.org/x/tools/go/analysis/passes/inspect" "golang.org/x/tools/go/ast/astutil" "golang.org/x/tools/go/ast/edge" "golang.org/x/tools/go/ast/inspector" "golang.org/x/tools/go/buildutil" "golang.org/x/tools/go/cfg" "golang.org/x/tools/go/gcexportdata" "golang.org/x/tools/go/internal/cgo" "golang.org/x/tools/go/loader" "golang.org/x/tools/go/packages" "golang.org/x/tools/go/types/objectpath" "golang.org/x/tools/go/types/typeutil" "golang.org/x/tools/internal/aliases" "golang.org/x/tools/internal/analysis/driverutil" "golang.org/x/tools/internal/astutil/free" "golang.org/x/tools/internal/diff" "golang.org/x/tools/internal/diff/lcs" "golang.org/x/tools/internal/event" "golang.org/x/tools/internal/event/core" "golang.org/x/tools/internal/event/keys" "golang.org/x/tools/internal/event/label" "golang.org/x/tools/internal/gcimporter" "golang.org/x/tools/internal/gocommand" "golang.org/x/tools/internal/packagesinternal" "golang.org/x/tools/internal/pkgbits" "golang.org/x/tools/internal/stdlib" "golang.org/x/tools/internal/testenv" "golang.org/x/tools/internal/typeparams" "golang.org/x/tools/internal/typesinternal" "golang.org/x/tools/internal/versions" "golang.org/x/tools/txtar"];
    };
    "golang.org/x/tools/go/expect" = {
      version = "v0.1.1-deprecated";
      hash = "sha256-7JLwLMSzp9Eovnq7YBTv4Lgx8/FZnfMlx6ZkUdaW4dc=";
      go = "1.23.0";
      packages = ["golang.org/x/tools/go/expect"];
    };
  };
}
