# Auto-generated by goscrape - do not edit manually
{
  version = "1.17.8";
  date = "2022-03-03";

  "x86_64-darwin" = {
    sha256 = "345f530a6a4295a1bf0a25931c08bf31582ed83252580196bd643049dfef0563";
    url = "https://go.dev/dl/go1.17.8.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "2827fb5d62453b30f0644382e22ab9d287c7bca868c374a15145b29e272443b1";
    url = "https://go.dev/dl/go1.17.8.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "9c125df1b1f78b9ecaa5546e1ec84ec60832d5749a632cc326750a1eb1b6f778";
    url = "https://go.dev/dl/go1.17.8.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "cdbe36033d585a3a4c4155fb996a9e67336c7ea73b4382120ce3e52824a97a8f";
    url = "https://go.dev/dl/go1.17.8.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "a826cd599828aeefc86d742e1a8ce8ab7e0251b2429568ad5633e21c8a769053";
    url = "https://go.dev/dl/go1.17.8.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "980e65a863377e69fd9b67df9d8395fd8e93858e7a24c9f55803421e453f4f99";
    url = "https://go.dev/dl/go1.17.8.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "57a9171682e297df1a5bd287be056ed0280195ad079af90af16dcad4f64710cb";
    url = "https://go.dev/dl/go1.17.8.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "3287ca2fe6819fa87af95182d5942bf4fa565aff8f145812c6c70c0466ce25ae";
    url = "https://go.dev/dl/go1.17.8.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "2077dd2fc57a74b0630b0c239ae4e3114607311778effd43fcfe5174133ee188";
    url = "https://go.dev/dl/go1.17.8.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "3fac23801644a2f93a1643acecd5a94a5ea05d88e19467092fb6e64205710f61";
    url = "https://go.dev/dl/go1.17.8.linux-s390x.tar.gz";
  };
}
