# Auto-generated by goscrape - do not edit manually
{
  version = "1.17rc2";
  date = "2021-08-02";

  "x86_64-darwin" = {
    sha256 = "8abf0b17d6a0664e53ea7e1aecb649e2378732d2d97e8a292c27e6aae711c6c9";
    url = "https://go.dev/dl/go1.17rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "fb8954dc8172bfabb8c22125a994a04278be554f15a1cb26ff2595841d9c1ba1";
    url = "https://go.dev/dl/go1.17rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "cffffb5dc4937d1f6728cc9a88aa33ade059040a3b3856eca8e65d31df3e3b49";
    url = "https://go.dev/dl/go1.17rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "48b36ed9618b81d4d59acdec3bcf56f18e97173c46dd5efa875ad7b03da61330";
    url = "https://go.dev/dl/go1.17rc2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "273fd4647d2311e3044d3d937eedbee91477317d867b6c81636fdc0a9ba7f947";
    url = "https://go.dev/dl/go1.17rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "328235edc7c7d2a51d6c6cb4d7ff97e97357654ef9e1098b9a4603a9d278ad04";
    url = "https://go.dev/dl/go1.17rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "4e1b335c53bf28cd20c5f7f2f7e79187b93e71c1d027448e313097785efb673d";
    url = "https://go.dev/dl/go1.17rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "4820fcd80b47e7d7dc1f15343c4fb59e66183cef9dadb3d3ac10f82615ad2141";
    url = "https://go.dev/dl/go1.17rc2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "57fd15f97e4fccc3227d07423baca2b3e44fb2c1b12a35f8cda8a453867ca1b6";
    url = "https://go.dev/dl/go1.17rc2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "be3a78ae162eac193fc66b0ed50f56c75c5a1506c6b631a1f2af3d4e700816fe";
    url = "https://go.dev/dl/go1.17rc2.linux-s390x.tar.gz";
  };
}
