# Auto-generated by goscrape - do not edit manually
{
  version = "1.18beta2";
  date = "2022-01-31";

  "x86_64-darwin" = {
    sha256 = "83fa94b3101d1a00dc5685645e4b49809a5dad18ce19ab449392806a85c05125";
    url = "https://go.dev/dl/go1.18beta2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "b442585cbd50759bd11d7a9971e02ec3b2e8cfc1ff1094fa23afadc9e3889689";
    url = "https://go.dev/dl/go1.18beta2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "f45899dcc440c9943b3af11a2856959e1ffd9fb11d0dbdbe6398615a96715751";
    url = "https://go.dev/dl/go1.18beta2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "f5688d21a0e02991445b7992f01fc5fda459c84a1812b3b08c2ada4a98e74b5e";
    url = "https://go.dev/dl/go1.18beta2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "74ac524d7d17df606cc74059bf30efce35bb6930f950110dd79cc58ba057f186";
    url = "https://go.dev/dl/go1.18beta2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "b5dacafa59737cfb0d657902b70c2ad1b6bb4ed15e85ea2806f72ce3d4824688";
    url = "https://go.dev/dl/go1.18beta2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "21e4248594401568c2e8704b9d26c6185a61f46b4f17e1a628bf1b5d9a010503";
    url = "https://go.dev/dl/go1.18beta2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "bc958a63b51c44762ec026ab587b0261e94cf6337613bfbbcfbd0414fb95f7b6";
    url = "https://go.dev/dl/go1.18beta2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "573916974201745360883102c80482e1d6730683d1a4a6bb4b469978d4f99d30";
    url = "https://go.dev/dl/go1.18beta2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "860ee3e5cd68fd36d3d49654adc37b9450584d07f0745f7f461080d9cc7749e1";
    url = "https://go.dev/dl/go1.18beta2.linux-s390x.tar.gz";
  };
}
