# Auto-generated by goscrape - do not edit manually
{
  version = "1.18beta1";
  date = "2021-12-14";

  "x86_64-darwin" = {
    sha256 = "013d6d427a9591711d6e05defc46c4086e2fb9dffbc41c9a0fce09192e6e8ede";
    url = "https://go.dev/dl/go1.18beta1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "09b7718f2354acb9826eef27f8257ac41c77df6389b14e91af09b90f79f200e8";
    url = "https://go.dev/dl/go1.18beta1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "1cba65f134a4231bb9cf1e9b02ad43bca04eb087a2c8a15c8fa5472e7de124d9";
    url = "https://go.dev/dl/go1.18beta1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "cddf3c8b26240d39df19c914e583b484a265354e392d342e5df2c24ac0a0e2b1";
    url = "https://go.dev/dl/go1.18beta1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "1cf671fafb57371615c454d58f8cd78db63682aba0f19350cea80045aa7d2e54";
    url = "https://go.dev/dl/go1.18beta1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "128f72c5c22640085e4187cd1b540c587cf8fb280f941519bd2d1ae9fdab4f37";
    url = "https://go.dev/dl/go1.18beta1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "717092a7265a86af2454cd402b29e8889fb1c83971220fbc37946755e14c891a";
    url = "https://go.dev/dl/go1.18beta1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d45526c56562abaa473f50302d73abc9f24228108e717a7027024db74fbc774c";
    url = "https://go.dev/dl/go1.18beta1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "a0cef27d97197d9e5f3eae3d47b39ea8ab466ee5d97b7ec41335447ec858c47a";
    url = "https://go.dev/dl/go1.18beta1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "741749a743d29e7f63f4db64f9e4bc2982b974d254dbb13942d6d3cc4f576194";
    url = "https://go.dev/dl/go1.18beta1.linux-s390x.tar.gz";
  };
}
