# Auto-generated by goscrape - do not edit manually
{
  version = "1.19.11";
  date = "2023-07-11";

  "x86_64-darwin" = {
    sha256 = "4a97c282524f1612843dc3fd3a43a662729526516de31a77ff1ea8e3d5528003";
    url = "https://go.dev/dl/go1.19.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "2e216abdf7c5d4a77ebeebac030610e893740085e130f979c4ebea3ba1c8f702";
    url = "https://go.dev/dl/go1.19.11.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "d39aa174e710e90b6bb5aa9bc9d9b460cfe39957f6f4f26d8251bf02491f62c4";
    url = "https://go.dev/dl/go1.19.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "22e1f352c7b927d30333ffb3cc9536260084a4013015c54737ea9ea44c301306";
    url = "https://go.dev/dl/go1.19.11.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "29ca147de075cfbb2e7157cf74351aae1b77d003fcdeeb75801a61c73f637a6f";
    url = "https://go.dev/dl/go1.19.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "ee18f98a03386e2bf48ff75737ea17c953b1572f9b1114352f104ac5eef04bb4";
    url = "https://go.dev/dl/go1.19.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "ae22c047e0e63d2d28205b529baaf9d9ca0c93e890c309af62cd116b9efebcbd";
    url = "https://go.dev/dl/go1.19.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "1945391a508243bc38b2b9cc5f309772b9e8ba9f8921220868c172c1e23722f1";
    url = "https://go.dev/dl/go1.19.11.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "fee20eb309c4777eaf4390d21520229af3e7cb635dc5543d8149a64296a5096e";
    url = "https://go.dev/dl/go1.19.11.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "0c593538f5527ec786962143d521b0ba1a7df7e752c051370f8e38416c14b704";
    url = "https://go.dev/dl/go1.19.11.linux-s390x.tar.gz";
  };
}
