# Auto-generated by goscrape - do not edit manually
{
  version = "1.19rc2";
  date = "2022-07-12";

  "x86_64-darwin" = {
    sha256 = "e85f22cecec124ac8eff87be0ce8db0ed74b74aa4f3458681ea3044e9e10c411";
    url = "https://go.dev/dl/go1.19rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "7a097fcd5ff9a9ea7d4585e5d54df51636fb78af9cd323e807d9b3c9db68c761";
    url = "https://go.dev/dl/go1.19rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "33c64db1307749641a352a9ed862b8f392f817f9ca91b7599cfa551b7251840d";
    url = "https://go.dev/dl/go1.19rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "ee55a8a0d68b5b7f8f1584e15bda08615a091cb2d9ce1ec10d04256b11f95237";
    url = "https://go.dev/dl/go1.19rc2.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "6d7b02ba7c008f38ebb9ab78c137c6b7a2fd7cd6badefcc2a008cc45cc6501a2";
    url = "https://go.dev/dl/go1.19rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "9130c6f8e87ce9bb4813533a68c3f17c82c7307caf8795d3c9427652b77f81aa";
    url = "https://go.dev/dl/go1.19rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9260d3d8db973e2afd0b53f70ebb2f977f3716660de02a0ca4a14667fab2c658";
    url = "https://go.dev/dl/go1.19rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "83a956703e69dd0a2ce1d4881e6038fb1a292c535c8b7ae80993b2a15708757d";
    url = "https://go.dev/dl/go1.19rc2.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "b4edcd4780018b479220c65a12e149c9b95b2062cbdba47432b09f96b3de37f0";
    url = "https://go.dev/dl/go1.19rc2.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "a017b5c227bc6cc6e191d66a2e5f00737f1a6163e07416cee39c98af6118fea8";
    url = "https://go.dev/dl/go1.19rc2.linux-s390x.tar.gz";
  };
}
