# Auto-generated by goscrape - do not edit manually
{
  version = "1.19.10";
  date = "2023-06-06";

  "x86_64-darwin" = {
    sha256 = "2a7246247fc8ee798ac5a2276b6b89165ec6336666a35b2d0733459d98a9581c";
    url = "https://go.dev/dl/go1.19.10.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a66a47adcf67e7036274765d61f7b79db68462476537b3b4bad23dc1cf4bd118";
    url = "https://go.dev/dl/go1.19.10.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "59523bef7715b605e7a181851a1293339031f4d90c18cd51c7d49406fedae1d9";
    url = "https://go.dev/dl/go1.19.10.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "0d22265662eaa9b8136223f8ab68f5c06c58c6a6311748fb810e830ebd17cbe2";
    url = "https://go.dev/dl/go1.19.10.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "45a34313664d66087d49b46ca63a3ecf292f56e9e63bd439829b5eaf0270586d";
    url = "https://go.dev/dl/go1.19.10.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "8b045a483d3895c6edba2e90a9189262876190dbbd21756870cdd63821810677";
    url = "https://go.dev/dl/go1.19.10.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "df98698821211c819e8b2420c77a0f802d989e377718578a31b1f91f6be2c5b4";
    url = "https://go.dev/dl/go1.19.10.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "937f885c35f191be4c6a618868ae0dbbb15b0213925a1a104d122eba02622356";
    url = "https://go.dev/dl/go1.19.10.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "726256cd435a39aba76e5e8ea7e6e7cc4bca0fbe023d00f11690d7c95a9648dd";
    url = "https://go.dev/dl/go1.19.10.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "3c6598e8a4db1cb87847c4698e5774303a21c8849584419f16d760a8093e0b5e";
    url = "https://go.dev/dl/go1.19.10.linux-s390x.tar.gz";
  };
}
