# Auto-generated by goscrape - do not edit manually
{
  version = "1.20.7";
  date = "2023-08-01";

  "x86_64-darwin" = {
    sha256 = "785170eab380a8985d53896808b0a71336d0ea60e0a26099b4ccec77798b1cf4";
    url = "https://go.dev/dl/go1.20.7.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "eea1e7e4c2f75c72629050e6a6c7c46c446d64056732a7787fb3ba16ace1982e";
    url = "https://go.dev/dl/go1.20.7.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "d8cff0357ac24eb06f3f280535397eeaacf95611d29f9b2abc3060f3d6dce3b4";
    url = "https://go.dev/dl/go1.20.7.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "26918dcebf474a9e81ccf9f648cdf36968dfb76b481518cf615d78455dda4416";
    url = "https://go.dev/dl/go1.20.7.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "ddb48145f05bda2f4617a22c979d4e94b22802cdb1a1fde1b1974e733b26f091";
    url = "https://go.dev/dl/go1.20.7.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "f0a87f1bcae91c4b69f8dc2bc6d7e6bfcd7524fceec130af525058c0c17b1b44";
    url = "https://go.dev/dl/go1.20.7.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "44781ae3b153c3b07651d93b6bc554e835a36e2d72a696281c1e4dad9efffe43";
    url = "https://go.dev/dl/go1.20.7.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7cc231b415b94f2f7065870a73f67dd2b0ec12b5a98052b7ee0121c42bc04f8d";
    url = "https://go.dev/dl/go1.20.7.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "6318a1db307c12b8afe68808bd6fae4fba1e558a85b958216096869ed506dcb3";
    url = "https://go.dev/dl/go1.20.7.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "26aea2ede8722ceecbd9db883328a8d963136fd96c11dacc356c44c4c19c6515";
    url = "https://go.dev/dl/go1.20.7.linux-s390x.tar.gz";
  };
}
