# Auto-generated by goscrape - do not edit manually
{
  version = "1.20rc1";
  date = "2022-12-07";

  "x86_64-darwin" = {
    sha256 = "bd7f6b14655d83126b85331b1c99032b4417982377ff1ee4cb0b4fa955935e52";
    url = "https://go.dev/dl/go1.20rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "05b80ba6576e4f7070f7c0ae7d4381768adbf183d1e3cb13bbdfba5b4577ebcf";
    url = "https://go.dev/dl/go1.20rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "3a24e5b8f36fb70e602f8cfe3cd10ce75efe70f240707817a9379a1058929fba";
    url = "https://go.dev/dl/go1.20rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "34be3f369754286c06bfbece8feb874cc387f85ee8e1b2e6f75d6fa73ff209d6";
    url = "https://go.dev/dl/go1.20rc1.freebsd-amd64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "a6e90a0c39d55d7d671090cfd25e4b24447b9be3c6e12c142f18adb65687df12";
    url = "https://go.dev/dl/go1.20rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "4757fb32d7514145e43d4f37713f98d8cc0ecbbb5b1737accfc84be50e1e2e32";
    url = "https://go.dev/dl/go1.20rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "dfc64ba011710565821cc97a2685c5afe3b9cbd5a3e3b665ffb3384d15c5ae50";
    url = "https://go.dev/dl/go1.20rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "518267b51750d3831c535d1bc734355f4ebec7f9a9ef7142b7138c7491088b1f";
    url = "https://go.dev/dl/go1.20rc1.linux-armv6l.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "62baa88b916958410bc25330ec695c258fb5fd6e0009eafcca8da7818f9b31a3";
    url = "https://go.dev/dl/go1.20rc1.linux-ppc64le.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "767fafebdc2dacc70f7a02dab4ae3ef4fae004108b974771dd84c8844222c074";
    url = "https://go.dev/dl/go1.20rc1.linux-s390x.tar.gz";
  };
}
