# Auto-generated by goscrape - do not edit manually
{
  version = "1.21.9";
  date = "2024-04-03";

  "x86_64-darwin" = {
    sha256 = "c0599a349b8d4a1afa3a1721478bb21136ab96c0d75b5f0a0b5fdc9e3b736880";
    url = "https://go.dev/dl/go1.21.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "3411600bd7596c57ae29cfdb4978e5d45cafa3f428a44a526ad5a2d5ad870506";
    url = "https://go.dev/dl/go1.21.9.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "36f34b0ece2de97ac51a87ef313c394c630d7548d4e7428d48e3a1d2276b7972";
    url = "https://go.dev/dl/go1.21.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "c4172ddee1c80bbf60bac24bcb2d549c0a23c6dd138a40a521db59101503b0b9";
    url = "https://go.dev/dl/go1.21.9.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "25c10b17f9bf196fb2d2c72420d4fcd038a4a10bc424a8e19af56e3326b29153";
    url = "https://go.dev/dl/go1.21.9.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "a8ba72a03dd7e6e5b8827754153b0dc335361343535b733d666c458e30996b4a";
    url = "https://go.dev/dl/go1.21.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "f76194c2dc607e0df4ed2e7b825b5847cb37e34fc70d780e2f6c7e805634a7ea";
    url = "https://go.dev/dl/go1.21.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "4d169d9cf3dde1692b81c0fd9484fa28d8bc98f672d06bf9db9c75ada73c5fbc";
    url = "https://go.dev/dl/go1.21.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "3d53e0fc659a983bbca3ffa373fab26093d8b1d94198a503be19003a1d73ffb3";
    url = "https://go.dev/dl/go1.21.9.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "5d5ac62d65489b7d7b28022845e1228b54f945f9fa7c29472b321141a5f898c0";
    url = "https://go.dev/dl/go1.21.9.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "6eadde4149c36dae7d9a9bd9385285db1d0e2988350822f4c72a5eb11ffbfffc";
    url = "https://go.dev/dl/go1.21.9.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "b92dcc990298d68652e28f3bec57824de99a328b8e584a31490b96fe4bd973c5";
    url = "https://go.dev/dl/go1.21.9.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "05daee44fc4771b2a2471b678a812de2488f05110976faeb8bbbae740e01e7ae";
    url = "https://go.dev/dl/go1.21.9.linux-s390x.tar.gz";
  };
}
