# Auto-generated by goscrape - do not edit manually
{
  version = "1.23.1";
  date = "2024-09-05";

  "x86_64-darwin" = {
    sha256 = "488d9e4ca3e3ed513ee4edd91bef3a2360c65fa6d6be59cf79640bf840130a58";
    url = "https://go.dev/dl/go1.23.1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "e223795ca340e285a760a6446ce57a74500b30e57469a4109961d36184d3c05a";
    url = "https://go.dev/dl/go1.23.1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "cc957c1a019702e6cdc2e257202d42799011ebc1968b6c3bcd6b1965952607d5";
    url = "https://go.dev/dl/go1.23.1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "a7d57781c50bb80886a8f04066791956d45aa3eea0f83070c5268b6223afb2ff";
    url = "https://go.dev/dl/go1.23.1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "b05cd6a77995a0c8439d88df124811c725fb78b942d0b6dd1643529d7ba62f1f";
    url = "https://go.dev/dl/go1.23.1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "cdee2f4e2efa001f7ee75c90f2efc310b63346cfbba7b549987e9139527c6b17";
    url = "https://go.dev/dl/go1.23.1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "49bbb517cfa9eee677e1e7897f7cf9cfdbcf49e05f61984a2789136de359f9bd";
    url = "https://go.dev/dl/go1.23.1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "faec7f7f8ae53fda0f3d408f52182d942cc89ef5b7d3d9f23ff117437d4b2d2f";
    url = "https://go.dev/dl/go1.23.1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "6c7832c7dcd8fb6d4eb308f672a725393403c74ee7be1aeccd8a443015df99de";
    url = "https://go.dev/dl/go1.23.1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "649ce3856ddc808c00b14a46232eab0bf95e7911cdf497010b17d76656f5ca4e";
    url = "https://go.dev/dl/go1.23.1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "042888cae54b5fbfd9dd1e3b6bc4a5134879777fe6497fc4c62ec394b5ecf2da";
    url = "https://go.dev/dl/go1.23.1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "1a4a609f0391bea202d9095453cbfaf7368fa88a04c206bf9dd715a738664dc3";
    url = "https://go.dev/dl/go1.23.1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "47dc49ad45c45e192efa0df7dc7bc5403f5f2d15b5d0dc74ef3018154b616f4d";
    url = "https://go.dev/dl/go1.23.1.linux-s390x.tar.gz";
  };
}
