# Auto-generated by goscrape - do not edit manually
{
  version = "1.24rc2";
  date = "2025-01-16";

  "x86_64-darwin" = {
    sha256 = "52e4be7607e6de43379b9161cc313bd5042b669e16a68f90f88b8206d7d117a8";
    url = "https://go.dev/dl/go1.24rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "66c0299808cb02555031f6bf0a9bb9d57419178c4d182caebee126e53d906a58";
    url = "https://go.dev/dl/go1.24rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b048917a083bd359311432e17c2028d5104c42264c69d47c23b46ab3f1783027";
    url = "https://go.dev/dl/go1.24rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "a1217545663d389c048b74f86b6a7088ea4893d3ff02c374f48de87e427ab575";
    url = "https://go.dev/dl/go1.24rc2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "de598362f0f0b5de5ec0e4dca8f010549ce865523a91b7e7c2197e3d4ab7db93";
    url = "https://go.dev/dl/go1.24rc2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "451b6990886631a0dbf43cf99b6478f103bfe77798fe4eaee06ee47c15494b08";
    url = "https://go.dev/dl/go1.24rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "3835e217efb30c6ace65fcb98cb8f61da3429bfa9e3f6bb4e5e3297ccfc7d1a4";
    url = "https://go.dev/dl/go1.24rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "dc8009c89676b2af4410f96ddd815dd0e68047cf97c96a708bf68bf403ff3ef9";
    url = "https://go.dev/dl/go1.24rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d074e52a89822692443d33f2342065935e32d5346bc874ddc1e7f2105321f090";
    url = "https://go.dev/dl/go1.24rc2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "6fcafe3f09cae127f0cfbc651671f39f00f317f4297f66f4c7ebdc426c49fa3e";
    url = "https://go.dev/dl/go1.24rc2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "911fe8c27b7fcc380dafe3c9aff2b5707f3411f331bb9ec130e6dfbce34ba520";
    url = "https://go.dev/dl/go1.24rc2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "0a9a0d015b978f0a39d555de03b01dae6375e9a65747cd5335f61229c267140d";
    url = "https://go.dev/dl/go1.24rc2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "994dedbe337c81134ae4d5883c8d4420e467c48b958894d3a4c50e6b160ca313";
    url = "https://go.dev/dl/go1.24rc2.linux-s390x.tar.gz";
  };
}
