# Auto-generated by goscrape - do not edit manually
{
  version = "1.25.9";
  date = "2026-04-07";

  "x86_64-darwin" = {
    sha256 = "92cb78fba4796e218c1accb0ea0a214ef2094c382049a244ad6505505d015fbe";
    url = "https://go.dev/dl/go1.25.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "9528be7329b9770631a6bd09ca2f3a73ed7332bec01d87435e75e92d8f130363";
    url = "https://go.dev/dl/go1.25.9.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "1e14a73bc2b19e370e0d4c57ba87aabfe8aef1e435e14d246742d48a13254f36";
    url = "https://go.dev/dl/go1.25.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "00859d7bd6defe8bf84d9db9e57b9a4467b2887c18cd93ae7460e713db774bc1";
    url = "https://go.dev/dl/go1.25.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "ec342e7389b7f489564ed5463c63b16cf8040023dabc7861256677165a8c0e2b";
    url = "https://go.dev/dl/go1.25.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "7d4f0d266d871301e08ef4ac31c56e66048688893b2848392e5c600276351ee8";
    url = "https://go.dev/dl/go1.25.9.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "2d67dbdfd09c6fcaa0e64485367ef43b8837ea200c663d6417183237bcddf83d";
    url = "https://go.dev/dl/go1.25.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "9152d0c0badbfeb0c0e148e47c12bec28099d8cf2db60958810c879e0b679d07";
    url = "https://go.dev/dl/go1.25.9.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "4c0fe53977412036fc8081e8d0992bbaabe4d3e1926137271ba11c2f5753300f";
    url = "https://go.dev/dl/go1.25.9.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "f3460d901a14496bc609636e4accf9110ee1869d41c64af7e29cd567cffcf49b";
    url = "https://go.dev/dl/go1.25.9.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "b0c41c7da1fc8d39020d65296a0dc54167afd9f76d67064e22c31ce3d839a739";
    url = "https://go.dev/dl/go1.25.9.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "2a630be8f854177c13e5fa75f7812c721369ecb9bd6e4c0fb1bd1c708d08b37c";
    url = "https://go.dev/dl/go1.25.9.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "0cf55136ac7eaccfc36d849054f849510ea289c2d959ffbed7b3866b4f484d17";
    url = "https://go.dev/dl/go1.25.9.linux-s390x.tar.gz";
  };
}
