# Auto-generated by goscrape - do not edit manually
{
  version = "1.25rc1";
  date = "2025-06-11";

  "x86_64-darwin" = {
    sha256 = "1c0ba988b1457f845bcb3d7efedf4f2fed072fc0d5cad64b90091513df9530d5";
    url = "https://go.dev/dl/go1.25rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "8df00c64e37e13270add03560ba2f11a7e2c498ae1e122065f694d79682c05d4";
    url = "https://go.dev/dl/go1.25rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "87b0efcff938e29b3d2b3347c9d5ea65a5b95b56f0fec6ca283275473e8c1461";
    url = "https://go.dev/dl/go1.25rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "ad7c5df8c8e30a14bcf01c00e07e87325c07099f592eb1fd14b2710597d24a8e";
    url = "https://go.dev/dl/go1.25rc1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "5351def99069bef3e04d359315c67aa752cf5fa4ffdbcafda4bfbd1a955605ef";
    url = "https://go.dev/dl/go1.25rc1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "4fb3aee891b70edee4423fb457546a30341a7b112c38594af4ee5f6db77ac376";
    url = "https://go.dev/dl/go1.25rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "7588a720e243e4672e0dc1c7942ec7592d480a80440fa2829be8b22c9c44a5b7";
    url = "https://go.dev/dl/go1.25rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "ee0b82bc1421c66f3f322a214218b423beddb64182e0105dbff142e777e96fc1";
    url = "https://go.dev/dl/go1.25rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "96a18398bc2bbbb2a144e0f30c431a1508351d43c1b1194c7647ca4a967dbc69";
    url = "https://go.dev/dl/go1.25rc1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "45ea7475fbd63ec5c46be274af0f8e8145a2980d353b83312b28b57380c89259";
    url = "https://go.dev/dl/go1.25rc1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "1ffd0793a1288854e73096c673597854d30d065f18dc5803f39b8c729aa65f7b";
    url = "https://go.dev/dl/go1.25rc1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "3e5fbc8fdc44a8bbd1b2393a6cc369eb6f43f99d424e0b01b1e38977989239fd";
    url = "https://go.dev/dl/go1.25rc1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "bfcea7cc93ab874185ef6c66a66dacc34ab01dbd03c4d0e5aad3d360c1a6c324";
    url = "https://go.dev/dl/go1.25rc1.linux-s390x.tar.gz";
  };
}
