# Auto-generated by goscrape - do not edit manually
{
  version = "1.25.11";
  date = "2026-06-02";

  "x86_64-darwin" = {
    sha256 = "26d0ee4071de42b5c332337db9fdd234072877697c547e46e85efb0f59507c66";
    url = "https://go.dev/dl/go1.25.11.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "cd8d4920e7930d55da1a5a57ba43a64b1305f71cdf2ca3c76cd8c549272b1680";
    url = "https://go.dev/dl/go1.25.11.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "a2556ed17549cbec782f4c577c1bd7ad0d0decacffd2666a804304c320a1abe9";
    url = "https://go.dev/dl/go1.25.11.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "34f14304e856893f4ba30c2cacfe93906e9de7915c5f6aaaf3a81cdccd7ba30b";
    url = "https://go.dev/dl/go1.25.11.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "c30bf9e156a54ea4e31fbbbf31a712b32734b58cc9a22426fa5ee632d0885124";
    url = "https://go.dev/dl/go1.25.11.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "492d69badee59cae12e9a36282dfce94041bd4aac88fdddea575a7d99a2bd05d";
    url = "https://go.dev/dl/go1.25.11.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "3044213e0ea7d395bba90f73845d2155096d1c2223af9ce516ab77c769e3ab51";
    url = "https://go.dev/dl/go1.25.11.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "e51b50a1ee4bf136002c5595d2c1efac6dda0c465a46ad2571d83f89c83c729e";
    url = "https://go.dev/dl/go1.25.11.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "cd661c1647c43edfbb9c98d8fabfdaa6c836e714a97632dfaf66bd303f8db96c";
    url = "https://go.dev/dl/go1.25.11.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "b8ddd4b92fe2f7c3da80eed25cfcb6a78a90bb00c99bbeed10fa6779e53e7b05";
    url = "https://go.dev/dl/go1.25.11.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "2d3d498b9dac8e6d53dfcdda9629079ff2dfde58554bd63eb101a0861bf37249";
    url = "https://go.dev/dl/go1.25.11.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "3489cdeadbfaee949f202805673837856ab24cced2ed64ba03c27ad523126904";
    url = "https://go.dev/dl/go1.25.11.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "5b6f69df0df910d679442b4695051d82ffa06feb68d96fe975e0da8eeb5391d8";
    url = "https://go.dev/dl/go1.25.11.linux-s390x.tar.gz";
  };
}
