# Auto-generated by goscrape - do not edit manually
{
  version = "1.25rc3";
  date = "2025-08-06";

  "x86_64-darwin" = {
    sha256 = "0a0721d178ed460707d7874276c0890de7aa95780e56538c50c767c00d96d541";
    url = "https://go.dev/dl/go1.25rc3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "6f055697762295e31591aa2cf12c3e87b2de94e8a1c860b3ef7c956ebec7453c";
    url = "https://go.dev/dl/go1.25rc3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "f6b337ebe5149ba7e3b8e99159b2ae9297d9a987f7d96536e925684dd11bb5ca";
    url = "https://go.dev/dl/go1.25rc3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "277a2a2ec302873b751d7c00a680f0834adea3e19e8c8822aa9be2f5e96a4854";
    url = "https://go.dev/dl/go1.25rc3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "edb9aba1da875b4b4cde2734d667a948a361cd93f05b81017955451b1012aba7";
    url = "https://go.dev/dl/go1.25rc3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "337d124f69d81bbfd434fae0e25466f13245c6386d87e783d1fcf14a3261eb9b";
    url = "https://go.dev/dl/go1.25rc3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "e6c08a140ae7c28770eeb246934981fe5095ecc92ec232571497c22a7588960e";
    url = "https://go.dev/dl/go1.25rc3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "5b07f421b2a9b477da5ba3cc62e24a85fb28b2f83f6db081896bcf0d2e76cfd2";
    url = "https://go.dev/dl/go1.25rc3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "82d5157bfe441100f96601da77e1951301904a36d85d6497d9f524544c83bf0f";
    url = "https://go.dev/dl/go1.25rc3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "f39a75ccf50ecb84f2d2905104b354849b8dd0f3cf4b87d7b2fbe4a66950383b";
    url = "https://go.dev/dl/go1.25rc3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "ea1f0d96e903f97ab7e805ed072b41117ff80dc6f2113b846067e7e7563cf88d";
    url = "https://go.dev/dl/go1.25rc3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "ad8d5f24a60731ec0e32b195f0db8c642c3ff7983902ab03d577191f33e134b5";
    url = "https://go.dev/dl/go1.25rc3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "ee2e34bc2bc3dc7f90cb51787512221c2a3032dd4358604e0273e1cf76b076b9";
    url = "https://go.dev/dl/go1.25rc3.linux-s390x.tar.gz";
  };
}
