# Auto-generated by goscrape - do not edit manually
{
  version = "1.26.9";
  date = "2026-10-08";

  "x86_64-darwin" = {
    sha256 = "00c29e3d4c8562f547410daa18d2959b641bd691ab00c4a525ea817a0253d4bd";
    url = "https://go.dev/dl/go1.26.9.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "f9bb7c0a02506c5d9bf0d1eb1f7ee6c7684f844ae49558308a0427b830e022cc";
    url = "https://go.dev/dl/go1.26.9.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "dea88a548986e02d02f6f24f7ea8a886cd5d6e583419247955a140cd84a74d77";
    url = "https://go.dev/dl/go1.26.9.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "42d158b4d8f7b61ac0a830567c940a86098fb7aac52e467a5ebec03ef5cc2f8d";
    url = "https://go.dev/dl/go1.26.9.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "4a97373d49fcacdcf3694fea368a500b00ee3e963974f3e7514132717632f052";
    url = "https://go.dev/dl/go1.26.9.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "4e7427224d6200800b8c8b9b05b2cb1868df0fb950f57843cf51b1060d91a0c8";
    url = "https://go.dev/dl/go1.26.9.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "416ecb5a84edd957c23137a3ffccad641fe532dae0e7c3d72fb78b94fa1ba652";
    url = "https://go.dev/dl/go1.26.9.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "9a2928c12bba7357fd8f24143fb0f400882d3081406bf0ef87b3857635b02fea";
    url = "https://go.dev/dl/go1.26.9.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "df0323ac1b496464ff7ab32f3bd8206b189c167f3e1759005fc012df4a3051d2";
    url = "https://go.dev/dl/go1.26.9.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "67f722b1975dde7df926c3c928a891639d176a2dc7c8c7fcabb575d9f35f195d";
    url = "https://go.dev/dl/go1.26.9.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "a21a65001146ca0c6c022c690d5418f8298c5513a81fb5eed42f6cdb29f40063";
    url = "https://go.dev/dl/go1.26.9.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "05cc69a7d000154d5913527bbb6cbad89808fb7362e5ab83949b1a269112665e";
    url = "https://go.dev/dl/go1.26.9.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "4cea4b77caedc8869a4f1f9301ec42b526e09020f72235d019acacd2c4441550";
    url = "https://go.dev/dl/go1.26.9.linux-s390x.tar.gz";
  };
}
