# Auto-generated by goscrape - do not edit manually
{
  version = "1.26rc2";
  date = "2026-01-15";

  "x86_64-darwin" = {
    sha256 = "9a99124affe3e1c0a72ec87b5c6143c66aa534276981f4a3d490bdc81f1efbd5";
    url = "https://go.dev/dl/go1.26rc2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "c3aa4746d672c2ce0afff9b624e4856a08479b0b85d08dd24099845d9c746739";
    url = "https://go.dev/dl/go1.26rc2.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "b3955b06d26f95e10094241081598f4693d30ccd2ddf74ac3f0812547c321d08";
    url = "https://go.dev/dl/go1.26rc2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "957969c7a159923435ae2bc941bda8d3726c7e107b9e443a771eb92350696727";
    url = "https://go.dev/dl/go1.26rc2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "b4950130e08f8cd950ce01445b575b57069c5c0018eba641846abfbfb8238a14";
    url = "https://go.dev/dl/go1.26rc2.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "cdb03b50a81e0f0ad22f99ba3730b0a58c9b9c893bec043c13ca087af9be3b4d";
    url = "https://go.dev/dl/go1.26rc2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "16e98a4ecd3ee04354685b6f0d31f67d2109d17dde9a95eaa574f5b182855b7c";
    url = "https://go.dev/dl/go1.26rc2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "f09ac34939eca35ef34907529bb77b19c6f83bd7ff1f43c624dde531aa2d3158";
    url = "https://go.dev/dl/go1.26rc2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "0dc1463b9dcb6fc4b744eb05419ac548b16e9b0e624c3c9953ec2bec9f06e60b";
    url = "https://go.dev/dl/go1.26rc2.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "992239e6a917c4d51bb70235049081a011a258296f5cf8a32f6596d951cdb0de";
    url = "https://go.dev/dl/go1.26rc2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "37dc84b474cd11ce405b78e6d909b823975bbf03962590375a0f2e4b161e9142";
    url = "https://go.dev/dl/go1.26rc2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "ba7ac60a62149a2f9259bc71d32bbee9aeb52213de88a4b14f14f083d886ee7d";
    url = "https://go.dev/dl/go1.26rc2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "b5907c5cc9285ffb3e67fd61c9fb31b88d1f0cb054146ef23c9f79ffeab7dbd3";
    url = "https://go.dev/dl/go1.26rc2.linux-s390x.tar.gz";
  };
}
