# Auto-generated by goscrape - do not edit manually
{
  version = "1.26.3";
  date = "2026-05-07";

  "x86_64-darwin" = {
    sha256 = "278d580b32e299fe4a9c990fcf2d02acfe538c7e551a6ee18f9c7164573d2c63";
    url = "https://go.dev/dl/go1.26.3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "875cf54a15311eee2c99b9dd67c68c4a49351d489ab622bf2cfd28c8f2078d3c";
    url = "https://go.dev/dl/go1.26.3.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "0ef3626a149b5811c813838c62b7d6618d03ea36047b32c90b0e4851cc42b1fa";
    url = "https://go.dev/dl/go1.26.3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "2b2cfc7148493da5e73981bffbf3353af381d5f93e789c82c79aff64962eb556";
    url = "https://go.dev/dl/go1.26.3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "9d89a3ea57d141c2b22d70083f2c8459ba3890f2d9e818e7e933b75614936565";
    url = "https://go.dev/dl/go1.26.3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "d44133d4c66b1451a1e247da26db7716f76a081c0169a75e6c84e1871e394320";
    url = "https://go.dev/dl/go1.26.3.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "270df83863a4fbeb716565e91915f54af4ed911ec503651fbce6c14f9e00018c";
    url = "https://go.dev/dl/go1.26.3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "2a5a3b0265f24cdf3878bbab19bb1086f71ae5d29566f238214847d1e3745b4e";
    url = "https://go.dev/dl/go1.26.3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "07431d472522d3e3b9fce3f5d1ea825e2fbb14d7b0b7fbfa548726654217127c";
    url = "https://go.dev/dl/go1.26.3.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "05215802b85a33dcfdb933a6c3ab881f4f0405587ee6581d33f34cc5c2ab740c";
    url = "https://go.dev/dl/go1.26.3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "dbd82b50530ead2beb1fd72215117380df3cb16332b51467116dc35b3691dd75";
    url = "https://go.dev/dl/go1.26.3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "3b8fd5112340b72587e42c619f43270f1bc21f63cfdb587e6b72e0336580727c";
    url = "https://go.dev/dl/go1.26.3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "5c0605b7175449f1c8e8cb02efaba2695caab914fad4dcedc764c2f4c6dfe6ca";
    url = "https://go.dev/dl/go1.26.3.linux-s390x.tar.gz";
  };
}
