# Auto-generated by goscrape - do not edit manually
{
  version = "1.26.7";
  date = "2026-08-19";

  "x86_64-darwin" = {
    sha256 = "92e8b34bff3c89ab16404c595669ac8cb004cc2f676dcbd1f5b87a6b8def3b47";
    url = "https://go.dev/dl/go1.26.7.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "020a1e8224811be75163e920bc77e0926a1390a6aeea19bdcf23f74b9d749f6d";
    url = "https://go.dev/dl/go1.26.7.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "5b6fad4a7fe8fa230c935625b67450305be95e2f4f976b731623f76b88fc4821";
    url = "https://go.dev/dl/go1.26.7.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "ffb5f8de10c62550dfddab66b36b57030721e0a44a3218e9e1181d7b59f121ca";
    url = "https://go.dev/dl/go1.26.7.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "5a4ec883379d51ee9ce1040d5e87f8d35e20387574dd8c947feb01eabc3c1b37";
    url = "https://go.dev/dl/go1.26.7.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "6a41557335d1d9fa9bfc7439cedcfd0e4df2fc83d916175b5f3eae4685f5fe3f";
    url = "https://go.dev/dl/go1.26.7.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "7eecfa4d6c126bcdedb8e16583ec672857e607659c672c60a9d645f8957da117";
    url = "https://go.dev/dl/go1.26.7.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "2ad37146fa8449907716b494dd268aeae6f79592b875915525c28c8c337ad32a";
    url = "https://go.dev/dl/go1.26.7.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "23d425a3a51876df8bf050f080b1ae50340048def689fbcc44c939fa23485ce0";
    url = "https://go.dev/dl/go1.26.7.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "89b5e92446e719719e23db447a41860d7d573252bab0704c9acb09ad97e9eca1";
    url = "https://go.dev/dl/go1.26.7.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "22d3b362d557175fd16b79651cab0cad64f8aaaedca745f66d16f44d56bc5de1";
    url = "https://go.dev/dl/go1.26.7.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "21e1dc0e2f7dd9f80e0e94613fc324f1f99403b99997f9d8c5f80f8132fc642b";
    url = "https://go.dev/dl/go1.26.7.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "bc3308e05e9397958ad4aac453e3dc4565ba6d548e9ace0a9b4b165feb6382f2";
    url = "https://go.dev/dl/go1.26.7.linux-s390x.tar.gz";
  };
}
