# Auto-generated by goscrape - do not edit manually
{
  version = "1.26rc3";
  date = "2026-02-04";

  "x86_64-darwin" = {
    sha256 = "5a68e9702867b3cc53dcdded6439dd476dd5f401fb82751e34628e0baf8813c0";
    url = "https://go.dev/dl/go1.26rc3.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a03c1754aaab960077e1755e8c1fc8d3daab235b004218e5a789aadec4d21c78";
    url = "https://go.dev/dl/go1.26rc3.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "6f393492dd781c7387f796e5b72182d1c7d150c533acb91974d2a3a52ef6dc40";
    url = "https://go.dev/dl/go1.26rc3.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "7cbf277ac99bbce2c60f3e6b91cbf7a180eebcc043133589f8ba4d8f3de33b22";
    url = "https://go.dev/dl/go1.26rc3.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "506292222a2545e33b937e544dc7fe2eb8e78361d645eff174f8a1be73d8584a";
    url = "https://go.dev/dl/go1.26rc3.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "b3c0ed3e37fb023510aa2d0627e018e204e0606da5524a9824e7dd431245a1d7";
    url = "https://go.dev/dl/go1.26rc3.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "5eef7fb80790d3c5339607f7b17b4b8b7b67a4c322fc636cea8820f490cede00";
    url = "https://go.dev/dl/go1.26rc3.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "7c3bf203f7ae95499914d358cad26442a3b2259ac8a79d0e21f59cef921b59bb";
    url = "https://go.dev/dl/go1.26rc3.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "616670989d950b1b70cf5999a944e2a51a5d096a5e24ab34fa757c8877611e2d";
    url = "https://go.dev/dl/go1.26rc3.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "df87dec48ecfb85710ff00aebb6c21a0d0c2112e6f2cc45e61cf73580d97417f";
    url = "https://go.dev/dl/go1.26rc3.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "9c218d68b501db4e143f97ffe243469edc1ad8e18dbc70145a1c12fa9501f9a0";
    url = "https://go.dev/dl/go1.26rc3.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "a15b0374b7395854743205fc93eb241e8312e6a7dd2e54c55673dedb71113d4b";
    url = "https://go.dev/dl/go1.26rc3.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "fb7427d956013c3869b2b3735d86f36496684356c9658f79a66c83ca9a0ec983";
    url = "https://go.dev/dl/go1.26rc3.linux-s390x.tar.gz";
  };
}
