# Auto-generated by goscrape - do not edit manually
{
  version = "1.26.8";
  date = "2026-09-01";

  "x86_64-darwin" = {
    sha256 = "186be014105aa6542b767d2c6ed5cca10a0214bdff809ef1724022a8c7894150";
    url = "https://go.dev/dl/go1.26.8.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "a012b25b571bd0138a03dcd25375ceba866fe5ca822f426d2c66a4de56fd3f4b";
    url = "https://go.dev/dl/go1.26.8.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "55115677dfcd953fa9d2fe376039125a60ff14fe0e619a2339a364860dda64ef";
    url = "https://go.dev/dl/go1.26.8.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "d0f743b33e8d8945e6b1f432edd15785c70507121d6e2a723b21285eddf8b57b";
    url = "https://go.dev/dl/go1.26.8.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "211ffced9dcb9633a55eac6364816ec0ddd951389a740e88fa8b3337971bdda0";
    url = "https://go.dev/dl/go1.26.8.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "eab440beabf395870752021fa74cedf04f97b61e43ebbe005ecbb98b94e55697";
    url = "https://go.dev/dl/go1.26.8.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "2a082608129d754d06ad2cb110f3a9d347ba2bf8cac91f587a2a4f21da340729";
    url = "https://go.dev/dl/go1.26.8.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "458adea37c17ce9a8754a0455fa43e84f27d7e7de3fee81041a13de40c766434";
    url = "https://go.dev/dl/go1.26.8.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "041d822e331b6c45b393bb3314ad890e4f622c4ffb6eba6cd7e934afed4158a9";
    url = "https://go.dev/dl/go1.26.8.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "64fb507c00d6f830f71a342feb80b05641b4da5d5ca1d5e06896d5572f8a458c";
    url = "https://go.dev/dl/go1.26.8.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "0ddf3ecab842013e6bd618602823a0b8158a18d3e9362f2540463ea5aa184975";
    url = "https://go.dev/dl/go1.26.8.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "75d368eef1dc44ff9de0c8cac4b37c519e541e6d46c4291c1ff959644a71af32";
    url = "https://go.dev/dl/go1.26.8.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "339d1a09716815f737cb5ddd355e04e339312b449c268cc417118f4b8137ddd1";
    url = "https://go.dev/dl/go1.26.8.linux-s390x.tar.gz";
  };
}
