# Auto-generated by goscrape - do not edit manually
{
  version = "1.26rc1";
  date = "2025-12-16";

  "x86_64-darwin" = {
    sha256 = "c76b80ef28866b653f94525c79425e8dd19b9afbca54fffa7e02ecb1c49d465b";
    url = "https://go.dev/dl/go1.26rc1.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "f5b40648e5a1a6d1b078628d63f1feb928b76d8f43b78166532c03f53715ff4d";
    url = "https://go.dev/dl/go1.26rc1.darwin-arm64.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "323061a2250b8e66ffbcc8fddae50011bb5fd9d104ffe96dd81ddf9616a5b94e";
    url = "https://go.dev/dl/go1.26rc1.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "6603e1af32f322ee4804bfe969bae186800064783a2c2de134454b23c4157a94";
    url = "https://go.dev/dl/go1.26rc1.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "d89825004e3a2319799d7df897d1184a0fd4bba9bcd6bd0ea49805057d9e8a29";
    url = "https://go.dev/dl/go1.26rc1.freebsd-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "88766dabe34bf9b8a422e5a0788b695a27f0c45b4ce3c1c293ec948d72577f34";
    url = "https://go.dev/dl/go1.26rc1.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "b395b5d51d45cf2a19e61855edd7bafaa2dfeaafaf8d9649cb3262fd8b81a96a";
    url = "https://go.dev/dl/go1.26rc1.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "b254925e2bc55467595e9d9b15a4f61a9102d763a92a972c853e471f0e8365a9";
    url = "https://go.dev/dl/go1.26rc1.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "53cb2acc73ae9fe6ca1c94c6798abcdf3ed879202f9bd968f6e1ab0aa23b8212";
    url = "https://go.dev/dl/go1.26rc1.linux-armv6l.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "7449ed873f5b8a04bc8f9e9a121ac7731925f8246c6b24e2fab6d6e9bad428fe";
    url = "https://go.dev/dl/go1.26rc1.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "56ea825c6f3ded35af6109108daa14935f31ef7abbf8f410a8a0a428bc6e6de2";
    url = "https://go.dev/dl/go1.26rc1.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "00ce26401dd50045ca398128a9de1d91fbafbb38cb7706d9c64c13619c6439b3";
    url = "https://go.dev/dl/go1.26rc1.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "a34cd098dea5c1f53b366a1c6070ab42000437a618696d293e2023a5f91c3df8";
    url = "https://go.dev/dl/go1.26rc1.linux-s390x.tar.gz";
  };
}
