# Auto-generated by goscrape - do not edit manually
{
  version = "1.27.0";
  date = "2026-08-19";

  "x86_64-darwin" = {
    sha256 = "d3314e25496e4381d71a5c51d2907e7af655d199f6780b549f015bd85fef4986";
    url = "https://go.dev/dl/go1.27.0.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "90493b3bbd5e10f91d12153198bf1994fd756399b4fec93b49b0c6e2acdeeb3e";
    url = "https://go.dev/dl/go1.27.0.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "eac4abaca4113170a1cf261b8bf1d38480e61e99deecbc6a14767deb8b19e8ad";
    url = "https://go.dev/dl/go1.27.0.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "675c26c449cbb18fc24b74650de1eabbae6e16f64326fd85a283fb3b58280685";
    url = "https://go.dev/dl/go1.27.0.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "51798d2c42d0e1c6ed7fd9f48728b4193abac9e8aad6dbac2fe96a81f5909bda";
    url = "https://go.dev/dl/go1.27.0.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e337ecd9c321377c0d8832690c2cb10463447c0bd0e65e2e3413dfff63a3435b";
    url = "https://go.dev/dl/go1.27.0.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "db350b8961e4b01e0d0f3d4e4f98d6218bdab84ca112dedb27f1463c887d437f";
    url = "https://go.dev/dl/go1.27.0.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "2c24ddcca6dbd5e0be775a48cec4171e9ca616e654b63b02c9cbc515238dae31";
    url = "https://go.dev/dl/go1.27.0.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "0d33b993d26337cd4cedaa57d4d0fec71c4b578a5b47d8d08cb153eb337b27c7";
    url = "https://go.dev/dl/go1.27.0.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "a1f198e34c8bc42a4a9393220cfc5b6299b27c3e9c641b9399f576965c4f760c";
    url = "https://go.dev/dl/go1.27.0.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "068085e257a6014c036c723ca62943edbf48fd168b8d00a6d39527d10b656255";
    url = "https://go.dev/dl/go1.27.0.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "e631e2e1e5aec4979960787f5f8cdb549001bb144c279e134447e54ffe8bd2d3";
    url = "https://go.dev/dl/go1.27.0.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "cb5c89fa48cba4123c68aee62b217ca030f281546df0898a0c32889c340b928c";
    url = "https://go.dev/dl/go1.27.0.linux-s390x.tar.gz";
  };
}
