# Auto-generated by goscrape - do not edit manually
{
  version = "1.27.2";
  date = "2026-10-08";

  "x86_64-darwin" = {
    sha256 = "587b59182488b23aa6e5fc25110405a3e0e5b38ed2f5b2f46ed13c32aee356fe";
    url = "https://go.dev/dl/go1.27.2.darwin-amd64.tar.gz";
  };
  "aarch64-darwin" = {
    sha256 = "76812b213b1b2302c978d28fa52fa92d541704b9e7d9d5db8002c50e4018c4c5";
    url = "https://go.dev/dl/go1.27.2.darwin-arm64.tar.gz";
  };
  "i686-linux" = {
    sha256 = "93dae4b7f463ed1e9c65e05561ce9fc5f7cd5c4ffca5e336248d48f3a2eab5fc";
    url = "https://go.dev/dl/go1.27.2.linux-386.tar.gz";
  };
  "x86_64-linux" = {
    sha256 = "ecbadb99091a3f46e31f5f934b068b1864eafa7995211b39eaddf76996045fe5";
    url = "https://go.dev/dl/go1.27.2.linux-amd64.tar.gz";
  };
  "aarch64-linux" = {
    sha256 = "94f3e30b8e374bc285e7dadc11e0865726b9bc6e85b841ccceaabc0214c6b7c8";
    url = "https://go.dev/dl/go1.27.2.linux-arm64.tar.gz";
  };
  "armv7l-linux" = {
    sha256 = "e25a174051d8675f87ac720aedcd25bf89ac652c4b82f26aa47919524725ed95";
    url = "https://go.dev/dl/go1.27.2.linux-armv6l.tar.gz";
  };
  "i686-freebsd" = {
    sha256 = "ebbee6bf21224ca07bcb0309e81fe24bb4464a1a12b944bbe2c7b6daf0f2bd13";
    url = "https://go.dev/dl/go1.27.2.freebsd-386.tar.gz";
  };
  "x86_64-freebsd" = {
    sha256 = "3baf61eec549b0c3f638d82636388e36abf94aa14814a011f011d2648ad1eded";
    url = "https://go.dev/dl/go1.27.2.freebsd-amd64.tar.gz";
  };
  "aarch64-freebsd" = {
    sha256 = "b77d9b8aa9cde90e1045a13f6166e46e370ef7225556e9c2043d351c59557ecb";
    url = "https://go.dev/dl/go1.27.2.freebsd-arm64.tar.gz";
  };
  "loongarch64-linux" = {
    sha256 = "b49a3b2f090934ca588c7a897d64bc12f844348a2cd35e301d8f4f50eaf3bfdb";
    url = "https://go.dev/dl/go1.27.2.linux-loong64.tar.gz";
  };
  "powerpc64le-linux" = {
    sha256 = "059d5f01b1607a724ea5ae87c5589041a51c577a6f3f20099e49d00f31c803fa";
    url = "https://go.dev/dl/go1.27.2.linux-ppc64le.tar.gz";
  };
  "riscv64-linux" = {
    sha256 = "420f3b8dac8b5a9d11f51e12b496ac27f02ab31cbe495067e355ed43b9fe3aa1";
    url = "https://go.dev/dl/go1.27.2.linux-riscv64.tar.gz";
  };
  "s390x-linux" = {
    sha256 = "dfd01d1e08e4dbece2cd91e259953f87b858752037fd151da2f674c4fa09aeef";
    url = "https://go.dev/dl/go1.27.2.linux-s390x.tar.gz";
  };
}
