package godev

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gotest.tools/v3/golden"
)

const fakeGoManifest = `# Auto-generated by goscrape - do not edit manually
{
  version = "%s";
  date = "%s";

  "x86_64-linux" = {
    sha256 = "fake";
    url = "https://go.dev/dl/go%s.linux-amd64.tar.gz";
  };
}
`

func writeFakeGoManifests(t *testing.T, dir string, versions map[string]string) {
	t.Helper()
	for ver, date := range versions {
		content := fmt.Sprintf(fakeGoManifest, ver, date, ver)
		require.NoError(t, os.WriteFile(filepath.Join(dir, ver+".nix"), []byte(content), 0o644))
	}
}

func TestWriteIndex(t *testing.T) {
	dir := t.TempDir()

	// Deliberately includes prereleases and two-digit patches: lexical or
	// semver ordering would misplace 1.21rc2, 1.17beta1 and 1.21.10.
	writeFakeGoManifests(t, dir, map[string]string{
		"1.17beta1": "2021-06-10",
		"1.20.14":   "2024-02-06",
		"1.21rc2":   "2023-06-21",
		"1.21.0":    "2023-08-08",
		"1.21.9":    "2024-04-03",
		"1.21.10":   "2024-05-07",
	})

	require.NoError(t, writeIndex(dir))

	got, err := os.ReadFile(filepath.Join(dir, "index.nix"))
	require.NoError(t, err)

	golden.Assert(t, string(got), "index.nix.golden")
}

func TestWriteIndexIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	writeFakeGoManifests(t, dir, map[string]string{
		"1.25.5": "2025-12-02",
		"1.26.0": "2026-02-10",
	})

	require.NoError(t, writeIndex(dir))
	first, err := os.ReadFile(filepath.Join(dir, "index.nix"))
	require.NoError(t, err)

	// The second run sees the index.nix written by the first and must skip it.
	require.NoError(t, writeIndex(dir))
	second, err := os.ReadFile(filepath.Join(dir, "index.nix"))
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second))
}

func TestWriteIndexMissingDate(t *testing.T) {
	dir := t.TempDir()
	content := "# Auto-generated by goscrape - do not edit manually\n{\n  version = \"1.25.5\";\n}\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "1.25.5.nix"), []byte(content), 0o644))

	err := writeIndex(dir)
	assert.ErrorContains(t, err, "1.25.5.nix has no top-level date")
}

func TestWriteIndexRejectsAFileNotNamedAfterAGoVersion(t *testing.T) {
	dir := t.TempDir()
	writeFakeGoManifests(t, dir, map[string]string{"1.25.5": "2025-12-02"})
	require.NoError(t, os.WriteFile(filepath.Join(dir, "default.nix"), []byte("{}\n"), 0o644))

	err := writeIndex(dir)
	assert.ErrorContains(t, err, "default.nix is not named after a Go version")
}
