name: nix-checks
on:
  push:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "default.nix"
      - "lib/**"
      - "builder/**"
      - "test/**"
      - "govendor.toml"
  pull_request:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "default.nix"
      - "lib/**"
      - "builder/**"
      - "test/**"
      - "govendor.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    name: checks / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Run all checks
        run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake .#checks

  integration-in-tree-vendor:
    runs-on: ${{ matrix.os }}
    name: integration-in-tree-vendor / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Build and run in-tree vendor integration test
        run: |
          cd test/integration/in-tree-vendor
          nix run ./../../..#go -- mod vendor
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./../../..);
              system = builtins.currentSystem;
              pkgs = import flake.inputs.nixpkgs {
                inherit system;
                overlays = [ flake.overlays.default ];
              };
            in import ./. {
              inherit pkgs;
              go = pkgs.go-bin.fromGoMod ./../../../go.mod;
            }
          '
          ./result/bin/integration-in-tree-vendor

      - name: Build and run workspace in-tree vendor integration test
        run: |
          cd test/integration/workspace-in-tree-vendor
          nix run ./../../..#go -- work vendor
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./../../..);
              system = builtins.currentSystem;
              pkgs = import flake.inputs.nixpkgs {
                inherit system;
                overlays = [ flake.overlays.default ];
              };
            in import ./. {
              inherit pkgs;
              go = pkgs.go-bin.fromGoMod ./../../../go.mod;
            }
          '
          ./result/bin/api
