name: nix-checks
on:
  push:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "default.nix"
      - "lib/**"
      - "builder/**"
      - "test/**"
      - "examples/**"
      - "govendor.toml"
  pull_request:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "default.nix"
      - "lib/**"
      - "builder/**"
      - "test/**"
      - "examples/**"
      - "govendor.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    name: checks / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.GH_CACHIX }}

      - name: Run all checks
        run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --max-jobs 2 --flake .#checks
