name: nix-go-toolchain
on:
  push:
    branches:
      - main
    paths:
      - "manifests/go/**"
  pull_request:
    branches:
      - main
    paths:
      - "manifests/go/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: build / ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: harden_runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup_nix
        uses: $/.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.GH_CACHIX }}
          push-to-cachix: "true"

      - name: build_toolchain
        run: nix build
